//! `cli-reference`: the complete flag table, generated from the clap surface.
//!
//! The book's `cli.md` is a curated narrative — it explains the model and the flags
//! that carry it, and it is the better page to read. What a narrative cannot do is stay
//! *complete*: a flag added in [`crate::args`] appears here the moment it exists, and a
//! committed page that no longer matches fails this module's staleness test.
//!
//! Every string below comes from the command tree itself — the same `///` doc comments
//! `--help` renders — so this module decides layout and nothing else. There is no
//! second place to describe a flag, and therefore no second place for a description to
//! drift.

use clap::{Command, CommandFactory};

/// Run `cli-reference [--markdown]`.
///
/// `--markdown` exists to name the intent — this is what regenerates the committed
/// page — rather than to switch formats: the reference *is* Markdown, and a second
/// rendering of the same tables would be a second thing to keep correct.
pub(crate) fn run(_markdown: bool) -> Result<(), Box<dyn std::error::Error>> {
    print!("{}", render(&crate::args::Cli::command()));
    Ok(())
}

/// The generated page: a preamble, the global flags, then one table per subcommand.
///
/// Subcommands keep the order they are declared in, which is the order the workflow
/// runs in (inspect → scaffold → update → verify → build → clean), not alphabetical.
/// A reader scanning for "what comes after update" is better served by the order the
/// tool itself is organized around.
fn render(cli: &Command) -> String {
    let mut s = String::new();
    s.push_str(
        "<!-- Generated by `boot2deb cli-reference --markdown`; do not hand-edit.\n     \
         Regenerate after adding, removing, or re-describing any flag. -->\n\n\
         # Every flag\n\n\
         The complete argument surface, generated from the command tree — so it is\n\
         exhaustive by construction, and a test fails when this page and the binary\n\
         disagree. For what the flags *mean* together, read [CLI](cli.md); this page is\n\
         the index, not the explanation.\n\n\
         Every flag is also `--help`-discoverable: `boot2deb <command> --help`.\n\n",
    );

    s.push_str("## Global\n\nAccepted by every subcommand.\n\n");
    s.push_str(&flag_table(cli));

    for sub in cli.get_subcommands() {
        let _ = std::fmt::Write::write_fmt(&mut s, format_args!("\n## {}\n\n", sub.get_name()));
        if let Some(about) = sub.get_about() {
            let _ = std::fmt::Write::write_fmt(
                &mut s,
                format_args!("{}\n\n", one_line(&about.to_string())),
            );
        }
        // A parent whose work is entirely in its children (`patch`) has no flags of its
        // own; tabling its empty set and then its children reads as two sections about
        // nothing, so the child is titled with the full invocation instead.
        let nested: Vec<&Command> = sub.get_subcommands().collect();
        if nested.is_empty() {
            s.push_str(&positional_table(sub));
            s.push_str(&flag_table(sub));
        } else {
            for child in nested {
                let _ = std::fmt::Write::write_fmt(
                    &mut s,
                    format_args!("### {} {}\n\n", sub.get_name(), child.get_name()),
                );
                if let Some(about) = child.get_about() {
                    let _ = std::fmt::Write::write_fmt(
                        &mut s,
                        format_args!("{}\n\n", one_line(&about.to_string())),
                    );
                }
                s.push_str(&positional_table(child));
                s.push_str(&flag_table(child));
            }
        }
    }
    s
}

/// The positional arguments of one command, or an empty string when it takes none.
fn positional_table(cmd: &Command) -> String {
    let args: Vec<_> = cmd.get_positionals().collect();
    if args.is_empty() {
        return String::new();
    }
    let mut s = String::from("| argument | required | what it is |\n| --- | --- | --- |\n");
    for arg in args {
        let _ = std::fmt::Write::write_fmt(
            &mut s,
            format_args!(
                "| `{}` | {} | {} |\n",
                arg.get_id(),
                if arg.is_required_set() { "yes" } else { "no" },
                describe(arg),
            ),
        );
    }
    s.push('\n');
    s
}

/// The named flags of one command, or a note when it takes none of its own.
///
/// `--help` and `--version` are omitted: clap adds them to every command, so listing
/// them per section would triple the page with one fact.
fn flag_table(cmd: &Command) -> String {
    let args: Vec<_> = cmd
        .get_arguments()
        .filter(|a| !a.is_positional())
        .filter(|a| !matches!(a.get_id().as_str(), "help" | "version"))
        .collect();
    if args.is_empty() {
        return "This command takes no flags of its own.\n".to_string();
    }
    let mut s = String::from("| flag | value | what it does |\n| --- | --- | --- |\n");
    for arg in args {
        let long = arg
            .get_long()
            .map(|l| format!("`--{l}`"))
            .unwrap_or_else(|| format!("`{}`", arg.get_id()));
        // The short form is part of how the flag is typed, so it belongs beside the
        // long one rather than in the prose.
        let name = match arg.get_short() {
            Some(c) => format!("{long}, `-{c}`"),
            None => long,
        };
        let _ = std::fmt::Write::write_fmt(
            &mut s,
            format_args!("| {name} | {} | {} |\n", value_of(arg), describe(arg)),
        );
    }
    s.push('\n');
    s
}

/// The value column: what the flag takes, and whether it repeats.
///
/// A boolean switch takes nothing, so its cell is empty rather than saying "flag" —
/// the absence *is* the information, and a filler word in every other row would bury
/// the ones that do take a value.
fn value_of(arg: &clap::Arg) -> String {
    if matches!(
        arg.get_action(),
        clap::ArgAction::SetTrue | clap::ArgAction::SetFalse
    ) {
        return String::new();
    }
    // A closed value set is more useful than a placeholder: `combined | split` says
    // what to type, where `<LAYOUT>` sends the reader back to the prose.
    let values = arg.get_possible_values();
    let mut s = if values.is_empty() {
        let placeholder = arg
            .get_value_names()
            .and_then(|n| n.first())
            .map(|n| n.to_string())
            .unwrap_or_else(|| arg.get_id().to_string().to_uppercase());
        format!("`<{placeholder}>`")
    } else {
        values
            .iter()
            .map(|v| format!("`{}`", v.get_name()))
            .collect::<Vec<_>>()
            .join(" \\| ")
    };
    if matches!(arg.get_action(), clap::ArgAction::Append) {
        s.push_str(", repeatable");
    }
    if let Some(default) = arg.get_default_values().first() {
        let _ = std::fmt::Write::write_fmt(
            &mut s,
            format_args!(" (default `{}`)", default.to_string_lossy()),
        );
    }
    s
}

/// A flag's description, from its `///` doc comment, flattened to one table cell.
fn describe(arg: &clap::Arg) -> String {
    arg.get_long_help()
        .or_else(|| arg.get_help())
        .map(|h| one_line(&h.to_string()))
        .unwrap_or_default()
}

/// Flatten multi-line help into one Markdown table cell.
///
/// Newlines become spaces (a `|` row cannot hold them), a paragraph break becomes a
/// visible separator rather than vanishing into the run-on it would otherwise make,
/// and a literal `|` is escaped so it cannot end the cell early.
fn one_line(text: &str) -> String {
    let joined = text
        .split("\n\n")
        .map(|para| para.split_whitespace().collect::<Vec<_>>().join(" "))
        .filter(|p| !p.is_empty())
        .collect::<Vec<_>>()
        .join(" — ");
    joined.replace('|', "\\|")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testsupport::repo_root_path;

    /// The page under `docs/` is generated output, and the only thing keeping a
    /// generated file honest is a gate that regenerates it. This is the test the
    /// review asked for: it closes the whole class of "a flag exists and is documented
    /// nowhere", rather than the instances.
    #[test]
    fn the_committed_docs_page_matches_the_generated_one() {
        let path = repo_root_path().join("docs/src/reference/cli-flags.md");
        let committed = std::fs::read_to_string(&path).expect("the flag reference is committed");
        assert_eq!(
            committed,
            render(&crate::args::Cli::command()),
            "{} is stale — regenerate it with `boot2deb cli-reference --markdown`",
            path.display()
        );
    }

    /// Every flag carries a description, because the generated table is only worth
    /// having if its rows say something. A `#[arg]` with no `///` renders an empty
    /// cell, which this catches at the source rather than in review.
    #[test]
    fn every_flag_describes_itself() {
        fn check(cmd: &Command, path: &str) {
            for arg in cmd.get_arguments() {
                if matches!(arg.get_id().as_str(), "help" | "version") {
                    continue;
                }
                assert!(
                    !describe(arg).is_empty(),
                    "{path} '{}' has no doc comment",
                    arg.get_id()
                );
            }
            for sub in cmd.get_subcommands() {
                assert!(
                    sub.get_about().is_some(),
                    "subcommand '{}' has no doc comment",
                    sub.get_name()
                );
                check(sub, &format!("{path} {}", sub.get_name()));
            }
        }
        check(&crate::args::Cli::command(), "boot2deb");
    }

    #[test]
    fn a_help_paragraph_break_survives_as_a_separator() {
        // Two paragraphs run together would read as one contradictory sentence, and a
        // dropped one would lose the qualification the second paragraph usually is.
        assert_eq!(
            one_line("first para\nwrapped\n\nsecond para"),
            "first para wrapped — second para"
        );
        // A pipe in help text would end the table cell.
        assert_eq!(one_line("combined | split"), "combined \\| split");
    }
}
