//! Local apt repo — assembles the build's own `.deb`s into a small flat
//! apt repository the rootfs node installs from, so apt resolves our packages
//! together with their dependencies (against this repo plus the suite mirror).
//!
//! The build makes every artifact a `.deb` (kernel, u-boot, MPP/RGA, ffmpeg-rk);
//! dropping them behind a trusted `copy://` apt source lets the rootfs
//! install a package *list* — the substrate base set plus the selected features'
//! packages — and have apt pull each deb's transitive deps from the mirror
//! via the standard `apt-get install .../*.deb`.
//!
//! The flat `Packages` index is generated by `dpkg-scanpackages` and the `Release`
//! by `apt-ftparchive` — apt's own tools for the job. Generating the index
//! in pure Rust is a later purity item, paralleling the debrepo backend.

use crate::build;
use crate::error::EngineError;
use crate::event::Step;
use std::path::{Path, PathBuf};
use std::process::Command;

/// A flat local apt repository assembled from the build's `.deb`s.
pub struct LocalRepo {
    /// Absolute repo directory holding the `.deb`s + `Packages` + `Release`.
    dir: PathBuf,
}

impl LocalRepo {
    /// Assemble a flat apt repo at `dir` from `debs`, emitting progress to `step`.
    ///
    /// Links (or copies, across filesystems) each `.deb` into `dir`, then
    /// generates the `Packages` index (`dpkg-scanpackages`) and a `Release`
    /// (`apt-ftparchive`). Any prior contents of `dir` are removed, so the repo
    /// reflects exactly `debs`. `dir` should be absolute —
    /// [`source_line`](LocalRepo::source_line) embeds it in an apt `copy://` URI
    /// read inside the rootfs bootstrap namespace.
    pub fn assemble(dir: &Path, debs: &[PathBuf], step: &Step) -> Result<LocalRepo, EngineError> {
        let _ = std::fs::remove_dir_all(dir);
        std::fs::create_dir_all(dir).map_err(|s| EngineError::io(dir, s))?;
        for deb in debs {
            let name = deb.file_name().ok_or_else(|| EngineError::Io {
                path: deb.display().to_string(),
                source: std::io::Error::new(
                    std::io::ErrorKind::InvalidInput,
                    "deb path has no file name",
                ),
            })?;
            link_or_copy(deb, &dir.join(name))?;
        }
        step.log(format!(
            "assembling local apt repo from {} .deb(s) at {}",
            debs.len(),
            dir.display()
        ));

        // dpkg-scanpackages writes the index to stdout; the shell redirects it to
        // `Packages` (its own "wrote N entries" note still streams to the event
        // sink through build::run's stderr). --multiversion keeps every version.
        let mut scan = Command::new("sh");
        scan.arg("-c")
            .arg("dpkg-scanpackages --multiversion . > Packages")
            .current_dir(dir);
        build::run(scan, "dpkg-scanpackages", "generate Packages index", step)?;

        // Release carries the index checksums; `[trusted=yes]` on the source means
        // apt does not require it to be signed.
        let mut rel = Command::new("sh");
        rel.arg("-c")
            .arg("apt-ftparchive release . > Release")
            .current_dir(dir);
        build::run(rel, "apt-ftparchive", "generate Release", step)?;

        Ok(LocalRepo {
            dir: dir.to_path_buf(),
        })
    }

    /// The apt source line that makes this repo installable during the rootfs
    /// bootstrap: `deb [trusted=yes] copy:///<dir> ./`.
    ///
    /// `copy://` (not `file://`) so apt copies each `.deb` into the target as it
    /// installs — the repo is reachable at its host path from the bootstrap's user
    /// namespace, and copying leaves the installed rootfs self-contained.
    /// `[trusted=yes]` skips signature verification: this is a build-local,
    /// freshly generated repo, not a network mirror. Its contents are exactly the
    /// `.deb`s the caller passed — the CLI seeds them from the invocation's recorded
    /// artifact ledger, not an extension-only scan of the output dir, so an unsigned
    /// stray never rides in on the blanket trust.
    pub fn source_line(&self) -> String {
        format!("deb [trusted=yes] copy://{} ./", self.dir.display())
    }

    /// The repo directory.
    pub fn dir(&self) -> &Path {
        &self.dir
    }
}

/// Hard-link `src` to `dst`, falling back to a copy across filesystems.
fn link_or_copy(src: &Path, dst: &Path) -> Result<(), EngineError> {
    let _ = std::fs::remove_file(dst);
    match std::fs::hard_link(src, dst) {
        Ok(()) => Ok(()),
        Err(_) => std::fs::copy(src, dst)
            .map(|_| ())
            .map_err(|s| EngineError::io(dst, s)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// True when a host tool is runnable — the repo path shells out to apt/dpkg
    /// tooling, so tests that need it skip cleanly where it is absent.
    fn have(tool: &str) -> bool {
        Command::new(tool)
            .arg("--version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    }

    /// Build a minimal `.deb` (`<pkg>_<version>_arm64.deb`) under `dir` via
    /// `dpkg-deb --build`, returning its path.
    fn make_deb(dir: &Path, pkg: &str, version: &str) -> PathBuf {
        let tree = dir.join(format!("{pkg}-tree"));
        std::fs::create_dir_all(tree.join("DEBIAN")).unwrap();
        std::fs::write(
            tree.join("DEBIAN/control"),
            format!(
                "Package: {pkg}\nVersion: {version}\nArchitecture: arm64\n\
                 Maintainer: test <t@example.invalid>\nDescription: test package\n"
            ),
        )
        .unwrap();
        let out = dir.join(format!("{pkg}_{version}_arm64.deb"));
        let status = Command::new("dpkg-deb")
            .args(["--build", "--nocheck"])
            .arg(&tree)
            .arg(&out)
            .status()
            .unwrap();
        assert!(status.success(), "dpkg-deb --build failed");
        out
    }

    #[test]
    fn source_line_is_trusted_flat_copy_uri() {
        let repo = LocalRepo {
            dir: PathBuf::from("/x/repo"),
        };
        assert_eq!(repo.source_line(), "deb [trusted=yes] copy:///x/repo ./");
    }

    #[test]
    fn assemble_indexes_every_deb() {
        if !have("dpkg-deb") || !have("dpkg-scanpackages") || !have("apt-ftparchive") {
            eprintln!("skipping assemble_indexes_every_deb: apt/dpkg tooling unavailable");
            return;
        }
        let tmp = tempfile::tempdir().unwrap();
        let a = make_deb(tmp.path(), "librockchip-mpp1", "1.5.0-1");
        let b = make_deb(tmp.path(), "ffmpeg-rk", "3e53143");
        let repo_dir = tmp.path().join("localrepo");
        let sink = |_: crate::event::Event| {};
        let step = Step::start(&sink, "repo");

        let repo = LocalRepo::assemble(&repo_dir, &[a, b], &step).unwrap();

        // Both debs are present in the repo dir.
        assert!(repo_dir.join("librockchip-mpp1_1.5.0-1_arm64.deb").exists());
        assert!(repo_dir.join("ffmpeg-rk_3e53143_arm64.deb").exists());
        // Packages indexes both, with relative Filename entries apt can resolve.
        let packages = std::fs::read_to_string(repo_dir.join("Packages")).unwrap();
        assert!(packages.contains("Package: librockchip-mpp1"));
        assert!(packages.contains("Package: ffmpeg-rk"));
        assert!(packages.contains("Filename: ./ffmpeg-rk_3e53143_arm64.deb"));
        // Release exists and checksums the index.
        let release = std::fs::read_to_string(repo_dir.join("Release")).unwrap();
        assert!(release.contains("SHA256:"));
        assert!(repo.dir().join("Release").exists());
    }
}
