//! Local apt repo — assembles the build's own `.deb`s into a small apt
//! repository the rootfs node installs from, so apt (or ferroday-cage's
//! provisioner) resolves our packages together with their dependencies (against
//! this repo plus the suite mirror).
//!
//! The build makes every artifact a `.deb` (kernel, u-boot, MPP/RGA, ffmpeg-rk);
//! dropping them behind a trusted apt source lets the rootfs install a package
//! *list* — the substrate base set plus the selected features' packages — and
//! have the solver pull each deb's transitive deps from the mirror.
//!
//! Two shapes, one per rootfs backend:
//!
//!  - **Flat** ([`LocalRepo`]) — a `deb [trusted=yes] copy://…` source the
//!    `mmdebstrap` backend ([`crate::rootfs::MmdebstrapRootfs`]) installs from.
//!  - **`dists/`-structured** ([`LocalDistsRepo`]) — a trusted `file://` mirror
//!    the ferroday-cage provisioner backend reads, which speaks only the standard
//!    `dists/<suite>/…/Release` + `Packages` mirror layout, not a flat repo.
//!
//! The `Packages` index is generated by `dpkg-scanpackages` and the `Release` by
//! `apt-ftparchive` — apt's own tools for the job. Generating the index in pure
//! Rust is a later purity item.

use crate::build;
use crate::error::EngineError;
use crate::event::Step;
use std::path::{Path, PathBuf};
use std::process::Command;

/// A flat local apt repository assembled from the build's `.deb`s.
pub struct LocalRepo {
    /// Absolute repo directory holding the `.deb`s + `Packages` + `Release`.
    dir: PathBuf,
}

impl LocalRepo {
    /// Assemble a flat apt repo at `dir` from `debs`, emitting progress to `step`.
    ///
    /// Links (or copies, across filesystems) each `.deb` into `dir`, then
    /// generates the `Packages` index (`dpkg-scanpackages`) and a `Release`
    /// (`apt-ftparchive`). Any prior contents of `dir` are removed, so the repo
    /// reflects exactly `debs`. `dir` should be absolute —
    /// [`source_line`](LocalRepo::source_line) embeds it in an apt `copy://` URI
    /// read inside the rootfs bootstrap namespace.
    pub fn assemble(dir: &Path, debs: &[PathBuf], step: &Step) -> Result<LocalRepo, EngineError> {
        let _ = std::fs::remove_dir_all(dir);
        std::fs::create_dir_all(dir).map_err(|s| EngineError::io(dir, s))?;
        for deb in debs {
            let name = deb.file_name().ok_or_else(|| EngineError::Io {
                path: deb.display().to_string(),
                source: std::io::Error::new(
                    std::io::ErrorKind::InvalidInput,
                    "deb path has no file name",
                ),
            })?;
            link_or_copy(deb, &dir.join(name))?;
        }
        step.log(format!(
            "assembling local apt repo from {} .deb(s) at {}",
            debs.len(),
            dir.display()
        ));

        // dpkg-scanpackages writes the index to stdout; the shell redirects it to
        // `Packages` (its own "wrote N entries" note still streams to the event
        // sink through build::run's stderr). --multiversion keeps every version.
        let mut scan = Command::new("sh");
        scan.arg("-c")
            .arg("dpkg-scanpackages --multiversion . > Packages")
            .current_dir(dir);
        build::run(scan, "dpkg-scanpackages", "generate Packages index", step)?;

        // Release carries the index checksums; `[trusted=yes]` on the source means
        // apt does not require it to be signed.
        let mut rel = Command::new("sh");
        rel.arg("-c")
            .arg("apt-ftparchive release . > Release")
            .current_dir(dir);
        build::run(rel, "apt-ftparchive", "generate Release", step)?;

        Ok(LocalRepo {
            dir: dir.to_path_buf(),
        })
    }

    /// The apt source line that makes this repo installable during the rootfs
    /// bootstrap: `deb [trusted=yes] copy:///<dir> ./`.
    ///
    /// `copy://` (not `file://`) so apt copies each `.deb` into the target as it
    /// installs — the repo is reachable at its host path from the bootstrap's user
    /// namespace, and copying leaves the installed rootfs self-contained.
    /// `[trusted=yes]` skips signature verification: this is a build-local,
    /// freshly generated repo, not a network mirror. Its contents are exactly the
    /// `.deb`s the caller passed — the CLI seeds them from the invocation's recorded
    /// artifact ledger, not an extension-only scan of the output dir, so an unsigned
    /// stray never rides in on the blanket trust.
    pub fn source_line(&self) -> String {
        format!("deb [trusted=yes] copy://{} ./", self.dir.display())
    }

    /// The repo directory.
    pub fn dir(&self) -> &Path {
        &self.dir
    }
}

/// A `dists/`-structured trusted local apt repository — the shape the
/// ferroday-cage provisioner backend reads.
///
/// The provisioner speaks only the standard mirror layout: a
/// `dists/<suite>/Release` indexing a per-component `Packages` file, whose
/// packages carry a pool-relative `Filename`. So the build's own `.deb`s reach
/// the provisioner's resolution as one more `file://` mirror, trusted without a
/// signature (apt's `[trusted=yes]` / ferroday's `trust_unsigned`). The layout:
///
/// ```text
/// <dir>/pool/main/<pkg>_<ver>_<arch>.deb
/// <dir>/dists/<suite>/main/binary-<arch>/Packages
/// <dir>/dists/<suite>/Release
/// ```
///
/// The debs are the build's own freshly-generated output, so trusting the repo
/// unsigned is apt's own `file://` `[trusted=yes]` case — the provisioner refuses
/// `trust_unsigned` only over `http://`, never a local path.
pub struct LocalDistsRepo {
    /// Absolute repo root — the `file://` mirror URL base the provisioner fetches
    /// `dists/<suite>/…` and `pool/…` under.
    dir: PathBuf,
}

impl LocalDistsRepo {
    /// Assemble a `dists/`-structured trusted repo at `dir` from `debs` for
    /// `suite`/`arch`, emitting progress to `step`.
    ///
    /// Links (or copies, across filesystems) each `.deb` into `pool/main/`, then
    /// generates the component `Packages` index (`dpkg-scanpackages`, with
    /// pool-relative `Filename`s the provisioner resolves against the `file://`
    /// base) and a `Release` (`apt-ftparchive`, stamped with the suite, the `main`
    /// component, and `<arch>` so the provisioner's release check accepts it —
    /// `trust_unsigned` skips the signature and the freshness bound, so no
    /// `Valid-Until` is needed). Any prior contents of `dir` are removed, so the
    /// repo reflects exactly `debs`. `dir` should be absolute.
    pub fn assemble(
        dir: &Path,
        debs: &[PathBuf],
        suite: &str,
        arch: &str,
        step: &Step,
    ) -> Result<LocalDistsRepo, EngineError> {
        let _ = std::fs::remove_dir_all(dir);
        let pool = dir.join("pool/main");
        std::fs::create_dir_all(&pool).map_err(|s| EngineError::io(&pool, s))?;
        for deb in debs {
            let name = deb.file_name().ok_or_else(|| EngineError::Io {
                path: deb.display().to_string(),
                source: std::io::Error::new(
                    std::io::ErrorKind::InvalidInput,
                    "deb path has no file name",
                ),
            })?;
            link_or_copy(deb, &pool.join(name))?;
        }
        let binary_rel = format!("dists/{suite}/main/binary-{arch}");
        std::fs::create_dir_all(dir.join(&binary_rel)).map_err(|s| EngineError::io(dir, s))?;
        step.log(format!(
            "assembling dists/ local apt repo from {} .deb(s) at {} ({suite}/{arch})",
            debs.len(),
            dir.display()
        ));

        // dpkg-scanpackages names each Filename relative to its invocation dir; run
        // it from the repo root over `pool/main`, so Filename is `pool/main/<deb>` —
        // pool-relative to the `file://` mirror base, which is how the provisioner
        // resolves each package's bytes. --multiversion keeps every version.
        let mut scan = Command::new("sh");
        scan.arg("-c")
            .arg(format!(
                "dpkg-scanpackages --multiversion pool/main > {binary_rel}/Packages"
            ))
            .current_dir(dir);
        build::run(scan, "dpkg-scanpackages", "generate dists Packages index", step)?;

        // apt-ftparchive release checksums the Packages under dists/<suite>/ and, via
        // the -o overrides, stamps the Suite/Codename/Components/Architectures the
        // provisioner's release check requires. Run from within dists/<suite> so the
        // checksum paths are component-relative, as a mirror's are. suite/arch are
        // resolved, validated identifiers, safe to embed in the sourced command.
        let rel_cmd = format!(
            "apt-ftparchive \
             -o APT::FTPArchive::Release::Suite={suite} \
             -o APT::FTPArchive::Release::Codename={suite} \
             -o APT::FTPArchive::Release::Components=main \
             -o APT::FTPArchive::Release::Architectures={arch} \
             -o APT::FTPArchive::Release::Origin=boot2deb-local \
             -o APT::FTPArchive::Release::Label=boot2deb-local \
             release . > Release"
        );
        let mut rel = Command::new("sh");
        rel.arg("-c").arg(&rel_cmd).current_dir(dir.join(format!("dists/{suite}")));
        build::run(rel, "apt-ftparchive", "generate dists Release", step)?;

        Ok(LocalDistsRepo {
            dir: dir.to_path_buf(),
        })
    }

    /// The `file://` mirror URL for this repo — the base the provisioner fetches
    /// `dists/<suite>/…` and each package's pool `Filename` under. Built for a
    /// [`ferroday_cage`](crate::sandbox) `Repository::builder(...).mirror(...)`.
    pub fn file_url(&self) -> String {
        format!("file://{}", self.dir.display())
    }

    /// The repo directory.
    pub fn dir(&self) -> &Path {
        &self.dir
    }
}

/// Hard-link `src` to `dst`, falling back to a copy across filesystems.
fn link_or_copy(src: &Path, dst: &Path) -> Result<(), EngineError> {
    let _ = std::fs::remove_file(dst);
    match std::fs::hard_link(src, dst) {
        Ok(()) => Ok(()),
        Err(_) => std::fs::copy(src, dst)
            .map(|_| ())
            .map_err(|s| EngineError::io(dst, s)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// True when a host tool is runnable — the repo path shells out to apt/dpkg
    /// tooling, so tests that need it skip cleanly where it is absent.
    fn have(tool: &str) -> bool {
        Command::new(tool)
            .arg("--version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    }

    /// Build a minimal `.deb` (`<pkg>_<version>_arm64.deb`) under `dir` via
    /// `dpkg-deb --build`, returning its path.
    fn make_deb(dir: &Path, pkg: &str, version: &str) -> PathBuf {
        let tree = dir.join(format!("{pkg}-tree"));
        std::fs::create_dir_all(tree.join("DEBIAN")).unwrap();
        std::fs::write(
            tree.join("DEBIAN/control"),
            format!(
                "Package: {pkg}\nVersion: {version}\nArchitecture: arm64\n\
                 Maintainer: test <t@example.invalid>\nDescription: test package\n"
            ),
        )
        .unwrap();
        let out = dir.join(format!("{pkg}_{version}_arm64.deb"));
        let status = Command::new("dpkg-deb")
            .args(["--build", "--nocheck"])
            .arg(&tree)
            .arg(&out)
            .status()
            .unwrap();
        assert!(status.success(), "dpkg-deb --build failed");
        out
    }

    #[test]
    fn source_line_is_trusted_flat_copy_uri() {
        let repo = LocalRepo {
            dir: PathBuf::from("/x/repo"),
        };
        assert_eq!(repo.source_line(), "deb [trusted=yes] copy:///x/repo ./");
    }

    #[test]
    fn assemble_indexes_every_deb() {
        if !have("dpkg-deb") || !have("dpkg-scanpackages") || !have("apt-ftparchive") {
            eprintln!("skipping assemble_indexes_every_deb: apt/dpkg tooling unavailable");
            return;
        }
        let tmp = tempfile::tempdir().unwrap();
        let a = make_deb(tmp.path(), "librockchip-mpp1", "1.5.0-1");
        let b = make_deb(tmp.path(), "ffmpeg-rk", "3e53143");
        let repo_dir = tmp.path().join("localrepo");
        let sink = |_: crate::event::Event| {};
        let step = Step::start(&sink, "repo");

        let repo = LocalRepo::assemble(&repo_dir, &[a, b], &step).unwrap();

        // Both debs are present in the repo dir.
        assert!(repo_dir.join("librockchip-mpp1_1.5.0-1_arm64.deb").exists());
        assert!(repo_dir.join("ffmpeg-rk_3e53143_arm64.deb").exists());
        // Packages indexes both, with relative Filename entries apt can resolve.
        let packages = std::fs::read_to_string(repo_dir.join("Packages")).unwrap();
        assert!(packages.contains("Package: librockchip-mpp1"));
        assert!(packages.contains("Package: ffmpeg-rk"));
        assert!(packages.contains("Filename: ./ffmpeg-rk_3e53143_arm64.deb"));
        // Release exists and checksums the index.
        let release = std::fs::read_to_string(repo_dir.join("Release")).unwrap();
        assert!(release.contains("SHA256:"));
        assert!(repo.dir().join("Release").exists());
    }

    #[test]
    fn dists_repo_has_the_mirror_layout_the_provisioner_reads() {
        if !have("dpkg-deb") || !have("dpkg-scanpackages") || !have("apt-ftparchive") {
            eprintln!("skipping dists_repo_has_the_mirror_layout: apt/dpkg tooling unavailable");
            return;
        }
        let tmp = tempfile::tempdir().unwrap();
        let a = make_deb(tmp.path(), "librockchip-mpp1", "1.5.0-1");
        let b = make_deb(tmp.path(), "ffmpeg-rk", "3e53143");
        let repo_dir = tmp.path().join("localdists");
        let sink = |_: crate::event::Event| {};
        let step = Step::start(&sink, "repo");

        let repo =
            LocalDistsRepo::assemble(&repo_dir, &[a, b], "forky", "arm64", &step).unwrap();

        // The debs live in the pool, and the file:// URL bases at the repo root.
        assert!(repo_dir.join("pool/main/librockchip-mpp1_1.5.0-1_arm64.deb").exists());
        assert!(repo_dir.join("pool/main/ffmpeg-rk_3e53143_arm64.deb").exists());
        assert_eq!(repo.file_url(), format!("file://{}", repo_dir.display()));

        // The Packages index sits at the standard dists path, and each Filename is
        // pool-relative to the mirror base (how the provisioner resolves the bytes).
        let packages =
            std::fs::read_to_string(repo_dir.join("dists/forky/main/binary-arm64/Packages"))
                .unwrap();
        assert!(packages.contains("Package: ffmpeg-rk"));
        assert!(packages.contains("Filename: pool/main/ffmpeg-rk_3e53143_arm64.deb"));

        // The Release declares the suite, component, and architecture the
        // provisioner's release check requires, and checksums the index.
        let release = std::fs::read_to_string(repo_dir.join("dists/forky/Release")).unwrap();
        assert!(release.contains("Suite: forky"));
        assert!(release.contains("Codename: forky"));
        assert!(release.contains("Components: main"));
        assert!(release.contains("Architectures: arm64"));
        assert!(release.contains("SHA256:"));
        assert!(release.contains("main/binary-arm64/Packages"));
    }
}
