//! Rootfs node — bootstraps the device's Debian userland and emits the
//! `tar` archive the [image node](crate::image) formats into ext4, plus a
//! content-pinned solved package manifest.
//!
//! One `mmdebstrap --mode=unshare` invocation does the whole job, rootless (no
//! `sudo`, no persistent chroot): it installs the merged rootfs package set
//! ([`ResolvedBuild::rootfs_packages`]) from the build's own [`LocalRepo`]
//! plus the suite mirror — so apt resolves each `.deb`'s dependencies — and a
//! `--customize-hook` lays the staged overlay in, runs the target-chroot
//! config (user account, ssh first-boot, group membership), and re-runs the
//! kernel `postinst.d` hooks so `/boot` gains the initrd, board dtb, and
//! `extlinux.conf` u-boot loads (the kernel configured before the overlay's
//! hooks existed, so its own postinst produced none of them). The overlay is the
//! layered substrate merged in Rust beforehand: each layer's `overlay/` tree
//! followed by the *generated* config this module produces from the
//! resolved values (fstab, hostname, apt sources, locale, machine-id).
//!
//! This is the `mmdebstrap` backend behind the [`Rootfs`] trait; a `debrepo`
//! backend (native content-pinned manifest) slots in behind the same trait
//! later.
//!
//! The manifest is fully content-pinned — `name + version + arch + sha256` per
//! package. The sha256 is the hash of the exact `.deb` installed: the bootstrap
//! keeps every fetched `.deb` in the apt cache through the customize stage
//! (`--skip=essential/unlink` plus `APT::Keep-Downloaded-Packages`), a hook
//! hashes them there, and the manifest writer joins those hashes onto the
//! installed set from dpkg status. mmdebstrap's own cleanup still empties the
//! cache afterward, so the tarball stays lean.
//!
//! Board firmware (rockchip display, panthor Mali, Realtek NIC) is staged as
//! Debian `non-free-firmware` packages declared on the SoC layer (for RK3588:
//! `firmware-misc-nonfree` + `firmware-realtek` in `socs/rk3588.toml`), not
//! extracted from a linux-firmware tarball — so it is snapshot-pinned like every
//! other package and needs no separate fetch step.

use crate::bootstrap::{StagingRoot, COMPONENTS};
use crate::error::EngineError;
use crate::event::{EventSink, Step};
use crate::repo::LocalRepo;
use crate::rootcache::{self, RootfsStore};
use boot2deb_core::model::{AptSource, ResolvedBuild};
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::process::Command;

/// The default appliance account. Its first-boot password is **unique per built
/// image** — generated by [`crate::secret::generate_password`] and expired at
/// build time (`passwd -e`), so it must be changed at first login and no
/// guessable credential is ever on the network (SEC-6). Membership in
/// `video`/`render` is what the HW-accel udev rules grant device access through.
pub const DEFAULT_USER: &str = "debian";

/// Filesystem inputs for the rootfs node.
pub struct RootfsOptions<'a> {
    /// The build's `.deb`s (kernel, u-boot, MPP/RGA, ffmpeg-rk, …) — assembled
    /// into a [`LocalRepo`] the bootstrap installs the accel packages from.
    pub repo_debs: &'a [PathBuf],
    /// Layer `overlay/` directories to lay into the rootfs, in merge order
    /// (base → soc → boot-method → device → features). Non-existent entries
    /// are skipped; later entries win.
    pub overlay_dirs: &'a [PathBuf],
    /// Directory the rootfs tarball is written to.
    pub out_dir: &'a Path,
    /// Debian archive keyring verifying the suite's `Release` (as the sandbox);
    /// `None` uses the host apt trust store (Debian host only).
    pub keyring: Option<&'a Path>,
    /// Where the solved package manifest is written (the lock's `[rootfs].manifest`
    /// points at it).
    pub manifest_out: &'a Path,
    /// Ordered Debian mirror list the bootstrap fetches from — the live mirror,
    /// plus a `snapshot.debian.org` mirror when a captured snapshot is activated
    /// (resolved by [`crate::snapshot::resolve_mirrors`]). Must be non-empty;
    /// apt tries them in order, so a `fallback` snapshot backfills the first
    /// mirror's 404s from the second.
    pub mirrors: &'a [String],
    /// Extra package names to install beyond [`ResolvedBuild::rootfs_packages`] —
    /// build artifacts whose names are version-specific and thus unknowable to the
    /// static config, above all the freshly built kernel image.
    pub extra_packages: &'a [String],
    /// The ext4 volume label the image node will assign the rootfs partition. The
    /// generated `/etc/fstab` mounts root by this label, so it must be the same
    /// value the image node passes to mkfs — one resolved label threaded through
    /// both nodes, else the root mount fails on-device.
    pub rootfs_label: &'a str,
    /// Root of the content-addressed rootfs cache. `Some(dir)` enables the
    /// early-cutoff cache: a cheap `mmdebstrap --simulate` solve keys a store under
    /// `<dir>/rootfs/`, and an unchanged solved set restores a stored tree instead
    /// of re-bootstrapping ([`crate::rootcache`]). `None` always bootstraps.
    pub cache_dir: Option<&'a Path>,
    /// Ignore a cache hit and re-bootstrap, refreshing the stored entry
    /// (`--refresh-rootfs`). The solve still runs and the fresh tree is re-stored.
    pub refresh: bool,
    /// Third-party apt repositories the selected features contribute
    /// ([`ResolvedBuild::apt_sources`], CFG-1), each paired with the host
    /// path its `signed_by` keyring resolved to. Rendered into signed `deb` positionals
    /// so apt resolves an out-of-mirror app (e.g. Jellyfin) during the bootstrap solve.
    /// Empty when no feature adds one.
    pub apt_sources: &'a [AptRepo<'a>],
    /// Deterministic build timestamp (`SOURCE_DATE_EPOCH`, the locked kernel commit's
    /// committer date — the same lock-derived seed the image identifiers use), or
    /// `None` when the kernel tree is not available to read it (a partial rootfs-only
    /// build). When set it is exported into the mmdebstrap environment so the tarball's
    /// member mtimes are clamped to it, and stamped onto the password-splice's appended
    /// `./etc/shadow` member, so only the deliberate per-image secret (SEC-6,
    /// DET-1) — not incidental build-time mtimes — varies between builds of one lock
    /// (DET-2/DET-4).
    pub source_date_epoch: Option<u64>,
}

/// A resolved third-party apt repository activated during the rootfs bootstrap solve
/// (CFG-1): a feature's [`AptSource`] paired with the host path its `signed_by`
/// keyring resolved to. The CLI resolves and existence-checks the keyring (a vendored
/// build-host prerequisite); the rootfs stage renders the pair into an
/// mmdebstrap positional `deb [signed-by=…]` line so the repo's `Release` signature is
/// verified during the solve rather than trusted blindly.
pub struct AptRepo<'a> {
    /// The resolved feature source (uri / suite / components / name / signed_by).
    pub source: &'a AptSource,
    /// Host path the source's `signed_by` keyring resolved to (CLI-verified to exist).
    pub keyring: PathBuf,
}

/// What [`Rootfs::build`] produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RootfsArtifacts {
    /// The rootfs `tar` archive (device nodes excluded), consumed by the image
    /// node's ext4 formatter. [`DEFAULT_USER`]'s account is **locked** in it — the
    /// unique per-image first-boot password (SEC-6) is spliced into the staged tree
    /// at image assembly, not into this shared, cacheable tarball.
    pub tar: PathBuf,
    /// The solved package manifest (`name version arch sha256` per line).
    pub manifest: PathBuf,
}

/// A rootfs backend: bootstraps the device userland to a tarball plus a
/// content-pinned manifest. Implemented by [`MmdebstrapRootfs`]; a `debrepo`
/// backend slots in behind this trait later.
pub trait Rootfs {
    /// Bootstrap `build`'s rootfs per `opts`, emitting the step's
    /// [`Event`](crate::event::Event)s to `sink`.
    fn build(
        &self,
        build: &ResolvedBuild,
        opts: &RootfsOptions,
        sink: &dyn EventSink,
    ) -> Result<RootfsArtifacts, EngineError>;
}

/// The `mmdebstrap` rootfs backend — rootless bootstrap in one invocation.
pub struct MmdebstrapRootfs;

impl Rootfs for MmdebstrapRootfs {
    fn build(
        &self,
        build: &ResolvedBuild,
        opts: &RootfsOptions,
        sink: &dyn EventSink,
    ) -> Result<RootfsArtifacts, EngineError> {
        let step = Step::start(sink, "rootfs");
        std::fs::create_dir_all(opts.out_dir).map_err(|s| EngineError::io(opts.out_dir, s))?;

        // Everything `mmdebstrap --mode=unshare` reads under an unprivileged mapped
        // uid — the local apt repo and keyring (apt's acquire phase) and the
        // customize-hook script plus the overlay tree it copies from (the hook runs
        // under a mapped uid too) — must sit on a world-traversable path: those uids
        // cannot traverse a build dir under a `0750` home. All of it stages under the
        // system temp dir; removed when `staging` drops.
        let staging = BootstrapStaging::new()?;

        // 1. The build's debs → a trusted local apt repo.
        let repo = LocalRepo::assemble(&staging.repo_dir(), opts.repo_debs, &step)?;
        let keyring = opts.keyring.map(|kr| staging.stage_keyring(kr)).transpose()?;

        // 2. Merge the layer overlays + write the generated config into a staged
        //    tree the customize-hook copies into the rootfs after install.
        let overlay = staging.overlay_dir();
        stage_overlay(&overlay, opts.overlay_dirs, build, opts.rootfs_label, &step)?;

        // 3. The customize-hooks: (a) capture each fetched `.deb`'s sha256 while the
        //    apt cache is still populated, then (b) lay the overlay in and run the
        //    chroot config. The account is created **locked** here — the unique
        //    per-image password (SEC-6) is non-reproducible, so it is *not*
        //    baked into the cacheable tree; it is spliced into the staged tree at
        //    image assembly, keeping a stored tree reusable across builds.
        let deb_hashes = staging.deb_hashes_path();
        let hash_hook = staging.hash_hook_path();
        std::fs::write(&hash_hook, capture_hashes_hook_script(&deb_hashes))
            .map_err(|s| EngineError::io(&hash_hook, s))?;
        let hook = staging.hook_path();
        std::fs::write(&hook, customize_hook_script(&overlay, DEFAULT_USER))
            .map_err(|s| EngineError::io(&hook, s))?;

        let repo_source = repo.source_line();
        let tarball = opts.out_dir.join(format!("{}-rootfs.tar", build.device));

        // 4. Early-cutoff cache: a cheap `mmdebstrap --simulate` solve learns
        //    the versions the current mirror resolves and keys a store of
        //    password-free rootfs trees. A hit skips the ~250 s bootstrap; because the
        //    key is the *solved* set (not the input names), a moved mirror resolves a
        //    different key and rebuilds — a hit is never stale. A solve failure just
        //    disables the cache for this run (fail-safe: a spurious miss only wastes
        //    time), so the bootstrap still surfaces any real error.
        let cache = match opts.cache_dir {
            Some(dir) => match solve_key(build, opts, keyring.as_deref(), &repo_source, &overlay, &step) {
                Ok(key) => Some((RootfsStore::new(dir), key)),
                Err(e) => {
                    step.log(format!("rootfs cache disabled this run ({e})"));
                    None
                }
            },
            None => None,
        };
        let hit = match &cache {
            Some((store, key)) if !opts.refresh => store.get(key),
            _ => None,
        };

        // 5. Materialize the password-free tarball + its content-pinned manifest,
        //    from the cache or by bootstrapping.
        if let Some(hit) = hit {
            let key = &cache.as_ref().expect("hit implies a cache").1;
            step.log(format!(
                "rootfs cache hit {} — restoring, skipping bootstrap",
                key.short()
            ));
            std::fs::copy(&hit.tar, &tarball).map_err(|s| EngineError::io(&hit.tar, s))?;
            std::fs::copy(&hit.manifest, opts.manifest_out)
                .map_err(|s| EngineError::io(&hit.manifest, s))?;
            step.progress(75);
        } else {
            step.progress(20);
            step.log(format!(
                "bootstrapping {} {} rootfs ({} packages, {} mirror(s)) at {}",
                build.arch,
                build.suite,
                build.rootfs_packages.len(),
                opts.mirrors.len(),
                tarball.display()
            ));
            let mut cmd = Command::new("mmdebstrap");
            cmd.args(mmdebstrap_argv(
                build,
                opts,
                keyring.as_deref(),
                &repo_source,
                &tarball,
                &hook,
                &hash_hook,
            ));
            // Clamp every tar member mtime to the lock-derived epoch so build-time
            // mtimes do not leak into the tarball (DET-4). mmdebstrap reduces any mtime
            // newer than SOURCE_DATE_EPOCH down to it; the generated config and the
            // overlay (hook-copied without preserving timestamps) are stamped "now", so
            // they all clamp to the epoch, while pinned package files keep their fixed
            // (older) mtimes. The solve above needs no epoch — it builds no tar.
            if let Some(epoch) = opts.source_date_epoch {
                cmd.env("SOURCE_DATE_EPOCH", epoch.to_string());
            }
            crate::build::run(cmd, "mmdebstrap", "bootstrap rootfs", &step)?;
            step.progress(70);
            // Reconstruct the solved manifest from the rootfs's dpkg status,
            // content-pinned with the per-`.deb` sha256s the hook captured.
            let hashes = read_deb_hashes(&deb_hashes)?;
            write_manifest(&tarball, opts.manifest_out, &hashes, &step)?;
            // Store the password-free tree + manifest for next time.
            if let Some((store, key)) = &cache {
                store.put(key, &tarball, opts.manifest_out, &step)?;
            }
            step.progress(75);
        }

        // The account stays locked in this shared, cacheable tarball. The unique
        // per-image first-boot password (SEC-6) is spliced into the staged tree at
        // image assembly (the image node's ext4 stage), not into the tar — so a
        // stored tree is reusable across builds and no fragile in-archive member
        // surgery on the (PAX) tarball is needed.
        step.progress(100);
        step.finish();
        Ok(RootfsArtifacts {
            tar: tarball,
            manifest: opts.manifest_out.to_path_buf(),
        })
    }
}

/// The `--include` argument shared by the real bootstrap and the `--simulate` solve:
/// the merged rootfs package set plus the build's `extra_packages`, with the base
/// excludes riding along as apt deselections (`pkgname-`) since mmdebstrap has no
/// `--exclude` flag (that is a debootstrap-ism). `None` when nothing is included.
fn include_arg(build: &ResolvedBuild, opts: &RootfsOptions) -> Option<String> {
    let mut includes = build.rootfs_packages.clone();
    includes.extend(opts.extra_packages.iter().cloned());
    includes.extend(build.rootfs_exclude.iter().map(|p| format!("{p}-")));
    (!includes.is_empty()).then(|| format!("--include={}", includes.join(",")))
}

/// Render a resolved feature apt repository as an mmdebstrap positional
/// `deb [signed-by=<keyring>] <uri> <suite> <components…>` line (CFG-1). The
/// `signed-by` points at the host keyring path the source's `signed_by` resolved to,
/// so apt verifies the repo's `Release` signature during the solve rather than
/// trusting it blindly — unlike the local repo's `[trusted=yes]`, which is our own
/// freshly-built output. Pure, so the line format is unit-testable.
fn apt_source_line(repo: &AptRepo) -> String {
    format!(
        "deb [signed-by={}] {} {} {}",
        repo.keyring.display(),
        repo.source.uri,
        repo.source.suite,
        repo.source.components.join(" ")
    )
}

/// `mmdebstrap --simulate` argv for the early-cutoff solve. Mirrors
/// [`mmdebstrap_argv`]'s package selection, mirrors, and local repo, but adds
/// `--simulate --verbose` (run apt's solver, print the resolved set, install
/// nothing) and drops the hooks and cache-retention flags — no rootfs is built, so
/// the target is `/dev/null`. Pure, so the invocation is unit-testable.
fn simulate_argv(
    build: &ResolvedBuild,
    opts: &RootfsOptions,
    keyring: Option<&Path>,
    repo_source: &str,
) -> Vec<String> {
    let mut argv = vec![
        "--mode=unshare".to_string(),
        format!("--arch={}", build.arch.debian_arch()),
        "--variant=important".to_string(),
        format!("--components={COMPONENTS}"),
        "--simulate".to_string(),
        "--verbose".to_string(),
    ];
    // Bound apt's per-connection network wait so a stalled mirror fails rather than
    // hangs (TRUST-5).
    argv.extend(crate::bootstrap::APT_TIMEOUT_OPTS.iter().map(|s| s.to_string()));
    if let Some(kr) = keyring {
        argv.push(format!("--keyring={}", kr.display()));
    }
    if let Some(include) = include_arg(build, opts) {
        argv.push(include);
    }
    // `--` stops option parsing so the positional suite/target/mirrors cannot be
    // read as options even if a value begins with `-` (SUB-2; mmdebstrap documents
    // this terminator explicitly).
    argv.push("--".to_string());
    argv.push(build.suite.clone());
    argv.push("/dev/null".to_string());
    argv.extend(opts.mirrors.iter().cloned());
    // Third-party feature repos (signed), so an out-of-mirror app resolves in the
    // solve; the local repo (our own built debs) stays last (CFG-1).
    argv.extend(opts.apt_sources.iter().map(apt_source_line));
    argv.push(repo_source.to_string());
    argv
}

/// Run the cheap `--simulate` solve and fold its result into the rootfs cache key:
/// the solved package set (from [`simulate_argv`]) plus the assembled
/// overlay's content and the local-repo `.deb`s' content ([`rootcache::cache_key`]).
/// A non-zero exit or an empty solve is an error the caller downgrades to "cache
/// disabled this run" — fail-safe, since the real bootstrap then surfaces the cause.
fn solve_key(
    build: &ResolvedBuild,
    opts: &RootfsOptions,
    keyring: Option<&Path>,
    repo_source: &str,
    overlay: &Path,
    step: &Step,
) -> Result<crate::signature::Signature, EngineError> {
    step.log("solving package set (mmdebstrap --simulate) for the rootfs cache key");
    let out = Command::new("mmdebstrap")
        .args(simulate_argv(build, opts, keyring, repo_source))
        .output()
        .map_err(|source| EngineError::CommandSpawn {
            command: "mmdebstrap".into(),
            context: "simulate solve".into(),
            source,
        })?;
    if !out.status.success() {
        let s = String::from_utf8_lossy(&out.stderr);
        let lines: Vec<&str> = s.lines().collect();
        let tail = lines[lines.len().saturating_sub(10)..].join("\n");
        return Err(EngineError::CommandFailed {
            command: "mmdebstrap".into(),
            context: "simulate solve".into(),
            status: out.status.code(),
            stderr: tail,
        });
    }
    // apt's `Conf` lines land on stdout; combine with stderr defensively.
    let mut combined = String::from_utf8_lossy(&out.stdout).into_owned();
    combined.push_str(&String::from_utf8_lossy(&out.stderr));
    let solved = rootcache::parse_solved(&combined);
    if solved.is_empty() {
        return Err(EngineError::CommandFailed {
            command: "mmdebstrap".into(),
            context: "simulate solve".into(),
            status: out.status.code(),
            stderr: "solve produced no packages".into(),
        });
    }
    let overlay_fp = rootcache::dir_fingerprints(overlay)?;
    let repo_fp = rootcache::file_fingerprints(opts.repo_debs)?;
    let key = rootcache::cache_key(
        &solved,
        &overlay_fp,
        &repo_fp,
        &build.arch.to_string(),
        &build.suite,
    );
    step.log(format!(
        "solved {} packages; rootfs cache key {}",
        solved.len(),
        key.short()
    ));
    Ok(key)
}

/// `mmdebstrap` argv for the rootfs bootstrap. Pure, so the (long, easy-to-get-
/// wrong) invocation is unit-testable.
///
/// Emits a `--mode=unshare` bootstrap of the `important` variant (a full base
/// system, unlike the build sandbox's `minbase`) with the merged package set as
/// `--include`, and the positional mirrors: the resolved Debian mirror list
/// ([`RootfsOptions::mirrors`] — the live mirror, plus a snapshot mirror when
/// activated) followed by the local repo's `deb [trusted=yes] copy://…`
/// line, so apt resolves our accel `.deb`s and their mirror deps together. The
/// base excludes ride in the same `--include` list as apt deselections
/// (`pkgname-`) — mmdebstrap has no `--exclude` flag (that is a debootstrap-ism).
///
/// Two flags keep every fetched `.deb` in `/var/cache/apt/archives` through the
/// customize stage so `hash_hook` can content-pin them: `--skip=essential/
/// unlink` stops the essential stage from unlinking the base debs it just
/// installed, and `APT::Keep-Downloaded-Packages "true"` stops apt from deleting
/// the rest after install. mmdebstrap's own `cleanup` still empties the cache
/// afterward, so the tarball is unaffected. Two customize-hooks run after
/// install with the rootfs dir as `$1`: `hash_hook` first (hash the cache), then
/// `hook` (lay the overlay in, chroot config).
#[allow(clippy::too_many_arguments)]
fn mmdebstrap_argv(
    build: &ResolvedBuild,
    opts: &RootfsOptions,
    keyring: Option<&Path>,
    repo_source: &str,
    tarball: &Path,
    hook: &Path,
    hash_hook: &Path,
) -> Vec<String> {
    let mut argv = vec![
        "--mode=unshare".to_string(),
        format!("--arch={}", build.arch.debian_arch()),
        "--variant=important".to_string(),
        format!("--components={COMPONENTS}"),
        // Retain the fetched `.deb`s through the customize stage so the sha256
        // capture hook can hash them (both removals happen before that stage
        // otherwise): the essential stage's unlink, and apt's post-install delete.
        "--skip=essential/unlink".to_string(),
        "--aptopt=APT::Keep-Downloaded-Packages \"true\"".to_string(),
    ];
    // Bound apt's per-connection network wait so a stalled mirror fails rather than
    // hangs (TRUST-5).
    argv.extend(crate::bootstrap::APT_TIMEOUT_OPTS.iter().map(|s| s.to_string()));
    if let Some(kr) = keyring {
        argv.push(format!("--keyring={}", kr.display()));
    }
    if let Some(include) = include_arg(build, opts) {
        argv.push(include);
    }
    // mmdebstrap runs each hook via `sh -c '<value>' sh <rootfs>`, so "$1" is the
    // rootfs dir. The hash hook runs first (cache still populated), then the
    // config hook does the copy-in and chroot config.
    argv.push(format!("--customize-hook=sh {} \"$1\"", hash_hook.display()));
    argv.push(format!("--customize-hook=sh {} \"$1\"", hook.display()));
    // `--` stops option parsing so the positional suite/target/mirrors cannot be
    // read as options even if a value begins with `-` (SUB-2; mmdebstrap documents
    // this terminator explicitly).
    argv.push("--".to_string());
    argv.push(build.suite.clone());
    argv.push(tarball.to_string_lossy().into_owned());
    // The resolved mirror list (live, plus a snapshot mirror when activated), then
    // the local repo — apt tries them in order.
    argv.extend(opts.mirrors.iter().cloned());
    // Third-party feature repos (signed), so an out-of-mirror app resolves in the
    // solve; the local repo (our own built debs) stays last (CFG-1).
    argv.extend(opts.apt_sources.iter().map(apt_source_line));
    argv.push(repo_source.to_string());
    argv
}

/// Merge the layer `overlay/` trees into `staging` (each existing dir, in order,
/// via `cp -a` so symlinks + modes are preserved), then write the *generated*
/// config into it. Later layers and the generated config win.
fn stage_overlay(
    staging: &Path,
    overlay_dirs: &[PathBuf],
    build: &ResolvedBuild,
    rootfs_label: &str,
    step: &Step,
) -> Result<(), EngineError> {
    let _ = std::fs::remove_dir_all(staging);
    std::fs::create_dir_all(staging).map_err(|s| EngineError::io(staging, s))?;
    for dir in overlay_dirs {
        if dir.exists() {
            let mut cmd = Command::new("cp");
            cmd.arg("-a").arg(format!("{}/.", dir.display())).arg(staging);
            crate::build::run(cmd, "cp", &format!("stage overlay {}", dir.display()), step)?;
        }
    }
    // Generated config, mirroring rootfs paths.
    write_staged(staging, "etc/fstab", &config::fstab(rootfs_label))?;
    write_staged(staging, "etc/hostname", &config::hostname(&build.hostname))?;
    write_staged(staging, "etc/hosts", &config::hosts(&build.hostname))?;
    write_staged(staging, "etc/apt/sources.list", &config::apt_sources(&build.suite))?;
    write_staged(staging, "etc/default/locale", &config::locale())?;
    write_staged(staging, "etc/kernel-img.conf", &config::kernel_img_conf())?;
    // Board boot params the kernel postinst.d/postrm.d hooks + mk_extlinux source,
    // so the boot-method overlay scripts stay board-agnostic (driven by the
    // device's kernel_dtb) rather than hardcoding one board's dtb name.
    write_staged(
        staging,
        "etc/boot2deb/board.conf",
        &config::board_conf(&build.kernel_dtb),
    )?;
    // Empty machine-id → systemd regenerates it on first boot.
    write_staged(staging, "etc/machine-id", "")?;
    // The sudoers drop-in is written by the customize-hook directly into the chroot,
    // not staged here: at mode 0440 it would be unreadable to the hook's mapped uid
    // when it copies the overlay in.
    step.log(format!("staged overlay + generated config at {}", staging.display()));
    Ok(())
}

/// Write `content` to `staging/<rel>` at mode `0644`, creating parent dirs. The
/// explicit mode keeps generated `/etc` config reproducible regardless of the
/// build host's umask (a `002` umask would otherwise leave it group-writable).
fn write_staged(staging: &Path, rel: &str, content: &str) -> Result<(), EngineError> {
    let path = staging.join(rel);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|s| EngineError::io(parent, s))?;
    }
    std::fs::write(&path, content).map_err(|s| EngineError::io(&path, s))?;
    set_mode(&path, 0o644)
}

/// Set the unix mode of `path`.
fn set_mode(path: &Path, mode: u32) -> Result<(), EngineError> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(mode))
        .map_err(|s| EngineError::io(path, s))
}

/// World-traversable staging for the bootstrap's acquire-phase inputs.
///
/// `mmdebstrap --mode=unshare` runs apt's acquire methods under an unprivileged
/// mapped uid (apt's `_apt` sandbox user, which is *not* the invoking user), so it
/// cannot traverse a build dir under a `0750` home. The local repo apt installs
/// from (`copy://`) and the archive keyring it verifies the mirror with must
/// therefore live on a path that uid can traverse. This wraps a randomly-named,
/// private [`StagingRoot`] with its `1777` drop dir materialized for the
/// capture hook; the tree is removed when it drops.
struct BootstrapStaging {
    /// The randomly-named, `0o711` staging root (removed on drop).
    root: StagingRoot,
}

impl BootstrapStaging {
    /// Create a fresh staging root with its capture-hook drop dir ready.
    fn new() -> Result<Self, EngineError> {
        let root = StagingRoot::new("boot2deb-rootfs-")?;
        // The capture hook writes its results into the sticky drop dir.
        root.drop_dir()?;
        Ok(Self { root })
    }

    /// Where the local apt repo is assembled — inside the traversable staging dir.
    fn repo_dir(&self) -> PathBuf {
        self.root.join("localrepo")
    }

    /// Where the merged overlay tree is staged — inside the traversable staging dir,
    /// so the customize-hook's mapped uid can read it when it copies the tree in.
    fn overlay_dir(&self) -> PathBuf {
        self.root.join("overlay")
    }

    /// The customize-hook script path — inside the traversable staging dir, so the
    /// mapped uid running it can read the script.
    fn hook_path(&self) -> PathBuf {
        self.root.join("customize-hook.sh")
    }

    /// The sha256-capture hook script path — inside the traversable staging dir.
    fn hash_hook_path(&self) -> PathBuf {
        self.root.join("capture-hashes.sh")
    }

    /// Where the capture hook writes the `name version arch sha256` lines — inside
    /// the world-writable `drop` dir, the only place the in-namespace hook can
    /// create a file. The hook `chmod`s it `0644` so the host can read it back
    /// regardless of the namespace's umask.
    fn deb_hashes_path(&self) -> PathBuf {
        self.root.join("drop/deb-sha256sums")
    }

    /// Copy `keyring` into the staging dir world-readable and return its new path.
    fn stage_keyring(&self, keyring: &Path) -> Result<PathBuf, EngineError> {
        self.root.stage_file(keyring, "keyring.gpg")
    }
}

/// The `--customize-hook` script: lay the staged overlay into the rootfs, then run
/// the target-chroot config that can only happen after install (the account and its
/// group membership + sudoers, and clearing the ssh host keys so they regenerate on
/// first boot).
///
/// It finishes by re-running the kernel `postinst.d` hooks (`run-parts`) for the
/// installed kernel: the overlay supplies the dtb-copy and `extlinux.conf`
/// (`mk_extlinux`) hooks and initramfs-tools supplies the initrd hook, but the kernel
/// package configured *before* the overlay was laid in, so its own postinst found an
/// empty hook dir. Re-running them here — with the overlay, initramfs-tools, and the
/// `LABEL=`-based `/etc/fstab` all in place — is what populates `/boot` with the
/// initrd, board dtb, and `extlinux/extlinux.conf` that u-boot's extlinux bootflow
/// loads; without it the image has a kernel but nothing to boot it.
///
/// The account is created **locked** (no `chpasswd` here): the per-image first-boot
/// password (SEC-6) is non-reproducible, so baking it in would make the
/// produced tree unfit for the content-addressed cache. Everything this hook
/// does *is* reproducible, so the tree it yields is cacheable; the image node
/// splices the unique password into the staged `/etc/shadow` at assembly time
/// (see [`crate::image`]).
///
/// `staging`/`user` are baked in, so the script is self-contained. Target binaries
/// (`useradd`, `usermod`, …) run under the host's `qemu-user` binfmt when cross-arch,
/// transparently — the same mechanism the build sandbox uses.
fn customize_hook_script(staging: &Path, user: &str) -> String {
    format!(
        "#!/bin/sh\n\
         set -eu\n\
         rootfs=\"$1\"\n\
         # lay the staged overlay (layer overlays + generated config) into the rootfs.\n\
         # --remove-destination so our files replace base ones even when the base\n\
         # left a (possibly dangling) symlink there, e.g. /etc/default/locale.\n\
         # -dR + --preserve=mode (not owner, not timestamps): the staged tree is owned\n\
         # by the build user, which maps to `nobody` in the hook namespace; copying\n\
         # without preserving owner lands the files root-owned, as /etc config must be.\n\
         # Timestamps are dropped so overlay files take a fresh mtime that mmdebstrap's\n\
         # SOURCE_DATE_EPOCH clamp then pins to the epoch, rather than carrying a\n\
         # checkout-time mtime that could sit below the epoch and escape the clamp\n\
         # (DET-2).\n\
         cp -dR --remove-destination --preserve=mode \"{staging}/.\" \"$rootfs/\"\n\
         # default account, created locked; the per-image password is spliced in later\n\
         chroot \"$rootfs\" useradd -m -s /bin/bash \"{user}\"\n\
         chroot \"$rootfs\" usermod -aG video,render \"{user}\"\n\
         # passwordless sudo for the default account (0440, as visudo expects), and\n\
         # the ssh host-key reset, run INSIDE the chroot: an overlay could plant a\n\
         # symlink at /etc/sudoers.d or /etc/ssh, and doing these writes/removals from\n\
         # outside would follow it out of the rootfs (TRUST-2). Inside the chroot a\n\
         # symlink resolves against the rootfs root, so the mutation stays contained.\n\
         chroot \"$rootfs\" mkdir -p /etc/sudoers.d\n\
         chroot \"$rootfs\" sh -c 'printf \"%s ALL=(ALL) NOPASSWD: ALL\\n\" \"{user}\" > /etc/sudoers.d/{user}'\n\
         chroot \"$rootfs\" chmod 0440 /etc/sudoers.d/{user}\n\
         # regenerate ssh host keys on first boot\n\
         chroot \"$rootfs\" sh -c 'rm -f /etc/ssh/ssh_host_*'\n\
         # Generate the boot artifacts u-boot's extlinux bootflow loads. The overlay\n\
         # (laid in above) and initramfs-tools ship the /etc/kernel/postinst.d hooks\n\
         # that build the initrd, copy the board dtb into /boot, and write\n\
         # /boot/extlinux/extlinux.conf (root=LABEL=... from the generated fstab). The\n\
         # kernel package was configured before the overlay existed, so its own\n\
         # postinst run-parts found an empty hook dir and produced none of them;\n\
         # re-run the hooks now, with everything in place. --exit-on-error fails the\n\
         # build loudly rather than shipping a kernel with nothing to boot it.\n\
         chroot \"$rootfs\" sh -c 'kver=\"$(linux-version list | linux-version sort --reverse | head -n1)\"; run-parts --exit-on-error --arg=\"$kver\" /etc/kernel/postinst.d'\n",
        staging = staging.display(),
    )
}

/// Extract a single `member` from `tarball` to a string (`tar xOf`). Used by the
/// manifest reader (and tests); mmdebstrap tarballs store `./`-prefixed paths, so
/// pass e.g. `./var/lib/dpkg/status`.
fn tar_member(tarball: &Path, member: &str) -> Result<String, EngineError> {
    let out = Command::new("tar")
        .args(["xOf"])
        .arg(tarball)
        .arg(member)
        .output()
        .map_err(|source| EngineError::CommandSpawn {
            command: "tar".into(),
            context: format!("read {member} from rootfs tarball"),
            source,
        })?;
    if !out.status.success() {
        return Err(EngineError::CommandFailed {
            command: "tar".into(),
            context: format!("read {member} from rootfs tarball"),
            status: out.status.code(),
            stderr: String::from_utf8_lossy(&out.stderr).trim().to_string(),
        });
    }
    Ok(String::from_utf8_lossy(&out.stdout).into_owned())
}

/// Members every finished rootfs tarball must contain, checked by [`validate_tar`].
/// `./etc/shadow` is the password splice's appended member, so its presence proves
/// the archive is readable through to its end (not truncated); `./etc/os-release` and
/// `./etc/fstab` confirm the archive is a real Debian rootfs rather than an unrelated
/// or empty tar.
const REQUIRED_TAR_MEMBERS: &[&str] = &["./etc/os-release", "./etc/fstab", "./etc/shadow"];

/// Validate that `tarball` is a complete, readable rootfs archive before the image
/// stage formats it into ext4 (ATOM-1). Lists the archive end-to-end (`tar tf`, which
/// errors on a truncated archive) and confirms every `REQUIRED_TAR_MEMBERS` entry is
/// present (including the still-locked `./etc/shadow`). A partial tar left by an
/// interrupted bootstrap fails here with a "re-run rootfs" pointer, rather than being
/// silently formatted into a broken image by an `--stage image` retry whose gate only
/// checked that the file existed.
pub fn validate_tar(tarball: &Path) -> Result<(), EngineError> {
    let out = Command::new("tar")
        .arg("-tf")
        .arg(tarball)
        .output()
        .map_err(|source| EngineError::CommandSpawn {
            command: "tar".into(),
            context: "validate rootfs tarball".into(),
            source,
        })?;
    if !out.status.success() {
        return Err(EngineError::CommandFailed {
            command: "tar".into(),
            context: format!("validate rootfs tarball {}", tarball.display()),
            status: out.status.code(),
            stderr: String::from_utf8_lossy(&out.stderr).trim().to_string(),
        });
    }
    let listing = String::from_utf8_lossy(&out.stdout);
    let members: std::collections::HashSet<&str> = listing.lines().map(str::trim).collect();
    for required in REQUIRED_TAR_MEMBERS {
        if !members.contains(required) {
            return Err(EngineError::ArtifactMissing {
                what: format!("member {required} in rootfs tarball (incomplete tar?)"),
                location: tarball.display().to_string(),
            });
        }
    }
    Ok(())
}

/// The sha256-capture `--customize-hook` script: hash every `.deb` still in the
/// rootfs's apt cache (kept alive by [`mmdebstrap_argv`]'s two flags) and write
/// `name version arch sha256` lines to `out`.
///
/// It runs on the host as ns-root with the rootfs as `$1`, so `dpkg-deb` (for the
/// exact control identity — the join key against dpkg status) and `sha256sum`
/// (for the content hash) are host binaries, not qemu-emulated. `${sum%% *}`
/// takes just the digest from `sha256sum`'s `<digest>  <file>` output. The glob
/// guard tolerates an empty cache (writes an empty file rather than failing).
fn capture_hashes_hook_script(out: &Path) -> String {
    format!(
        "#!/bin/sh\n\
         set -eu\n\
         rootfs=\"$1\"\n\
         out=\"{out}\"\n\
         : > \"$out\"\n\
         for deb in \"$rootfs\"/var/cache/apt/archives/*.deb; do\n\
         \t[ -e \"$deb\" ] || continue\n\
         \tident=$(dpkg-deb --show --showformat='${{Package}} ${{Version}} ${{Architecture}}' \"$deb\")\n\
         \tsum=$(sha256sum \"$deb\")\n\
         \tprintf '%s %s\\n' \"$ident\" \"${{sum%% *}}\" >> \"$out\"\n\
         done\n\
         # the file is owned by a subuid outside the namespace; 0644 lets the host read it back.\n\
         chmod 0644 \"$out\"\n",
        out = out.display(),
    )
}

/// Read the capture hook's `name version arch sha256` lines into a lookup keyed
/// by `(name, version, arch)`. Absent-but-successful is empty (the hook always
/// creates the file); a read failure is an error.
fn read_deb_hashes(path: &Path) -> Result<HashMap<(String, String, String), String>, EngineError> {
    let text = std::fs::read_to_string(path).map_err(|s| EngineError::io(path, s))?;
    let mut map = HashMap::new();
    for line in text.lines() {
        let mut f = line.split_whitespace();
        if let (Some(name), Some(ver), Some(arch), Some(sha)) =
            (f.next(), f.next(), f.next(), f.next())
        {
            map.insert(
                (name.to_string(), ver.to_string(), arch.to_string()),
                sha.to_string(),
            );
        }
    }
    Ok(map)
}

/// Extract the rootfs's dpkg status from `tarball` and write the solved manifest
/// (installed `name version arch sha256`, sorted by name) to `manifest_out`, the
/// content-pinned reproducibility artifact the lock's `[rootfs].manifest` points
/// at. The sha256 for each installed package is joined from `hashes`
/// (the capture hook's per-`.deb` digests); a package with no captured hash is a
/// [`ManifestIncomplete`](EngineError::ManifestIncomplete) error, never a
/// silently unpinned row.
fn write_manifest(
    tarball: &Path,
    manifest_out: &Path,
    hashes: &HashMap<(String, String, String), String>,
    step: &Step,
) -> Result<(), EngineError> {
    // mmdebstrap tarballs store paths `./`-prefixed (as the sandbox extract shows).
    let status = tar_member(tarball, "./var/lib/dpkg/status")?;
    let entries = parse_dpkg_status(&status);
    let body = render_manifest(&entries, hashes)?;
    if let Some(parent) = manifest_out.parent() {
        std::fs::create_dir_all(parent).map_err(|s| EngineError::io(parent, s))?;
    }
    std::fs::write(manifest_out, &body).map_err(|s| EngineError::io(manifest_out, s))?;
    step.log(format!(
        "wrote solved manifest ({} packages, sha256-pinned) to {}",
        entries.len(),
        manifest_out.display()
    ));
    Ok(())
}

/// Render the solved-manifest text: one sorted `name version arch sha256` line
/// per installed package, joining each package's sha256 from `hashes`. Pure, so
/// the join and the completeness check are testable without a bootstrap. An
/// installed package with no captured hash yields
/// [`ManifestIncomplete`](EngineError::ManifestIncomplete) naming a bounded
/// sample — the pin is all-or-nothing.
fn render_manifest(
    entries: &[PkgEntry],
    hashes: &HashMap<(String, String, String), String>,
) -> Result<String, EngineError> {
    let mut body = String::from(
        "# Solved rootfs package manifest: installed name version arch sha256.\n",
    );
    let mut missing = Vec::new();
    for e in entries {
        let key = (e.name.clone(), e.version.clone(), e.arch.clone());
        match hashes.get(&key) {
            Some(sha) => body.push_str(&format!("{} {} {} {}\n", e.name, e.version, e.arch, sha)),
            None => missing.push(format!("{} {} {}", e.name, e.version, e.arch)),
        }
    }
    if !missing.is_empty() {
        const SAMPLE: usize = 8;
        let sample = missing.iter().take(SAMPLE).cloned().collect::<Vec<_>>().join(", ");
        return Err(EngineError::ManifestIncomplete {
            count: missing.len(),
            sample: if missing.len() > SAMPLE {
                format!("{sample}, …")
            } else {
                sample
            },
        });
    }
    Ok(body)
}

/// One installed package in the solved manifest.
struct PkgEntry {
    /// Package name.
    name: String,
    /// Exact installed version.
    version: String,
    /// Package architecture.
    arch: String,
}

/// Parse a dpkg `status` file into the installed packages, sorted by name. Only
/// stanzas whose `Status:` is `install ok installed` count. Pure, so the manifest
/// derivation is testable without a bootstrap.
fn parse_dpkg_status(text: &str) -> Vec<PkgEntry> {
    let mut entries = Vec::new();
    for stanza in text.split("\n\n") {
        let (mut name, mut version, mut arch, mut installed) = (None, None, None, false);
        for line in stanza.lines() {
            if let Some(v) = line.strip_prefix("Package: ") {
                name = Some(v.trim().to_string());
            } else if let Some(v) = line.strip_prefix("Version: ") {
                version = Some(v.trim().to_string());
            } else if let Some(v) = line.strip_prefix("Architecture: ") {
                arch = Some(v.trim().to_string());
            } else if let Some(v) = line.strip_prefix("Status: ") {
                installed = v.trim() == "install ok installed";
            }
        }
        if let (true, Some(name), Some(version), Some(arch)) = (installed, name, version, arch) {
            entries.push(PkgEntry { name, version, arch });
        }
    }
    entries.sort_by(|a, b| a.name.cmp(&b.name));
    entries
}

/// Generated rootfs config files, rendered from resolved values. Pure —
/// each returns the exact file content — so the config is unit-testable.
mod config {
    /// `/etc/fstab`: mount the rootfs by ext4 **label** (`label`, the same value
    /// the image node's mkfs assigns) rather than UUID — the UUID is not known
    /// until the image node formats ext4, *after* this tarball is built, so the
    /// label decouples the rootfs build from image assembly. The caller threads the
    /// one resolved label through both nodes so this entry always matches the
    /// on-disk label.
    pub fn fstab(label: &str) -> String {
        format!(
            "# regenerate extlinux.conf via /boot/mk_extlinux after editing the root entry\n\
             # <device>\t<mount>\t<type>\t<options>\t\t<dump> <pass>\n\
             LABEL={label}\t/\text4\terrors=remount-ro\t0      1\n"
        )
    }

    /// `/etc/hostname`.
    pub fn hostname(h: &str) -> String {
        format!("{h}\n")
    }

    /// `/etc/hosts` with the loopback + a `127.0.1.1` entry for the hostname.
    pub fn hosts(h: &str) -> String {
        format!(
            "127.0.0.1\tlocalhost\n127.0.1.1\t{h}\n\
             ::1\tlocalhost ip6-localhost ip6-loopback\nff02::1\tip6-allnodes\nff02::2\tip6-allrouters\n"
        )
    }

    /// `/etc/apt/sources.list` for `suite` with the standard component set +
    /// security and updates pockets. Always the canonical `deb.debian.org` — the
    /// build-time `--mirror` override only redirects the bootstrap *fetch*, not the
    /// sources the shipped image points its `apt` at, so a device updates from the
    /// official mirror regardless of which mirror built it. Plain `http://` is
    /// standard Debian practice: apt verifies each `Release` signature against the
    /// device's archive keyring, so the transport carries no integrity burden.
    pub fn apt_sources(suite: &str) -> String {
        format!(
            "deb http://deb.debian.org/debian {suite} main contrib non-free non-free-firmware\n\
             deb http://deb.debian.org/debian-security {suite}-security main contrib non-free non-free-firmware\n\
             deb http://deb.debian.org/debian {suite}-updates main contrib non-free non-free-firmware\n"
        )
    }

    /// `/etc/default/locale` — a C.UTF-8 system locale (no locale package needed).
    pub fn locale() -> String {
        "LANG=\"C.UTF-8\"\nLC_ALL=\nLANGUAGE=\n".to_string()
    }

    /// `/etc/kernel-img.conf` — install kernels into `/boot` without symlinks, as
    /// the extlinux boot flow expects.
    pub fn kernel_img_conf() -> String {
        "link_in_boot = 1\ndo_symlinks = 0\n".to_string()
    }

    /// `/etc/boot2deb/board.conf` — board boot parameters the boot-method overlay
    /// scripts (`/etc/kernel/postinst.d` + `postrm.d` hooks and `/boot/mk_extlinux`)
    /// source, so those stay board-agnostic instead of hardcoding one board's dtb.
    /// Derived from the device's resolved `kernel_dtb`: `DTB_PATH` (relative to the
    /// DT output dir) locates the dtb inside the installed `linux-image` package,
    /// and `DTB_NAME` (its basename) names the copy placed in `/boot`.
    pub fn board_conf(kernel_dtb: &str) -> String {
        let name = kernel_dtb.rsplit('/').next().unwrap_or(kernel_dtb);
        format!(
            "# Generated by boot2deb -- board boot parameters. Do not edit.\n\
             # Sourced by /etc/kernel/{{postinst,postrm}}.d hooks and /boot/mk_extlinux.\n\
             DTB_PATH=\"{kernel_dtb}\"\n\
             DTB_NAME=\"{name}\"\n"
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use boot2deb_core::{resolve_recipe, ConfigRoot, Overrides};

    fn repo_root() -> ConfigRoot {
        ConfigRoot::new(
            std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .ancestors()
                .nth(2)
                .unwrap()
                .to_path_buf(),
        )
    }

    fn rk1() -> ResolvedBuild {
        resolve_recipe(&repo_root(), "turing-rk1-forky", &Overrides::default()).unwrap()
    }

    #[test]
    fn board_conf_derives_dtb_path_and_name() {
        let c = config::board_conf("rockchip/rk3576-h96-max-m9.dtb");
        assert!(c.contains("DTB_PATH=\"rockchip/rk3576-h96-max-m9.dtb\""));
        assert!(c.contains("DTB_NAME=\"rk3576-h96-max-m9.dtb\""));
        // A bare filename (no dir) uses itself as the name.
        assert!(config::board_conf("board.dtb").contains("DTB_NAME=\"board.dtb\""));
    }

    #[test]
    fn fstab_mounts_root_by_label() {
        let f = config::fstab("rootfs");
        assert!(f.contains("LABEL=rootfs\t/\text4"));
        assert!(!f.contains("UUID="));
        // A custom label threads through so it matches the image node's mkfs.
        assert!(config::fstab("rk1root").contains("LABEL=rk1root\t/\text4"));
    }

    #[test]
    fn apt_sources_has_suite_pockets_and_components() {
        let s = config::apt_sources("forky");
        assert!(s.contains("deb http://deb.debian.org/debian forky main contrib non-free non-free-firmware"));
        assert!(s.contains("forky-security"));
        assert!(s.contains("forky-updates"));
    }

    #[test]
    fn hosts_names_the_hostname() {
        assert!(config::hosts("turing-rk1").contains("127.0.1.1\tturing-rk1"));
    }

    #[test]
    fn mmdebstrap_argv_includes_packages_repo_and_hook() {
        let build = rk1();
        let extra = vec!["linux-image-7.1.1-1-arm64".to_string()];
        // A fallback snapshot: live mirror then the snapshot mirror, so both reach
        // the trailing positionals ahead of the local repo.
        let mirrors = vec![
            crate::DEFAULT_MIRROR.to_string(),
            "https://snapshot.debian.org/archive/debian/20260628T083000Z/".to_string(),
        ];
        let opts = RootfsOptions {
            repo_debs: &[],
            overlay_dirs: &[],
            out_dir: Path::new("/w/out"),
            keyring: Some(Path::new("/kr.gpg")),
            manifest_out: Path::new("/w/m.pkgs.lock"),
            mirrors: &mirrors,
            extra_packages: &extra,
            rootfs_label: "rootfs",
            cache_dir: None,
            refresh: false,
            apt_sources: &[],
            source_date_epoch: None,
        };
        let argv = mmdebstrap_argv(
            &build,
            &opts,
            Some(Path::new("/kr.gpg")),
            "deb [trusted=yes] copy:///w/localrepo ./",
            Path::new("/w/out/turing-rk1-rootfs.tar"),
            Path::new("/w/hook.sh"),
            Path::new("/w/capture-hashes.sh"),
        );
        assert!(argv.contains(&"--mode=unshare".to_string()));
        assert!(argv.contains(&"--arch=arm64".to_string()));
        assert!(argv.contains(&"--variant=important".to_string()));
        assert!(argv.contains(&"--keyring=/kr.gpg".to_string()));
        // The two flags that keep every fetched .deb in the apt cache through the
        // customize stage, so the capture hook can hash them.
        assert!(argv.contains(&"--skip=essential/unlink".to_string()));
        assert!(argv.contains(&"--aptopt=APT::Keep-Downloaded-Packages \"true\"".to_string()));
        // The merged package set + base excludes (as `pkgname-` deselections) all
        // ride in the single --include; mmdebstrap has no --exclude flag.
        assert!(argv.iter().any(|a| a.starts_with("--include=")
            && a.contains("ffmpeg-rk")
            && a.contains("openssh-server")
            && a.contains("linux-image-7.1.1-1-arm64")
            && a.contains("isc-dhcp-client-")));
        assert!(!argv.iter().any(|a| a.starts_with("--exclude=")));
        // `--` terminates options immediately before the positionals (SUB-2).
        assert_eq!(argv[argv.len() - 6], "--");
        // Suite, tarball, both mirrors (in order), and the local repo source are the
        // trailing args.
        let tail = &argv[argv.len() - 5..];
        assert_eq!(tail[0], "forky");
        assert_eq!(tail[1], "/w/out/turing-rk1-rootfs.tar");
        assert_eq!(tail[2], crate::DEFAULT_MIRROR);
        assert_eq!(
            tail[3],
            "https://snapshot.debian.org/archive/debian/20260628T083000Z/"
        );
        assert_eq!(tail[4], "deb [trusted=yes] copy:///w/localrepo ./");
        // Both customize-hooks run against the rootfs: the hash capture first,
        // then the overlay/config hook.
        let hooks: Vec<&String> = argv
            .iter()
            .filter(|a| a.starts_with("--customize-hook="))
            .collect();
        assert_eq!(hooks.len(), 2);
        assert!(hooks[0].starts_with("--customize-hook=sh /w/capture-hashes.sh"));
        assert!(hooks[1].starts_with("--customize-hook=sh /w/hook.sh"));
    }

    #[test]
    fn hook_creates_locked_account_and_lays_overlay() {
        let script = customize_hook_script(Path::new("/w/rootfs-overlay"), "debian");
        // Timestamps are not preserved, so overlay files take a fresh mtime that
        // mmdebstrap's SOURCE_DATE_EPOCH clamp pins to the epoch (DET-2).
        assert!(script.contains(
            "cp -dR --remove-destination --preserve=mode \"/w/rootfs-overlay/.\" \"$rootfs/\""
        ));
        assert!(!script.contains("--preserve=mode,timestamps"));
        assert!(script.contains("chroot \"$rootfs\" useradd -m -s /bin/bash \"debian\""));
        // The account is created locked; the per-image password is spliced into the
        // finished tar afterward, NOT baked here — that keeps the tree cacheable.
        assert!(!script.contains("chpasswd"));
        assert!(!script.contains("passwd -e"));
        assert!(script.contains("usermod -aG video,render"));
        // Sudoers write, chmod, and the ssh host-key reset all run inside the chroot
        // so an overlay symlink cannot redirect them out of the rootfs (TRUST-2).
        assert!(script.contains(
            "chroot \"$rootfs\" sh -c 'printf \"%s ALL=(ALL) NOPASSWD: ALL\\n\" \"debian\" > /etc/sudoers.d/debian'"
        ));
        assert!(script.contains("chroot \"$rootfs\" chmod 0440 /etc/sudoers.d/debian"));
        assert!(script.contains("chroot \"$rootfs\" sh -c 'rm -f /etc/ssh/ssh_host_*'"));
        // None of these mutations touch a "$rootfs/..." path from outside the chroot.
        assert!(!script.contains("> \"$rootfs/etc/sudoers.d"));
        assert!(!script.contains("rm -f \"$rootfs\"/etc/ssh"));
        // Boot artifacts: the kernel postinst.d hooks are re-run for the installed
        // kernel (they were absent when the kernel package configured), so /boot gains
        // the initrd, dtb, and extlinux.conf u-boot loads. Run inside the chroot,
        // --exit-on-error so a failed hook fails the build rather than shipping an
        // unbootable image.
        assert!(script.contains(
            "kver=\"$(linux-version list | linux-version sort --reverse | head -n1)\"; run-parts --exit-on-error --arg=\"$kver\" /etc/kernel/postinst.d"
        ));
    }

    #[test]
    fn simulate_argv_mirrors_the_bootstrap_selection() {
        let build = rk1();
        let extra = vec!["linux-image-7.1.1-1-arm64".to_string()];
        let mirrors = vec![crate::DEFAULT_MIRROR.to_string()];
        let opts = RootfsOptions {
            repo_debs: &[],
            overlay_dirs: &[],
            out_dir: Path::new("/w/out"),
            keyring: Some(Path::new("/kr.gpg")),
            manifest_out: Path::new("/w/m.pkgs.lock"),
            mirrors: &mirrors,
            extra_packages: &extra,
            rootfs_label: "rootfs",
            cache_dir: None,
            refresh: false,
            apt_sources: &[],
            source_date_epoch: None,
        };
        let argv = simulate_argv(
            &build,
            &opts,
            Some(Path::new("/kr.gpg")),
            "deb [trusted=yes] copy:///w/localrepo ./",
        );
        // Solve-only: no install, no rootfs written.
        assert!(argv.contains(&"--simulate".to_string()));
        assert!(argv.contains(&"--verbose".to_string()));
        // The same package selection the real bootstrap would install.
        assert!(argv.iter().any(|a| a.starts_with("--include=")
            && a.contains("ffmpeg-rk")
            && a.contains("linux-image-7.1.1-1-arm64")
            && a.contains("isc-dhcp-client-")));
        // No hooks / cache-retention flags on the solve path.
        assert!(!argv.iter().any(|a| a.starts_with("--customize-hook=")));
        assert!(!argv.iter().any(|a| a.starts_with("--skip=")));
        // `--` terminates options immediately before the positionals (SUB-2).
        assert_eq!(argv[argv.len() - 5], "--");
        // Suite, /dev/null target, mirror, and the local repo are the trailing args.
        let tail = &argv[argv.len() - 4..];
        assert_eq!(tail[0], "forky");
        assert_eq!(tail[1], "/dev/null");
        assert_eq!(tail[2], crate::DEFAULT_MIRROR);
        assert_eq!(tail[3], "deb [trusted=yes] copy:///w/localrepo ./");
    }

    #[test]
    fn feature_apt_sources_become_signed_deb_positionals_before_the_local_repo() {
        // CFG-1: a resolved feature repo (e.g. Jellyfin) must reach the solve as a
        // signed `deb` positional so apt can resolve its out-of-mirror package.
        let build = rk1();
        let mirrors = vec![crate::DEFAULT_MIRROR.to_string()];
        let jellyfin = AptSource {
            name: "jellyfin".into(),
            uri: "https://repo.jellyfin.org/debian".into(),
            suite: "trixie".into(),
            components: vec!["main".into()],
            signed_by: "jellyfin.gpg".into(),
        };
        let repos = vec![AptRepo {
            source: &jellyfin,
            keyring: PathBuf::from("/kr/jellyfin.gpg"),
        }];
        // The rendered line carries signed-by, uri, suite, and components.
        assert_eq!(
            apt_source_line(&repos[0]),
            "deb [signed-by=/kr/jellyfin.gpg] https://repo.jellyfin.org/debian trixie main"
        );
        let opts = RootfsOptions {
            repo_debs: &[],
            overlay_dirs: &[],
            out_dir: Path::new("/w/out"),
            keyring: Some(Path::new("/kr.gpg")),
            manifest_out: Path::new("/w/m.pkgs.lock"),
            mirrors: &mirrors,
            extra_packages: &[],
            rootfs_label: "rootfs",
            cache_dir: None,
            refresh: false,
            apt_sources: &repos,
            source_date_epoch: None,
        };
        // Both the solve and the bootstrap carry the repo, ordered after the mirror
        // and before the trailing local repo.
        for argv in [
            simulate_argv(&build, &opts, None, "deb [trusted=yes] copy:///w/localrepo ./"),
            mmdebstrap_argv(
                &build,
                &opts,
                None,
                "deb [trusted=yes] copy:///w/localrepo ./",
                Path::new("/w/out/turing-rk1-rootfs.tar"),
                Path::new("/w/hook.sh"),
                Path::new("/w/capture-hashes.sh"),
            ),
        ] {
            let jf = argv
                .iter()
                .position(|a| a.contains("repo.jellyfin.org"))
                .expect("jellyfin repo positional present");
            let mirror = argv.iter().position(|a| a == crate::DEFAULT_MIRROR).unwrap();
            let local = argv.iter().position(|a| a.contains("copy:///w/localrepo")).unwrap();
            assert!(mirror < jf && jf < local, "order: mirror < feature repo < local repo");
        }
    }

    /// Build a small mmdebstrap-shaped tarball (`./`-prefixed) at `tarball` from the
    /// given `members` (`archive-path`, `contents`). Returns false if `tar` is
    /// unavailable so the caller can skip.
    #[cfg(test)]
    fn build_test_tar(tarball: &Path, root: &Path, members: &[(&str, &str)]) -> bool {
        for (path, contents) in members {
            let full = root.join(path.trim_start_matches("./"));
            std::fs::create_dir_all(full.parent().unwrap()).unwrap();
            std::fs::write(&full, contents).unwrap();
        }
        let mut cmd = Command::new("tar");
        cmd.arg("-cf").arg(tarball).arg("-C").arg(root);
        for (path, _) in members {
            cmd.arg(path);
        }
        cmd.status().map(|s| s.success()).unwrap_or(false)
    }

    #[test]
    fn validate_tar_rejects_a_tar_missing_a_required_member() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("r");
        let tarball = tmp.path().join("rootfs.tar");
        // Missing `./etc/shadow` — the completeness sentinel — stands in for a tar
        // truncated by an interrupted bootstrap.
        let members = [
            ("./etc/os-release", "ID=debian\n"),
            ("./etc/fstab", "LABEL=rootfs / ext4 defaults 0 1\n"),
        ];
        if !build_test_tar(&tarball, &root, &members) {
            eprintln!("skipping: tar unavailable");
            return;
        }
        let err = validate_tar(&tarball).unwrap_err();
        assert!(
            matches!(err, EngineError::ArtifactMissing { what, .. } if what.contains("./etc/shadow")),
            "expected a missing-member error naming shadow"
        );
    }

    #[test]
    fn write_staged_forces_0644_regardless_of_umask() {
        use std::os::unix::fs::PermissionsExt;
        let tmp = tempfile::tempdir().unwrap();
        write_staged(tmp.path(), "etc/hostname", "host\n").unwrap();
        let mode = std::fs::metadata(tmp.path().join("etc/hostname"))
            .unwrap()
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o644);
    }

    #[test]
    fn parse_dpkg_status_keeps_only_installed() {
        let text = "Package: libc6\nStatus: install ok installed\nVersion: 2.41-1\nArchitecture: arm64\n\
                    \n\
                    Package: half-installed\nStatus: install ok unpacked\nVersion: 1.0\nArchitecture: arm64\n\
                    \n\
                    Package: ffmpeg-rk\nStatus: install ok installed\nVersion: 3e53143\nArchitecture: arm64\n";
        let entries = parse_dpkg_status(text);
        let names: Vec<_> = entries.iter().map(|e| e.name.as_str()).collect();
        // Only installed packages, sorted; the unpacked-but-not-configured one is out.
        assert_eq!(names, vec!["ffmpeg-rk", "libc6"]);
        assert_eq!(entries[0].version, "3e53143");
        assert_eq!(entries[1].arch, "arm64");
    }

    #[test]
    fn capture_hook_hashes_the_apt_cache() {
        let script = capture_hashes_hook_script(Path::new("/w/deb-sha256sums"));
        // Writes to the staged output, iterating the rootfs's apt archive.
        assert!(script.contains("out=\"/w/deb-sha256sums\""));
        assert!(script.contains("\"$rootfs\"/var/cache/apt/archives/*.deb"));
        // Identity via dpkg-deb (the join key), content hash via sha256sum, and the
        // glob guard for an empty cache.
        assert!(script.contains(
            "dpkg-deb --show --showformat='${Package} ${Version} ${Architecture}'"
        ));
        assert!(script.contains("sha256sum"));
        assert!(script.contains("[ -e \"$deb\" ] || continue"));
        assert!(script.contains("${sum%% *}"));
        // The output is chmod'd so the host can read the subuid-owned file back.
        assert!(script.contains("chmod 0644 \"$out\""));
    }

    #[test]
    fn read_deb_hashes_keys_by_name_version_arch() {
        let tmp = tempfile::tempdir().unwrap();
        let f = tmp.path().join("deb-sha256sums");
        std::fs::write(
            &f,
            "libc6 2.41-1 arm64 aaaa\ntzdata 2025b-1 all bbbb\nffmpeg-rk 3e53143 arm64 cccc\n",
        )
        .unwrap();
        let map = read_deb_hashes(&f).unwrap();
        assert_eq!(map.len(), 3);
        assert_eq!(
            map.get(&("libc6".into(), "2.41-1".into(), "arm64".into())),
            Some(&"aaaa".to_string())
        );
        assert_eq!(
            map.get(&("tzdata".into(), "2025b-1".into(), "all".into())),
            Some(&"bbbb".to_string())
        );
    }

    #[test]
    fn render_manifest_joins_sha256_sorted() {
        let entries = vec![
            PkgEntry { name: "libc6".into(), version: "2.41-1".into(), arch: "arm64".into() },
            PkgEntry { name: "ffmpeg-rk".into(), version: "3e53143".into(), arch: "arm64".into() },
        ];
        let mut hashes = HashMap::new();
        hashes.insert(("libc6".into(), "2.41-1".into(), "arm64".into()), "aaaa".into());
        hashes.insert(("ffmpeg-rk".into(), "3e53143".into(), "arm64".into()), "cccc".into());
        let body = render_manifest(&entries, &hashes).unwrap();
        let lines: Vec<&str> = body.lines().filter(|l| !l.starts_with('#')).collect();
        assert_eq!(lines, vec!["libc6 2.41-1 arm64 aaaa", "ffmpeg-rk 3e53143 arm64 cccc"]);
    }

    #[test]
    fn render_manifest_errors_on_unpinned_package() {
        let entries = vec![
            PkgEntry { name: "libc6".into(), version: "2.41-1".into(), arch: "arm64".into() },
            PkgEntry { name: "orphan".into(), version: "1.0".into(), arch: "arm64".into() },
        ];
        let mut hashes = HashMap::new();
        hashes.insert(("libc6".into(), "2.41-1".into(), "arm64".into()), "aaaa".into());
        let err = render_manifest(&entries, &hashes).unwrap_err();
        match err {
            EngineError::ManifestIncomplete { count, sample } => {
                assert_eq!(count, 1);
                assert!(sample.contains("orphan 1.0 arm64"));
            }
            other => panic!("expected ManifestIncomplete, got {other:?}"),
        }
    }
}
