//! Rootfs node — bootstraps the device's Debian userland and emits the
//! `tar` archive the [image node](crate::image) formats into ext4, plus a
//! content-pinned solved package manifest.
//!
//! The bootstrap is in-process and rootless — no `sudo`, no persistent chroot, no
//! external bootstrap binary. [`build_rootfs`] drives ferroday-cage's Debian
//! provisioner: it installs the merged rootfs package set
//! ([`ResolvedBuild::rootfs_packages`]) from the build's own
//! [`LocalDistsRepo`](crate::repo::LocalDistsRepo) plus the suite mirror — so each
//! `.deb`'s dependencies resolve together — lays the staged overlay in, runs the
//! target config (user account, ssh first-boot, group membership), and re-runs the
//! kernel `postinst.d` hooks so `/boot` gains the initrd, board dtb, and
//! `extlinux.conf` u-boot loads (the kernel configured before the overlay's
//! hooks existed, so its own postinst produced none of them). The overlay is the
//! layered substrate merged in Rust beforehand: each layer's `overlay/` tree
//! followed by the *generated* config this module produces from the
//! resolved values (fstab, hostname, apt sources, locale, machine-id).
//!
//! This module owns the node's inputs, the two staged overlay trees, and the
//! generated config; the bootstrap itself is the `provisioner` submodule.
//!
//! The manifest is fully content-pinned — `name + version + arch + sha256` per
//! package — from the archive-recorded digests in the resolved plan, so each row
//! names the exact `.deb` the image carries.
//!
//! Board firmware (rockchip display, panthor Mali, Realtek NIC) is staged as
//! Debian `non-free-firmware` packages declared on the SoC layer (for RK3588:
//! `firmware-misc-nonfree` + `firmware-realtek` in `socs/rk3588.toml`), not
//! extracted from a linux-firmware tarball — so it is snapshot-pinned like every
//! other package and needs no separate fetch step.

mod provisioner;
pub(crate) use provisioner::feature_repositories;
pub use provisioner::{
    build_rootfs, read_plan_record, read_plan_weights, sweep_provisioned, PlanRecord, PlanWeights,
};

use crate::error::EngineError;
use crate::event::Step;
use boot2deb_core::model::{AptSource, InitramfsCompress, ResolvedBuild};
use std::path::{Path, PathBuf};
use std::process::Command;

/// The default appliance account. Its first-boot password is **unique per built
/// image** — generated by [`crate::secret::generate_password`] and expired at
/// build time (`passwd -e`), so it must be changed at first login and no
/// guessable credential is ever on the network. Membership in
/// `video`/`render` is what the HW-accel udev rules grant device access through.
pub const DEFAULT_USER: &str = "debian";

/// Filesystem inputs for the rootfs node.
pub struct RootfsOptions<'a> {
    /// The build's `.deb`s (kernel, u-boot, MPP/RGA, ffmpeg-rk, …) — assembled
    /// into a [`LocalDistsRepo`](crate::repo::LocalDistsRepo) the bootstrap
    /// installs the accel packages from.
    pub repo_debs: &'a [PathBuf],
    /// Layer `overlay/` directories to lay into the rootfs **after** every package,
    /// in merge order (base → soc → boot-method → device → features). Non-existent
    /// entries are skipped; later entries win — including over the packages' own
    /// files, which is the point of laying them in last.
    pub overlay_dirs: &'a [PathBuf],
    /// Layer `overlay-pre/` directories to lay into the rootfs **before** any package
    /// is installed, same merge order.
    ///
    /// This is for config a package's maintainer scripts must see *while they run*,
    /// where winning afterwards is too late — the initramfs settings that decide how
    /// big the first initramfs is, and, on a depthcharge board, the
    /// `depthcharge-tools` config that stops its kernel hook from hunting the build
    /// host's disks for a ChromeOS kernel partition to write to. Empty for a board
    /// that needs none.
    pub preinstall_overlay_dirs: &'a [PathBuf],
    /// The boot-method-specific configuration written into the pre-install overlay
    /// ([`BootConfig`]), or `None` where the boot method generates none.
    pub boot_config: Option<BootConfig<'a>>,
    /// The image's account of itself
    /// ([`SystemIdentity`](boot2deb_core::provenance::SystemIdentity)), written into the
    /// rootfs at `/etc/boot2deb/image.toml`.
    ///
    /// It ships *inside* the image because its whole purpose is to be readable when the
    /// image is all you have: from other media, without mounting it, and possibly on a
    /// machine that is not this board. That last case is the one that decides its
    /// contents — `depthchargectl` recovers a board profile from the *running* board's
    /// HWID, so a tool re-signing this image's kernel from somewhere else has no way to
    /// learn it except by being told here.
    ///
    /// Written as part of the staged overlay, so it folds into the rootfs cache key with
    /// every other generated file ([`crate::rootcache::dir_fingerprints`]) and a cached tree can
    /// never be reused under an identity that disagrees with it.
    pub image_identity: &'a boot2deb_core::provenance::SystemIdentity,
    /// The rootfs partition's PARTUUID, as the image node will write it.
    ///
    /// Under `depthcharge` this is an *input* to the rootfs, not an output of the
    /// partition table: `depthchargectl` derives the signed kernel's `root=` from the
    /// image's own `/etc/fstab`, so the fstab has to name the partition before the
    /// filesystem containing it exists. The value is folded into the rootfs cache key
    /// with the rest of the staged overlay, so a cached tree can never carry an fstab
    /// pointing somewhere the table does not.
    pub rootfs_partuuid: uuid::Uuid,
    /// Directory the rootfs tarball is written to.
    pub out_dir: &'a Path,
    /// The build point's
    /// [artifact stem](boot2deb_core::buildpoint::BuildPoint::artifact_stem) — the
    /// tarball is published as `<stem>-rootfs.tar`. A board carries several recipes
    /// with different package sets, so a tarball named for the board alone would let
    /// one recipe's userland be formatted into another's image.
    pub stem: &'a str,
    /// The build's scratch tree — where this node stages the overlays and provisions
    /// the rootfs before exporting it.
    ///
    /// Deliberately **not** `TMPDIR`, for the same reason as
    /// [`build_root_uppers`](crate::sandbox::build_root_uppers). The provisioned tree
    /// is the whole target userland (multiple GB) carrying `security.capability`
    /// xattrs and subordinate-mapped ownership, and on most desktop distros `/tmp` is a
    /// RAM-backed `tmpfs` sized to a fraction of physical memory — so `TMPDIR` would
    /// make whether the build succeeds a property of the host's mount table, and a
    /// `nodev`/`nosuid` `TMPDIR` would change what the tree can hold. The work dir is
    /// where the build's other large intermediates already live, and it is the
    /// directory [`doctor`](crate::checks) probes, so its capabilities are a *checked*
    /// host requirement rather than an inherited one.
    pub scratch_dir: &'a Path,
    /// Debian archive keyring verifying the suite's `Release` (as the sandbox);
    /// `None` uses the host apt trust store (Debian host only).
    pub keyring: Option<&'a Path>,
    /// Identity of the `qemu-user` interpreter that executes the target's maintainer
    /// scripts
    /// ([`qemu_identity`](crate::toolchain::HostToolchain::qemu_identity)), or `None`
    /// on a native host, where target binaries run directly and nothing is interpreted.
    ///
    /// An input to the *tree*, not merely a fact about the host: on a cross host every
    /// maintainer script runs under it, and so does everything they invoke —
    /// `update-initramfs` writing the initrd this image boots, `ldconfig`,
    /// `locale-gen`, and on a depthcharge board the kernel signing. So it is folded
    /// into the rootfs cache key ([`crate::rootcache::CacheKeyInputs`]) and a tree
    /// configured under one interpreter is never restored for a build using another.
    ///
    /// One residual: the binfmt handler is registered `F`-flagged, so the kernel pins
    /// an fd to the interpreter when the handler is registered, while this identity is
    /// probed from `PATH`. Debian's `qemu-user-static` re-registers as it upgrades, so
    /// the two agree; a host that registers its handler by hand has a window where they
    /// do not.
    pub interpreter_id: Option<&'a str>,
    /// Where the solved package manifest is written (the lock's `[rootfs].manifest`
    /// points at it).
    pub manifest_out: &'a Path,
    /// A plan document from an earlier build, replayed instead of resolving one
    /// (`reproduce`). `None` — every ordinary build — resolves against the mirrors.
    ///
    /// Set, the archive is not consulted at all: no release is fetched and no package
    /// index is, and the exact versions the document names are installed by the digests
    /// it records. **That moves the trust anchor.** An ordinary build's package digests
    /// chain to the archive signature that vouched for the index they came from; a
    /// replay's chain to this document, because the index that would have carried the
    /// signature is never read. Each `.deb` is still verified against the digest here,
    /// so a mirror serving different bytes is caught — what is no longer checked is that
    /// the document itself describes a set the archive ever offered.
    ///
    /// That trade is right for reproducing a published image and wrong for a routine
    /// build, which is why it is reachable only through the command that names it.
    pub pinned_plan: Option<&'a Path>,
    /// Ordered Debian mirror list the bootstrap fetches from — the live mirror,
    /// plus a `snapshot.debian.org` mirror when a captured snapshot is activated
    /// (resolved by [`crate::snapshot::resolve_mirrors`]). Must be non-empty;
    /// apt tries them in order, so a `fallback` snapshot backfills the first
    /// mirror's 404s from the second.
    pub mirrors: &'a [String],
    /// Extra package names to install beyond [`ResolvedBuild::rootfs_packages`] —
    /// build artifacts whose names are version-specific and thus unknowable to the
    /// static config, above all the freshly built kernel image.
    pub extra_packages: &'a [String],
    /// Root of the content-addressed rootfs cache. `Some(dir)` enables the
    /// early-cutoff cache: the resolved plan keys a store under `<dir>/rootfs/`,
    /// and an unchanged solved set restores a stored tree instead of
    /// re-bootstrapping ([`crate::rootcache`]). It also roots the persistent
    /// `.deb` download cache the provisioner reuses across builds. `None` always
    /// bootstraps.
    pub cache_dir: Option<&'a Path>,
    /// Ignore a cache hit and re-bootstrap, refreshing the stored entry
    /// (`--refresh-rootfs`). The solve still runs and the fresh tree is re-stored.
    pub refresh: bool,
    /// Third-party apt repositories the selected features contribute
    /// ([`ResolvedBuild::apt_sources`]), each paired with the host
    /// path its `signed_by` keyring resolved to. Rendered into signed `deb` positionals
    /// so apt resolves an out-of-mirror app (e.g. Jellyfin) during the bootstrap solve.
    /// Empty when no feature adds one.
    pub apt_sources: &'a [AptRepo<'a>],
    /// Deterministic build timestamp (`SOURCE_DATE_EPOCH`, the locked kernel commit's
    /// committer date — the same lock-derived seed the image identifiers use), or
    /// `None` when the kernel tree is not available to read it (a partial rootfs-only
    /// build). When set it is the ceiling the tar export clamps every member's mtime
    /// to, and it is stamped onto the password-splice's appended `./etc/shadow`
    /// member, so only the deliberate per-image secret — not incidental build-time
    /// mtimes — varies between builds of one lock.
    pub source_date_epoch: Option<u64>,
}

/// The boot-method configuration the rootfs generates, for a method that needs the
/// *rootfs itself* to participate in booting.
///
/// `rockchip-rkbin` needs none: its bootloader is written to the raw gap by the image
/// node, and the in-rootfs half (the extlinux hooks) is static overlay files.
///
/// `depthcharge` is different in kind. The boot payload **is** the kernel, signed, and
/// it is built inside the rootfs by `depthchargectl` — so the rootfs has to be told
/// which board profile to sign for and what command line to bake in, and it has to be
/// told *before* the kernel package installs and triggers the whole chain.
#[derive(Debug, Clone, Copy)]
pub enum BootConfig<'a> {
    /// Configure `depthcharge-tools` inside the rootfs.
    Depthcharge {
        /// The board profile to sign for (`depthchargectl`'s `board` codename).
        board: &'a str,
        /// The kernel command line to bake into the signature, **without** `root=` —
        /// which `depthchargectl` derives from `/etc/fstab`, here and again on every
        /// on-device kernel upgrade.
        cmdline: &'a str,
        /// The compressor `mkinitramfs` builds this board's initramfs with, resolved
        /// from the kernel slot's size. It has to be in place before the kernel package
        /// is, or the first initramfs is built with the wrong one and thrown away.
        initramfs_compress: InitramfsCompress,
    },
}

/// A resolved third-party apt repository activated during the rootfs bootstrap solve:
/// a feature's [`AptSource`] paired with the host path its `signed_by`
/// keyring resolved to. The CLI resolves and existence-checks the keyring (a vendored
/// build-host prerequisite); the rootfs stage turns the pair into a signed provisioner
/// repository, so the repo's `Release` signature is verified against that keyring
/// during the solve rather than trusted blindly.
pub struct AptRepo<'a> {
    /// The resolved feature source (uri / suite / components / name / signed_by).
    pub source: &'a AptSource,
    /// Host path the source's `signed_by` keyring resolved to (CLI-verified to exist).
    pub keyring: PathBuf,
}

/// What [`build_rootfs`] produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RootfsArtifacts {
    /// The rootfs `tar` archive (device nodes excluded), consumed by the image
    /// node's ext4 formatter. [`DEFAULT_USER`]'s account is **locked** in it — the
    /// unique per-image first-boot password is spliced into the staged tree
    /// at image assembly, not into this shared, cacheable tarball.
    pub tar: PathBuf,
    /// The solved package manifest (`name version arch sha256` per line).
    pub manifest: PathBuf,
    /// The plan document: the install set *and* the archive state it resolved against,
    /// in the archive's own deb822 control format.
    ///
    /// The manifest beside it answers "which package bytes shipped"; this additionally
    /// answers "selected from what", and it is the form a later
    /// [`pinned_plan`](RootfsOptions::pinned_plan) replays. A `reproduce` run republishes
    /// the document it was given, byte for byte, rather than re-rendering the plan it
    /// parsed — see [`RootfsProvenance::plan_sha256`](boot2deb_core::provenance::RootfsProvenance::plan_sha256).
    ///
    /// What it contributes to the provenance manifest is read back off this file by
    /// [`read_plan_record`], not carried alongside it: the manifest describes the
    /// published document, so the digest it records must be the digest of what was
    /// published.
    pub plan: PathBuf,
}

/// Copy the layer overlay trees into `staging` (each existing dir, in order, via
/// `cp -a` so symlinks and the executable bit survive). Later layers win. The
/// caller normalizes the merged tree's modes with [`normalize_overlay_modes`].
///
/// `--remove-destination` is what makes "later layers win" hold for every file a
/// layer may legitimately ship. `cp` opens an existing destination for writing, so
/// overriding a file an earlier layer shipped without the owner-write bit — a key, a
/// `sudoers.d` drop-in — would fail with `Permission denied` instead of replacing it;
/// unlinking first sidesteps the destination's mode entirely.
fn copy_overlay_trees(
    staging: &Path,
    overlay_dirs: &[PathBuf],
    step: &Step,
) -> Result<(), EngineError> {
    let _ = std::fs::remove_dir_all(staging);
    std::fs::create_dir_all(staging).map_err(|s| EngineError::io(staging, s))?;
    for dir in overlay_dirs {
        if dir.exists() {
            let mut cmd = Command::new("cp");
            cmd.arg("-a")
                .arg("--remove-destination")
                .arg(format!("{}/.", dir.display()))
                .arg(staging);
            crate::build::run(cmd, "cp", &format!("stage overlay {}", dir.display()), step)?;
        }
    }
    Ok(())
}

/// Force every mode in a staged overlay tree to the mode the image must ship, so the
/// build host's umask cannot reach the rootfs: each directory to `0755`, each file to
/// `0755` if any execute bit is set and `0644` otherwise, symlinks left alone.
///
/// The rule is **git's own file model**, and that is what makes it lossless here. Git
/// records exactly two file modes (`100644` and `100755`) and records directory modes
/// not at all, so an overlay tree's checked-out modes are not authored data — they are
/// the developer's umask applied to git's two bits. Restating those bits is therefore
/// the identity function on everything the repository actually expresses, while
/// discarding the one thing it does not: under a `002` umask a checkout materializes
/// `0664`/`0775` files and `0775` directories, and a `cp -a` into the staging tree
/// followed by a mode-preserving copy into the rootfs would stamp a group-writable
/// `/etc`, `/usr`, and `/boot` into every image. Under `077` it would stamp `0700`
/// `/etc` and the image would not work at all.
///
/// It also covers the generated config: [`write_staged`] sets each file's own mode but
/// creates parent directories through `create_dir_all`, which applies the umask.
///
/// An overlay that needs a mode outside git's two — a `0440` sudoers drop-in, a `0700`
/// home — cannot express it in a git tree in the first place, and so belongs in the
/// customize script, which runs as root inside the cage. Applying this after the
/// merge is what keeps that boundary honest rather than accidental.
fn normalize_overlay_modes(root: &Path) -> Result<(), EngineError> {
    let meta = std::fs::symlink_metadata(root).map_err(|s| EngineError::io(root, s))?;
    if meta.file_type().is_symlink() {
        // A symlink's own mode is not consulted by the kernel, and `chmod` would
        // follow it and rewrite the target instead.
        return Ok(());
    }
    if meta.is_dir() {
        set_mode(root, 0o755)?;
        let mut children: Vec<PathBuf> = std::fs::read_dir(root)
            .map_err(|s| EngineError::io(root, s))?
            .map(|e| e.map(|e| e.path()).map_err(|s| EngineError::io(root, s)))
            .collect::<Result<_, _>>()?;
        // Deterministic recursion order (cosmetic; modes are order-independent).
        children.sort();
        for child in children {
            normalize_overlay_modes(&child)?;
        }
    } else {
        use std::os::unix::fs::PermissionsExt;
        // Any execute bit means git recorded `100755` — the hooks and first-boot
        // scripts, whose `+x` is load-bearing (the runner refuses a non-executable
        // hook). Everything else is `100644`.
        let exec = meta.permissions().mode() & 0o111 != 0;
        set_mode(root, if exec { 0o755 } else { 0o644 })?;
    }
    Ok(())
}

/// Force every modification time in a staged overlay tree to `epoch`, so the build
/// host's *checkout* time cannot reach the rootfs any more than its umask can
/// ([`normalize_overlay_modes`] is the same pass for the same reason).
///
/// A layer's `overlay/` files are merged with `cp -a`, which preserves their times, and
/// those times say when this working copy was cloned or last edited — a property of the
/// machine, not of the build. They matter because the tree is laid into the rootfs by
/// [`provision::CopyIn`](ferroday_cage::provision::CopyIn), which *does* preserve times,
/// and the tar export's clamp is `min(mtime, SOURCE_DATE_EPOCH)` — so a checkout older
/// than the epoch would ship its own mtime and two hosts would export different bytes.
/// Stamping the epoch here makes the clamp a no-op and the tree a function of the lock.
///
/// `None` is a rootfs-only build with no kernel tree to date, where the export clamps
/// nothing either; the tree keeps whatever times it has, which is the same amount of
/// determinism that build had to begin with.
///
/// Applied to symlinks too — `tar` records a symlink's own mtime — which is why this
/// does not go through `std::fs`: `filetime`-style helpers there follow the link and
/// would stamp its target instead.
fn normalize_overlay_times(root: &Path, epoch: Option<u64>) -> Result<(), EngineError> {
    let Some(epoch) = epoch else {
        return Ok(());
    };
    let secs = i64::try_from(epoch).unwrap_or(i64::MAX);
    stamp_times(root, secs)
}

/// Recursive worker for [`normalize_overlay_times`]: stamp `path`, then descend into it
/// when it is a real directory (never through a symlink, which would leave the tree and
/// stamp whatever it points at).
fn stamp_times(path: &Path, secs: i64) -> Result<(), EngineError> {
    let meta = std::fs::symlink_metadata(path).map_err(|s| EngineError::io(path, s))?;
    if meta.is_dir() && !meta.file_type().is_symlink() {
        for entry in std::fs::read_dir(path).map_err(|s| EngineError::io(path, s))? {
            let entry = entry.map_err(|s| EngineError::io(path, s))?;
            stamp_times(&entry.path(), secs)?;
        }
    }
    // The directory itself is stamped after its children, whose creation would
    // otherwise move its mtime back to now.
    set_times(path, secs)
}

/// Set one path's access and modification times to `secs`, without following a symlink.
fn set_times(path: &Path, secs: i64) -> Result<(), EngineError> {
    use std::os::unix::ffi::OsStrExt;
    let c_path = std::ffi::CString::new(path.as_os_str().as_bytes()).map_err(|_| {
        EngineError::io(path, std::io::Error::from(std::io::ErrorKind::InvalidInput))
    })?;
    let times = [
        libc::timespec {
            tv_sec: secs,
            tv_nsec: 0,
        },
        libc::timespec {
            tv_sec: secs,
            tv_nsec: 0,
        },
    ];
    // SAFETY: `c_path` is a NUL-terminated path owned for the duration of the call, and
    // `times` is a two-element array as `utimensat` requires.
    let rc = unsafe {
        libc::utimensat(
            libc::AT_FDCWD,
            c_path.as_ptr(),
            times.as_ptr(),
            libc::AT_SYMLINK_NOFOLLOW,
        )
    };
    if rc == 0 {
        Ok(())
    } else {
        Err(EngineError::io(path, std::io::Error::last_os_error()))
    }
}

/// Merge the layer `overlay-pre/` trees into `staging` and write the boot method's
/// generated pre-install config into it — the tree the essential hook lays into the
/// rootfs **before any package is configured**.
///
/// Only config that a package's own maintainer scripts must *see while they run*
/// belongs here. On a depthcharge board that is `/etc/depthcharge-tools/config` and
/// `/etc/kernel/cmdline`, and the reason is not tidiness:
///
///  - `depthcharge-tools`' kernel hook re-signs and re-writes a ChromeOS kernel
///    partition. With no config present it runs at its defaults and goes looking for
///    that partition on **the build host's** block devices. `enable-system-hooks =
///    False` must therefore be in place before the package is.
///  - `/etc/kernel/cmdline` — not `kernel-cmdline` in the depthcharge config, which is
///    read through a `ConfigParser` whose interpolation rejects a raw `%`. This file is
///    read with a plain `read_text()` + `shlex.split()`, so it is the one place a
///    cmdline can safely live.
///
/// The localization config is here for the same reason, and it is the difference
/// between an image that merely *has* a locale and one that can be *re-configured* to
/// another. Debian's `locales`, `keyboard-configuration`, and `tzdata` all seed their
/// debconf answers from these exact files when they configure: `locales` reads
/// `/etc/locale.gen` (and `/etc/locale.conf` for the current `LANG`) and runs
/// `locale-gen` over what it finds; `keyboard-configuration` reads
/// `/etc/default/keyboard`; `tzdata` `readlink`s `/etc/localtime`. Laid in *first*,
/// they are adopted — the installed files, the debconf database, and the `console-setup`
/// cached keymap all agree, so `dpkg-reconfigure` on the running board opens on the
/// image's real values. Written *after* the packages instead, the files would be right
/// and debconf would still hold Debian's defaults.
fn stage_preinstall_overlay(
    staging: &Path,
    overlay_dirs: &[PathBuf],
    build: &ResolvedBuild,
    boot: Option<BootConfig>,
    source_date_epoch: Option<u64>,
    step: &Step,
) -> Result<(), EngineError> {
    copy_overlay_trees(staging, overlay_dirs, step)?;
    if let Some(BootConfig::Depthcharge {
        board,
        cmdline,
        initramfs_compress,
    }) = boot
    {
        write_staged(
            staging,
            "etc/depthcharge-tools/config",
            &config::depthcharge_config(board, false),
        )?;
        write_staged(staging, "etc/kernel/cmdline", &format!("{cmdline}\n"))?;
        write_staged(
            staging,
            "etc/initramfs-tools/conf.d/depthcharge.conf",
            &config::depthcharge_initramfs_conf(initramfs_compress),
        )?;
    }

    write_staged(
        staging,
        "etc/locale.conf",
        &config::locale_conf(&build.locale),
    )?;
    write_staged(
        staging,
        "etc/locale.gen",
        &config::locale_gen(&build.locales_generate),
    )?;
    // The zone is the symlink and nothing else — see `config::localtime_target`.
    symlink_staged(
        staging,
        "etc/localtime",
        &config::localtime_target(&build.timezone),
    )?;
    // Only a board with a keyboard writes one. On a headless board the file is absent
    // and `keyboard-configuration` installs its own default, which is the honest
    // outcome: nothing here knows better than Debian what layout an unused console has.
    if let Some(keymap) = &build.keymap {
        write_staged(staging, "etc/default/keyboard", &config::keyboard(keymap))?;
    }
    // Same rule as the keymap: configure nothing when nothing is configured. An empty
    // list is not "no time source" — it is Debian's compiled-in pool, and writing an
    // empty `NTP=` would say the opposite.
    if !build.ntp_servers.is_empty() {
        write_staged(
            staging,
            "etc/systemd/timesyncd.conf.d/10-boot2deb.conf",
            &config::timesyncd_conf(&build.ntp_servers),
        )?;
    }

    normalize_overlay_modes(staging)?;
    normalize_overlay_times(staging, source_date_epoch)?;
    step.log(format!(
        "staged pre-install overlay at {} (laid in before any package)",
        staging.display()
    ));
    Ok(())
}

/// Merge the layer `overlay/` trees into `staging` (each existing dir, in order,
/// via `cp -a` so symlinks and the executable bit survive), then write the
/// *generated* config into it and normalize every mode and modification time
/// ([`normalize_overlay_modes`], [`normalize_overlay_times`]) so neither the build
/// host's umask nor its checkout time reaches the image. Later layers and the generated
/// config win.
fn stage_overlay(
    staging: &Path,
    overlay_dirs: &[PathBuf],
    build: &ResolvedBuild,
    rootfs_partuuid: uuid::Uuid,
    image_identity: &boot2deb_core::provenance::SystemIdentity,
    source_date_epoch: Option<u64>,
    step: &Step,
) -> Result<(), EngineError> {
    copy_overlay_trees(staging, overlay_dirs, step)?;
    // Generated config, mirroring rootfs paths.
    write_staged(staging, "etc/fstab", &config::fstab(build, rootfs_partuuid))?;
    // Only written when the build declares volumes: an image with none should not
    // ship a config file suggesting the mechanism is live.
    if !build.data_volumes.is_empty() {
        write_staged(
            staging,
            boot2deb_core::datavolume::CONFIG_PATH,
            &boot2deb_core::datavolume::render_config(&build.data_volumes),
        )?;
    }
    write_staged(staging, "etc/hostname", &config::hostname(&build.hostname))?;
    write_staged(staging, "etc/hosts", &config::hosts(&build.hostname))?;
    write_staged(
        staging,
        "etc/apt/sources.list",
        &config::apt_sources(build.image_suite(), crate::bootstrap::components(build)),
    )?;
    write_staged(staging, "etc/kernel-img.conf", &config::kernel_img_conf())?;
    // Two files that exist because the build host is not the board. `dhcpcd` cannot
    // start without a `/etc/resolv.conf` to bind, and `update-initramfs` — running here,
    // against a disk that does not exist yet — otherwise resolves its resume device and
    // its fsck helper by probing this host. See each generator for what goes wrong.
    write_staged(staging, "etc/resolv.conf", &config::resolv_conf())?;
    write_staged(
        staging,
        "etc/initramfs-tools/conf.d/boot2deb.conf",
        // From the image node's own declaration of what it formats, so the helper the
        // initramfs carries is the one the filesystem the image node writes needs.
        &config::initramfs_conf(crate::image::ROOTFS_FS_KIND),
    )?;
    // Board boot params the kernel postinst.d/postrm.d hooks + mk_extlinux source,
    // so the boot-method overlay scripts stay board-agnostic (driven by the
    // device's kernel_dtb) rather than hardcoding one board's dtb name.
    write_staged(
        staging,
        "etc/boot2deb/board.conf",
        &config::board_conf(&build.kernel_dtb, &build.kernel_cmdline),
    )?;
    // The image's own account of what it is, beside the board config, for a tool that
    // reads this disk from outside — from other media, without mounting it, on a machine
    // that may not be this board. Everything in it but the depthcharge board profile is a
    // cross-check against what such a reader can already infer from the disk; the board
    // profile is the part it cannot.
    write_staged(
        staging,
        "etc/boot2deb/image.toml",
        &image_identity.to_toml_string()?,
    )?;
    // Empty machine-id → systemd regenerates it on first boot.
    write_staged(staging, "etc/machine-id", "")?;
    // The sudoers drop-in is written by the customize-hook directly into the chroot,
    // not staged here: at mode 0440 it would be unreadable to the hook's mapped uid
    // when it copies the overlay in.
    normalize_overlay_modes(staging)?;
    normalize_overlay_times(staging, source_date_epoch)?;
    step.log(format!(
        "staged overlay + generated config at {}",
        staging.display()
    ));
    Ok(())
}

/// Write `content` to `staging/<rel>` at mode `0644`, creating parent dirs. The
/// explicit mode keeps generated `/etc` config reproducible regardless of the
/// build host's umask (a `002` umask would otherwise leave it group-writable);
/// the parent directories `create_dir_all` makes are covered by the staging
/// tree's closing [`normalize_overlay_modes`] pass, which the umask reaches the
/// same way.
fn write_staged(staging: &Path, rel: &str, content: &str) -> Result<(), EngineError> {
    let path = staging.join(rel);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|s| EngineError::io(parent, s))?;
    }
    std::fs::write(&path, content).map_err(|s| EngineError::io(&path, s))?;
    set_mode(&path, 0o644)
}

/// Create `staging/<rel>` as a symlink to `target`, replacing whatever is there.
///
/// The overlay copy preserves symlinks (`cp -dR`), so the link — not a copy of what it
/// points at — is what lands in the rootfs; the cache key fingerprints it by its target
/// ([`crate::rootcache::dir_fingerprints`]), so re-pointing it rebuilds.
fn symlink_staged(staging: &Path, rel: &str, target: &str) -> Result<(), EngineError> {
    let path = staging.join(rel);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|s| EngineError::io(parent, s))?;
    }
    // A staged tree is rebuilt each run, but an overlay may have shipped a file here.
    let _ = std::fs::remove_file(&path);
    std::os::unix::fs::symlink(target, &path).map_err(|s| EngineError::io(&path, s))
}

/// Set the unix mode of `path`.
fn set_mode(path: &Path, mode: u32) -> Result<(), EngineError> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(mode))
        .map_err(|s| EngineError::io(path, s))
}

/// Modules that must end up **inside the built initramfs** of a depthcharge board,
/// asserted after it is built and before it is signed.
///
/// This is not a general list — it is the set whose absence was each, at some point, a
/// board that booted to a white screen and said nothing:
///  - `i2c-rk3x` + `rk808-regulator` — the SD slot's power rails are RK808 LDOs, and
///    they are *device-tree* dependencies, so nothing pulls them in automatically;
///    without them the MMC controller defers its probe forever and root never appears.
///  - `dw_mmc-rockchip` — the MMC controller itself.
///  - `ext4` — the root filesystem.
///  - `spi-rockchip` — the keyboard (the EC is on SPI), so a rescue shell has input.
///    A rescue shell with no keyboard is indistinguishable from a hang.
const REQUIRED_INITRD_MODULES: &[&str] = &[
    "dw_mmc-rockchip",
    "ext4",
    "i2c-rk3x",
    "rk808-regulator",
    "spi-rockchip",
];

/// Members every finished rootfs tarball must contain, checked by [`validate_tar`].
/// `etc/shadow` is written late (the account is created there), so its presence
/// proves the archive is readable through to its end (not truncated);
/// `etc/os-release` and `etc/fstab` confirm the archive is a real Debian rootfs
/// rather than an unrelated or empty tar. Named without a leading `./` and matched
/// against a listing normalized the same way, so the check states the paths as the
/// rootfs sees them rather than as one tar writer happens to spell them.
const REQUIRED_TAR_MEMBERS: &[&str] = &["etc/os-release", "etc/fstab", "etc/shadow"];

/// Validate that `tarball` is a complete, readable rootfs archive before the image
/// stage formats it into ext4. Lists the archive end-to-end (`tar tf`, which
/// errors on a truncated archive) and confirms every `REQUIRED_TAR_MEMBERS` entry is
/// present (including the still-locked `./etc/shadow`). A partial tar left by an
/// interrupted bootstrap fails here with a "re-run rootfs" pointer, rather than being
/// silently formatted into a broken image by an `--stage image` retry whose gate only
/// checked that the file existed.
pub fn validate_tar(tarball: &Path) -> Result<(), EngineError> {
    let out = Command::new("tar")
        .arg("-tf")
        .arg(tarball)
        .output()
        .map_err(|source| EngineError::CommandSpawn {
            command: "tar".into(),
            context: "validate rootfs tarball".into(),
            source,
        })?;
    if !out.status.success() {
        return Err(EngineError::CommandFailed {
            command: "tar".into(),
            context: format!("validate rootfs tarball {}", tarball.display()),
            status: out.status.code(),
            stderr: String::from_utf8_lossy(&out.stderr).trim().to_string(),
        });
    }
    let listing = String::from_utf8_lossy(&out.stdout);
    // The export writes `./`-prefixed members (`./etc/os-release`); strip that prefix
    // so the comparison is against the path the rootfs sees, whatever the archive's
    // spelling.
    let members: std::collections::HashSet<&str> = listing
        .lines()
        .map(|l| l.trim().trim_start_matches("./"))
        .collect();
    for required in REQUIRED_TAR_MEMBERS {
        if !members.contains(required) {
            return Err(EngineError::ArtifactMissing {
                what: format!("member {required} in rootfs tarball (incomplete tar?)"),
                location: tarball.display().to_string(),
            });
        }
    }
    Ok(())
}

/// Generated rootfs config files, rendered from resolved values. Pure —
/// each returns the exact file content — so the config is unit-testable.
mod config {
    use boot2deb_core::model::{
        InitramfsCompress, Keymap, ResolvedBoot, ResolvedBuild, CONSOLE_LOGLEVEL_ARG,
    };
    use std::fmt::Write;
    use uuid::Uuid;

    /// `/etc/fstab`. Both boot methods root on the **PARTUUID** the image node stamps
    /// into the GPT ([`ImageIdentity::rootfs_partuuid`](crate::image::ImageIdentity)),
    /// derived up front and threaded through both nodes so this entry always names the
    /// partition the image will actually write. The value is the device's boot
    /// identity for its whole life: nothing on the device rewrites it (first-boot
    /// grows the partition but keeps its PARTUUID), so the references that carry it —
    /// this file, the extlinux cmdline, the signed depthcharge kernel — never go
    /// stale. The ext4 label and filesystem UUID still exist (the label is handy for
    /// rescue mounts) but nothing boots by them.
    ///
    /// Per-method notes:
    ///
    ///  - `rockchip-rkbin`: the `mk_extlinux` hook reads root back out of here to
    ///    build the bootloader's cmdline on every kernel install.
    ///
    ///  - `depthcharge`: this file is load-bearing for the boot itself —
    ///    `depthchargectl` reads it to derive the `root=` it bakes into the kernel's
    ///    *signature*, at image build and again on every on-device kernel upgrade. A
    ///    label would work for the kernel but not for the tool: it resolves root from
    ///    fstab and strips any `root=` that disagrees, so whatever is here is what
    ///    gets signed.
    pub fn fstab(build: &ResolvedBuild, rootfs_partuuid: Uuid) -> String {
        let (source, note) = match &build.boot {
            ResolvedBoot::RockchipRkbin(_) => (
                format!("PARTUUID={}", rootfs_partuuid.hyphenated()),
                "# regenerate extlinux.conf via /boot/mk_extlinux after editing the root entry",
            ),
            ResolvedBoot::Depthcharge(_) => (
                format!("PARTUUID={}", rootfs_partuuid.hyphenated()),
                "# depthchargectl derives the signed kernel's root= from this line; after\n\
                 # editing it, re-sign with `depthchargectl write --allow-current`",
            ),
        };
        // Data volumes follow root, mounted by LABEL and with `nofail`, so a board
        // whose data disk is absent or slow to enumerate still boots. The
        // first-boot hook creates or adopts the volume these lines name; the lines
        // themselves are here at build time so the mount survives every later boot
        // without the hook, which runs exactly once.
        let data: String = build
            .data_volumes
            .iter()
            .map(|v| format!("{}\n", v.fstab_line()))
            .collect();
        format!(
            "{note}\n\
             # <device>\t<mount>\t<type>\t<options>\t\t<dump> <pass>\n\
             {source}\t/\text4\terrors=remount-ro\t0      1\n\
             {data}"
        )
    }

    /// `/etc/depthcharge-tools/config` — which board profile to sign for, and whether
    /// the package's kernel hooks are live.
    ///
    /// `enable-system-hooks` is the safety switch, and it is written **False at build
    /// time** and flipped True at the end. The hook it gates runs `depthchargectl
    /// write`, which hunts the *host's* block devices for a ChromeOS kernel partition
    /// — harmless when there is none, and not harmless at all when the operator
    /// happens to have the target SD card plugged in while building.
    ///
    /// In the shipped image it must be `True`, or an `apt` kernel upgrade would leave
    /// the signed partition holding the old kernel while the filesystem moved on.
    pub fn depthcharge_config(board: &str, enable_system_hooks: bool) -> String {
        let enabled = if enable_system_hooks { "True" } else { "False" };
        format!(
            "# Generated by boot2deb.\n\
             [depthcharge-tools]\n\
             enable-system-hooks = {enabled}\n\
             \n\
             [depthchargectl]\n\
             board = {board}\n"
        )
    }

    /// `/etc/initramfs-tools/conf.d/depthcharge.conf` — the two initramfs settings a
    /// signed-payload board has to state outright.
    ///
    /// Generated rather than shipped as an overlay file because the compressor is not a
    /// free choice: it follows from the kernel slot's size
    /// ([`InitramfsCompress`](boot2deb_core::model::InitramfsCompress)), and a static
    /// file would make every board take the narrowest board's answer.
    ///
    /// A drop-in, not `/etc/initramfs-tools/initramfs.conf`, which is a conffile:
    /// writing that before the package unpacks makes dpkg prompt about a
    /// locally-modified file. `mkinitramfs` reads `conf.d/*` unconditionally, so a
    /// drop-in has the same effect and no packaging conflict.
    ///
    /// `MODULES=list`, not `dep`, for two reasons and the second is the sharp edge:
    ///
    ///  - Budget. A `MODULES=most` initramfs does not fit under the payload ceiling once
    ///    the kernel image has taken its share.
    ///  - Correctness under cross-build. `MODULES=dep` guesses from the *building*
    ///    system's mounted `/sys` and `/`, so in an armhf rootfs on an x86_64 host it
    ///    resolves the host's root device and produces an initramfs with none of the
    ///    drivers the board needs. It is only meaningful when built on the target; an
    ///    explicit list is deterministic and works in both places.
    ///
    /// The list itself is a config-layer drop-in under
    /// `usr/share/initramfs-tools/modules.d/`, so which modules a board carries stays
    /// with the board.
    pub fn depthcharge_initramfs_conf(compress: InitramfsCompress) -> String {
        format!(
            "# Generated by boot2deb.\n\
             MODULES=list\n\
             COMPRESS={}\n",
            compress.as_str()
        )
    }

    /// `/etc/hostname`.
    pub fn hostname(h: &str) -> String {
        format!("{h}\n")
    }

    /// `/etc/hosts` with the loopback + a `127.0.1.1` entry for the hostname.
    pub fn hosts(h: &str) -> String {
        format!(
            "127.0.0.1\tlocalhost\n127.0.1.1\t{h}\n\
             ::1\tlocalhost ip6-localhost ip6-loopback\nff02::1\tip6-allnodes\nff02::2\tip6-allrouters\n"
        )
    }

    /// `/etc/apt/sources.list` for `suite` over `components`, one line per pocket the
    /// suite actually publishes.
    ///
    /// `components` is the set this image was *provisioned* from, so what the booted
    /// board can install matches what the build could: a libre image, whose kernel
    /// loads no blob, does not offer `non-free-firmware` on the console either.
    ///
    /// The pocket set comes from [`suite::pockets`](boot2deb_core::suite::pockets)
    /// rather than a `{suite}-security`/`{suite}-updates` format string, because it
    /// is a property of the suite: unstable has neither, and emitting them regardless
    /// shipped a bootable image whose every `apt update` errored on two 404s.
    ///
    /// Always the canonical `deb.debian.org` — the build-time `--mirror` override only
    /// redirects the bootstrap *fetch*, not the sources the shipped image points its
    /// `apt` at, so a device updates from the official mirror regardless of which
    /// mirror built it. Plain `http://` is standard Debian practice: apt verifies each
    /// `Release` signature against the device's archive keyring, so the transport
    /// carries no integrity burden.
    pub fn apt_sources(suite: &str, components: &str) -> String {
        // The provisioner takes its components comma-separated; a sources.list line
        // wants them space-separated.
        let components = components.replace(',', " ");
        boot2deb_core::suite::pockets(suite)
            .iter()
            .map(|p| {
                format!(
                    "deb http://deb.debian.org/{} {} {components}\n",
                    p.archive, p.suite
                )
            })
            .collect()
    }

    /// `/etc/locale.conf` — the system `LANG`.
    ///
    /// **Not** `/etc/default/locale`, which Debian makes a symlink to this file and
    /// `systemd-tmpfiles` re-asserts with a *forcing* rule (`L+`) on every boot: a
    /// regular file written there is deleted and replaced by the symlink, so an image
    /// that put its `LANG` in `/etc/default/locale` would come up with no locale at
    /// all. Writing the symlink's target instead satisfies every reader — `pam_env`
    /// through the symlink, `systemd`/`localectl` directly, and the `locales` package,
    /// whose config script reads this exact path to learn the current default.
    pub fn locale_conf(locale: &str) -> String {
        format!("LANG={locale}\n")
    }

    /// `/etc/locale.gen` — one `<name> <codeset>` line per locale the image compiles.
    ///
    /// Laid in *before* `locales` installs, so its config script adopts these as the
    /// selected set and its postinst runs `locale-gen` over them as part of the normal
    /// install. The package then appends the full commented catalogue below them, which
    /// is what `dpkg-reconfigure locales` offers on the running board.
    pub fn locale_gen(locales: &[String]) -> String {
        let mut s = String::new();
        for locale in locales {
            // Resolution rejects a locale with no codeset, so this cannot be `None`.
            let codeset = boot2deb_core::locale_codeset(locale).unwrap_or("UTF-8");
            let _ = writeln!(s, "{locale} {codeset}");
        }
        s
    }

    /// `/etc/default/keyboard` — the console keyboard layout.
    ///
    /// Laid in before `keyboard-configuration` installs, which is what makes it stick:
    /// that package's config script seeds its debconf answers from this file, so the
    /// installed system, its debconf state, and the `console-setup` cached keymap all
    /// agree — and a later `dpkg-reconfigure keyboard-configuration` opens on the right
    /// current values rather than Debian's defaults.
    pub fn keyboard(keymap: &Keymap) -> String {
        format!(
            "# Generated by boot2deb. Consult the keyboard(5) manual page.\n\
             XKBMODEL=\"{model}\"\n\
             XKBLAYOUT=\"{layout}\"\n\
             XKBVARIANT=\"{variant}\"\n\
             XKBOPTIONS=\"{options}\"\n\
             \n\
             BACKSPACE=\"guess\"\n",
            model = keymap.model,
            layout = keymap.layout,
            variant = keymap.variant,
            options = keymap.options,
        )
    }

    /// The `/etc/localtime` symlink target for `timezone`.
    ///
    /// The symlink is the whole interface: forky's `tzdata` **deletes** `/etc/timezone`
    /// on configure ("Removing now unused /etc/timezone"), and reads the zone back by
    /// `readlink`-ing this symlink — so writing that file would be worse than
    /// redundant. `systemd`/`timedatectl` read the symlink too.
    pub fn localtime_target(timezone: &str) -> String {
        format!("/usr/share/zoneinfo/{timezone}")
    }

    /// `/etc/systemd/timesyncd.conf.d/10-boot2deb.conf` — the NTP servers the image
    /// reaches for first.
    ///
    /// Sets `NTP=` and deliberately leaves `FallbackNTP=` alone. Debian compiles its
    /// pool into that fallback, and `timesyncd` consults it whenever the primary list
    /// yields nothing — so writing only the primary makes a configured server a
    /// preference that degrades to the pool, where replacing the fallback would strand
    /// an image the moment it booted anywhere else.
    ///
    /// A drop-in rather than an edit of `timesyncd.conf`: that file is a `systemd`
    /// conffile, and rewriting it would make every future systemd upgrade prompt about
    /// a modified conffile on a running board.
    ///
    /// Resolution guarantees each entry is whitespace-free, which is what makes the
    /// space-separated join unambiguous.
    pub fn timesyncd_conf(servers: &[String]) -> String {
        format!(
            "# Generated by boot2deb. Consult the timesyncd.conf(5) manual page.\n\
             #\n\
             # FallbackNTP is deliberately not set here: Debian compiles its pool in as\n\
             # the fallback, so the servers below are tried first and the pool still\n\
             # covers this image on a network where they cannot be reached.\n\
             [Time]\n\
             NTP={servers}\n",
            servers = servers.join(" ")
        )
    }

    /// `/etc/kernel-img.conf` — install kernels into `/boot` without symlinks, as
    /// the extlinux boot flow expects.
    pub fn kernel_img_conf() -> String {
        "link_in_boot = 1\ndo_symlinks = 0\n".to_string()
    }

    /// `/etc/resolv.conf` — the file `dhcpcd` rewrites once it holds a lease.
    ///
    /// It carries no nameserver, because the network the board will join is not a thing
    /// the build host knows. What the image needs is that the **path exists**: Debian's
    /// `dhcpcd.service` runs under `ProtectSystem=strict` and names `/etc/resolv.conf`
    /// among its `ReadWritePaths=`, and systemd refuses to set up a mount namespace for
    /// a path that is not there. Without this file DHCP fails at `226/NAMESPACE` before
    /// `dhcpcd` runs at all, and the board comes up with no network.
    ///
    /// Nothing else in the image would create it: no Debian package ships
    /// `/etc/resolv.conf`, and the image installs neither `resolvconf` nor
    /// `systemd-resolved`, so `dhcpcd`'s own hook is the sole writer. That hook
    /// truncates and rewrites this path in place, which is what makes a file staged
    /// here — rather than a symlink into `/run` — the shape that works under the unit's
    /// read-write bind.
    pub fn resolv_conf() -> String {
        "# Rewritten by dhcpcd from the DHCP lease.\n\
         # Fixed entries belong in /etc/resolv.conf.head or /etc/resolv.conf.tail,\n\
         # which dhcpcd preserves across that rewrite.\n"
            .to_string()
    }

    /// `/etc/initramfs-tools/conf.d/boot2deb.conf` — the two initramfs settings an image
    /// has to state outright, because `update-initramfs` runs on the build host while
    /// the hardware it is building for is absent, and both defaults resolve by probing
    /// whatever is in front of them.
    ///
    /// `RESUME=none`: the image is one ext4 root partition with no swap, so there is
    /// nothing to resume from. Left unset, the resume hook auto-detects a swap device and
    /// finds the **build host's**, writing that host's device path into the image; the
    /// board then retries it for about thirty seconds every boot before giving up.
    ///
    /// `FSTYPE`: the fsck hook reads `FSTYPE=auto` as an instruction to resolve the root
    /// device named in `/etc/fstab` and probe it for its type — and that is a `PARTUUID`
    /// belonging to a disk the image has not been written to yet, so the probe finds
    /// nothing and the initramfs ships with no `fsck` at all, leaving the root filesystem
    /// unchecked on every boot. Naming the type skips the probe. It selects which helper
    /// is installed and nothing more: at boot the root filesystem's type is read from the
    /// device itself.
    pub fn initramfs_conf(fstype: &str) -> String {
        format!("RESUME=none\nFSTYPE={fstype}\n")
    }

    /// `/etc/boot2deb/board.conf` — board boot parameters the boot-method overlay
    /// scripts (`/etc/kernel/postinst.d` + `postrm.d` hooks and `/boot/mk_extlinux`)
    /// source, so those stay board-agnostic instead of hardcoding one board's dtb.
    /// Derived from the device's resolved `kernel_dtb`: `DTB_PATH` (relative to the
    /// DT output dir) locates the dtb inside the installed `linux-image` package,
    /// and `DTB_NAME` (its basename) names the copy placed in `/boot`.
    ///
    /// `EXTL_CMD_LINE` carries the arguments `mk_extlinux` writes into the boot
    /// entry: `rootwait`, then the base console gate
    /// ([`CONSOLE_LOGLEVEL_ARG`]), then any extra arguments the board asked for
    /// ([`ResolvedBuild::kernel_cmdline`]). It overrides `mk_extlinux`'s own
    /// `rootwait` default — board.conf is sourced after that default, so the
    /// assignment must carry `rootwait` itself. The board's arguments come last so a
    /// board can override the gate. Resolution guarantees the value is safe to embed
    /// in this double-quoted, shell-sourced assignment.
    pub fn board_conf(kernel_dtb: &str, kernel_cmdline: &str) -> String {
        let name = kernel_dtb.rsplit('/').next().unwrap_or(kernel_dtb);
        let mut args = format!("rootwait {CONSOLE_LOGLEVEL_ARG}");
        if !kernel_cmdline.is_empty() {
            args.push(' ');
            args.push_str(kernel_cmdline);
        }
        format!(
            "# Generated by boot2deb -- board boot parameters. Do not edit.\n\
             # Sourced by /etc/kernel/{{postinst,postrm}}.d hooks and /boot/mk_extlinux.\n\
             DTB_PATH=\"{kernel_dtb}\"\n\
             DTB_NAME=\"{name}\"\n\
             EXTL_CMD_LINE=\"{args}\"\n"
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use boot2deb_core::{resolve_recipe, ConfigRoot, Overrides};

    fn repo_root() -> ConfigRoot {
        ConfigRoot::new(
            std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .ancestors()
                .nth(2)
                .unwrap()
                .to_path_buf(),
        )
    }

    fn rk1() -> ResolvedBuild {
        // The media-accel build: these rootfs tests assert the bootstrap includes the
        // feature packages (ffmpeg-rk et al.), so they need the userspace-carrying recipe.
        resolve_recipe(
            &repo_root(),
            "turing-rk1/media-accel-forky",
            &Overrides::default(),
        )
        .unwrap()
    }

    /// A lock with nothing pinned. These tests exercise how the rootfs node *stages* the
    /// identity document, not what it contains — the contents are unit-tested where they
    /// are assembled, in `core::provenance`.
    fn empty_lock() -> boot2deb_core::lock::Lock {
        boot2deb_core::lock::Lock {
            kernel: None,
            patches: None,
            uboot: None,
            uboot_patches: None,
            userspace: None,
            ffmpeg: None,
            rootfs: Some(boot2deb_core::lock::RootfsPin {
                suite: "forky".into(),
                manifest: "m.pkgs.lock".into(),
                manifest_sha256: None,
            }),
            blobs: None,
            kmods: vec![],
            extra_debs: vec![],
            snapshot: None,
        }
    }

    /// The `/etc/boot2deb/image.toml` document for a build, for the `RootfsOptions`
    /// fixtures below.
    fn ident(build: &ResolvedBuild) -> boot2deb_core::provenance::SystemIdentity {
        boot2deb_core::provenance::system_identity(build, &empty_lock())
    }

    /// The staged tree's modes are the image's modes, and they must not depend on the
    /// umask the build ran under.
    ///
    /// Built at a `002` umask — the Ubuntu/Pop!_OS default, where a git checkout
    /// materializes `0664` files and `0775` directories — the tree normalizes to the
    /// two modes git can express, with the executable bit and the symlink intact. The
    /// `077` case is the one that would ship an unusable image (`/etc` at `0700`, so
    /// no non-root process could read `/etc/passwd`), so it is asserted too.
    #[test]
    fn staged_modes_do_not_follow_the_build_host_umask() {
        use std::os::unix::fs::PermissionsExt;

        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("overlay");
        std::fs::create_dir_all(root.join("etc/boot2deb/first-boot.d")).unwrap();
        // Group-writable throughout, as `cp -a` from a umask-002 checkout leaves it.
        let plain = root.join("etc/hostname");
        std::fs::write(&plain, "board\n").unwrap();
        std::fs::set_permissions(&plain, std::fs::Permissions::from_mode(0o664)).unwrap();
        let hook = root.join("etc/boot2deb/first-boot.d/20-network");
        std::fs::write(&hook, "#!/bin/sh\n").unwrap();
        std::fs::set_permissions(&hook, std::fs::Permissions::from_mode(0o775)).unwrap();
        let link = root.join("etc/localtime");
        std::os::unix::fs::symlink("/usr/share/zoneinfo/UTC", &link).unwrap();
        for dir in ["etc", "etc/boot2deb", "etc/boot2deb/first-boot.d"] {
            std::fs::set_permissions(root.join(dir), std::fs::Permissions::from_mode(0o775))
                .unwrap();
        }
        // The `077` shape, on one directory: `/etc` unreadable to every non-root process.
        std::fs::create_dir(root.join("usr")).unwrap();
        std::fs::set_permissions(root.join("usr"), std::fs::Permissions::from_mode(0o700)).unwrap();

        normalize_overlay_modes(&root).unwrap();

        let mode = |p: &Path| p.symlink_metadata().unwrap().permissions().mode() & 0o7777;
        for dir in [
            "",
            "etc",
            "etc/boot2deb",
            "etc/boot2deb/first-boot.d",
            "usr",
        ] {
            assert_eq!(mode(&root.join(dir)), 0o755, "directory {dir:?}");
        }
        assert_eq!(mode(&plain), 0o644, "a non-executable file is 0644");
        assert_eq!(mode(&hook), 0o755, "an executable hook keeps its +x");
        // The link's own mode is untouched, and it still points where it did — a
        // `chmod` through the link would have rewritten its target instead.
        assert!(link.symlink_metadata().unwrap().file_type().is_symlink());
        assert_eq!(
            std::fs::read_link(&link).unwrap(),
            Path::new("/usr/share/zoneinfo/UTC")
        );
    }

    /// A staged overlay's modification times are the lock's, not the checkout's.
    ///
    /// This is load-bearing rather than cosmetic. The tree is laid into the rootfs by a
    /// copy that *preserves* times, and the tar export clamps each member to
    /// `min(mtime, SOURCE_DATE_EPOCH)` — so a working copy older than the epoch would
    /// ship its own mtimes and two hosts building one lock would export different bytes.
    /// The symlink is the case that needs the raw `utimensat`: a helper that followed the
    /// link would stamp its target and leave the link's own mtime — which `tar` records —
    /// at whatever the checkout gave it.
    #[test]
    fn a_staged_overlay_is_stamped_with_the_lock_epoch() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("overlay");
        std::fs::create_dir_all(root.join("etc/kernel")).unwrap();
        let file = root.join("etc/hostname");
        std::fs::write(&file, "board\n").unwrap();
        let link = root.join("etc/localtime");
        std::os::unix::fs::symlink("/usr/share/zoneinfo/UTC", &link).unwrap();

        const EPOCH: u64 = 1_700_000_000;
        normalize_overlay_times(&root, Some(EPOCH)).unwrap();

        let mtime = |p: &Path| {
            use std::os::unix::fs::MetadataExt;
            p.symlink_metadata().unwrap().mtime()
        };
        for path in [
            root.as_path(),
            &root.join("etc"),
            &root.join("etc/kernel"),
            &file,
            &link,
        ] {
            assert_eq!(mtime(path), EPOCH as i64, "{}", path.display());
        }
        // The link's target was not touched — the stamp went to the link itself.
        assert!(link.symlink_metadata().unwrap().file_type().is_symlink());

        // A rootfs-only build has no kernel tree to date, so nothing is stamped and the
        // tree keeps the determinism it already had — which is none either way.
        let before = mtime(&file);
        normalize_overlay_times(&root, None).unwrap();
        assert_eq!(mtime(&file), before);
    }

    /// "Later layers win" has to hold for every file a layer may legitimately ship,
    /// including one with no owner-write bit — a key, a `sudoers.d` drop-in. `cp` opens
    /// an existing destination for writing, so without `--remove-destination` a device
    /// overriding such a file from its SoC layer fails the whole build with
    /// `Permission denied`, and the layering contract silently has an exception in it.
    #[test]
    fn a_later_layer_overrides_a_read_only_file() {
        use std::os::unix::fs::PermissionsExt;

        let tmp = tempfile::tempdir().unwrap();
        let base = tmp.path().join("base");
        let device = tmp.path().join("device");
        std::fs::create_dir_all(base.join("etc/ssh")).unwrap();
        std::fs::create_dir_all(device.join("etc/ssh")).unwrap();
        let key = base.join("etc/ssh/ssh_host_ed25519_key");
        std::fs::write(&key, "base key\n").unwrap();
        std::fs::set_permissions(&key, std::fs::Permissions::from_mode(0o400)).unwrap();
        std::fs::write(device.join("etc/ssh/ssh_host_ed25519_key"), "device key\n").unwrap();

        let staging = tmp.path().join("staging");
        let sink = |_: crate::event::Event| {};
        let step = Step::start(&sink, "overlay");
        copy_overlay_trees(&staging, &[base, device], &step).unwrap();

        assert_eq!(
            std::fs::read_to_string(staging.join("etc/ssh/ssh_host_ed25519_key")).unwrap(),
            "device key\n"
        );
    }

    /// Every first-boot hook any layer ships must be executable.
    ///
    /// The overlay trees are copied with `cp -a` and normalized by git's two file modes
    /// ([`normalize_overlay_modes`]), so a hook's executable bit in the repo is its
    /// executable bit in the image, and
    /// [the runner](../../../base/overlay/usr/lib/boot2deb/first-boot)
    /// refuses to run a non-executable one. The hooks are load-bearing — depthcharge's
    /// re-signs the kernel partition against the UUID first-boot has just changed — so a
    /// lost `+x` bit is the difference between a board that boots and one that boots
    /// exactly once. Nothing else in the build would notice, hence this test.
    #[test]
    fn shipped_first_boot_hooks_are_executable() {
        use std::os::unix::fs::PermissionsExt;

        let root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .ancestors()
            .nth(2)
            .unwrap()
            .to_path_buf();
        let mut checked: Vec<std::path::PathBuf> = Vec::new();
        // Every layer kind that can carry an overlay tree, which is every kind the
        // rootfs stage merges: base, then soc, boot method, device, feature. This list
        // must stay in step with the CLI's `overlay_dirs` — a kind missing here is not a
        // failing test but a *vacuous* one, silently exempting whatever it holds.
        let layer_dirs = std::iter::once(root.join("base")).chain(
            ["socs", "boot-methods", "devices", "features"]
                .iter()
                .flat_map(|kind| {
                    std::fs::read_dir(root.join(kind))
                        .into_iter()
                        .flatten()
                        .flatten()
                        .map(|e| e.path())
                        .filter(|p| p.is_dir())
                }),
        );

        for layer in layer_dirs {
            for overlay in ["overlay", "overlay-pre", "overlay-nonfree"] {
                let hooks = layer.join(overlay).join("etc/boot2deb/first-boot.d");
                let Ok(entries) = std::fs::read_dir(&hooks) else {
                    continue; // this layer ships no hooks, which is the common case
                };
                for entry in entries.flatten() {
                    let path = entry.path();
                    let mode = path.metadata().unwrap().permissions().mode();
                    assert!(
                        mode & 0o111 != 0,
                        "first-boot hook {} is mode {:o}; it would be copied into the image \
                         non-executable and the runner would refuse to boot past it",
                        path.display(),
                        mode & 0o7777,
                    );
                    checked.push(path);
                }
            }
        }
        // A path typo that found no hooks at all would make the assertions above vacuous,
        // and so would a layer kind missing from the list above. Name one hook from each
        // kind that ships one, so losing a whole kind fails here instead of quietly
        // shrinking the test's reach. (No boot-method layer ships a hook: boot identity
        // is fixed at build time, so there is nothing bootloader-side to redo on-device.)
        for expected in [
            "socs/rk3288/overlay/etc/boot2deb/first-boot.d/20-audio",
            "devices/turing-rk1/overlay/etc/boot2deb/first-boot.d/20-network",
        ] {
            assert!(
                checked.contains(&root.join(expected)),
                "{expected} was never checked — the layer-kind list above has a hole in it",
            );
        }
    }

    /// The other shape: a depthcharge board with a distro kernel.
    fn c201() -> ResolvedBuild {
        resolve_recipe(&repo_root(), "asus-c201/forky", &Overrides::default()).unwrap()
    }

    #[test]
    fn board_conf_derives_dtb_path_and_name() {
        let c = config::board_conf("rockchip/rk3576-h96-max-m9.dtb", "");
        assert!(c.contains("DTB_PATH=\"rockchip/rk3576-h96-max-m9.dtb\""));
        assert!(c.contains("DTB_NAME=\"rk3576-h96-max-m9.dtb\""));
        // A bare filename (no dir) uses itself as the name.
        assert!(config::board_conf("board.dtb", "").contains("DTB_NAME=\"board.dtb\""));
    }

    #[test]
    fn board_conf_gates_the_console_on_every_board_and_lets_one_override_it() {
        // Every board gets the assignment, because every board gets the console gate.
        // It re-states the script's `rootwait` default, which it replaces (board.conf
        // is sourced after it).
        let plain = config::board_conf("rockchip/rk3588-turing-rk1.dtb", "");
        assert!(plain.contains("EXTL_CMD_LINE=\"rootwait loglevel=4\"\n"));

        // A board's own arguments are appended *after* the gate, so a board that wants
        // a louder console can say so and the kernel takes its last `loglevel=`.
        let extra = config::board_conf(
            "rockchip/rk3576-h96-max-m9.dtb",
            "video=HDMI-A-1:d cpuidle.off=1",
        );
        assert!(extra
            .contains("EXTL_CMD_LINE=\"rootwait loglevel=4 video=HDMI-A-1:d cpuidle.off=1\"\n"));
        let louder = config::board_conf("rockchip/rk3576-h96-max-m9.dtb", "loglevel=7");
        assert!(louder.contains("EXTL_CMD_LINE=\"rootwait loglevel=4 loglevel=7\"\n"));
    }

    /// The rootfs PARTUUID the image node will write — a fixed value for the tests.
    const PARTUUID: uuid::Uuid = uuid::Uuid::from_bytes([0xb2; 16]);

    #[test]
    fn a_raw_gap_boot_mounts_root_by_the_partuuid_the_image_will_write() {
        // mk_extlinux reads root back out of fstab to build the cmdline, so this line
        // must name the partition the image node stamps into the GPT. It is the
        // device's boot identity for life — first-boot grows the partition but never
        // rewrites its PARTUUID — so no label and no filesystem UUID appears here.
        let f = config::fstab(&rk1(), PARTUUID);
        let expected = format!("PARTUUID={}\t/\text4", PARTUUID.hyphenated());
        assert!(
            f.contains(&expected),
            "fstab must root on the derived PARTUUID:\n{f}"
        );
        assert!(!f.contains("LABEL="));
        assert!(!f.contains("\tUUID="));
        assert!(f.contains("mk_extlinux"));
    }

    #[test]
    fn a_depthcharge_boot_mounts_root_by_the_partuuid_the_image_will_write() {
        // This line is what depthchargectl signs into the kernel, so it must name the
        // partition the image node is about to create — not a label, which the tool
        // would not resolve, and not a filesystem UUID, which does not exist yet.
        let f = config::fstab(&c201(), PARTUUID);
        let expected = format!("PARTUUID={}\t/\text4", PARTUUID.hyphenated());
        assert!(
            f.contains(&expected),
            "fstab must root on the derived PARTUUID:\n{f}"
        );
        assert!(!f.contains("LABEL="));
        // And it says how to re-sign, because editing this line without doing so
        // produces a system that boots once and then does not.
        assert!(f.contains("depthchargectl write"));
    }

    #[test]
    fn a_data_volume_follows_root_by_label_and_cannot_block_the_boot() {
        use boot2deb_core::datavolume::{
            CreatePolicy, DataVolume, DiskKind, VolumeFs, VolumeMatch,
        };
        let mut b = rk1();
        b.data_volumes = vec![DataVolume {
            match_: VolumeMatch::Kind(DiskKind::Nvme),
            label: "b2d-data".into(),
            fstype: VolumeFs::Ext4,
            mount: "/srv".into(),
            create: CreatePolicy::IfBlank,
        }];
        let f = config::fstab(&b, PARTUUID);
        let lines: Vec<&str> = f.lines().filter(|l| !l.starts_with('#')).collect();

        // Root still comes first and still roots on the PARTUUID.
        assert!(lines[0].starts_with(&format!("PARTUUID={}", PARTUUID.hyphenated())));
        // The data volume mounts by LABEL: the one identifier that survives the disk
        // moving slots, and the whole point of a volume that outlives its image.
        assert_eq!(
            lines[1],
            "LABEL=b2d-data\t/srv\text4\tdefaults,nofail,x-systemd.device-timeout=10s\t0 2"
        );
        // A missing or slow data disk must never be why a system will not boot.
        assert!(lines[1].contains("nofail"));
    }

    #[test]
    fn a_build_with_no_data_volumes_writes_the_fstab_it_always_did() {
        // The feature is opt-in, so an image that declares none must not gain a line,
        // a blank, or a comment about an axis it does not use.
        let f = config::fstab(&rk1(), PARTUUID);
        assert_eq!(f.lines().filter(|l| !l.starts_with('#')).count(), 1);
        assert!(!f.contains("LABEL="));
    }

    #[test]
    fn the_build_time_depthcharge_config_disarms_the_kernel_hooks() {
        // False during the build: the hook it gates runs `depthchargectl write`, which
        // hunts the *host's* block devices for a ChromeOS kernel partition. With the
        // target SD card plugged in while building, that is a real write to a real disk.
        let build = config::depthcharge_config("speedy", false);
        assert!(build.contains("enable-system-hooks = False"));
        assert!(build.contains("board = speedy"));
        // True in the shipped image, or an apt kernel upgrade would leave the signed
        // partition holding the old kernel while the filesystem moved on.
        assert!(config::depthcharge_config("speedy", true).contains("enable-system-hooks = True"));
    }

    #[test]
    fn the_depthcharge_initramfs_conf_states_the_list_and_the_slot_s_compressor() {
        // Pinned rather than probed: this file is what every `update-initramfs` on the
        // board reads, at build time and for the life of the image.
        assert_eq!(
            config::depthcharge_initramfs_conf(InitramfsCompress::Xz),
            "# Generated by boot2deb.\nMODULES=list\nCOMPRESS=xz\n"
        );
        assert_eq!(
            config::depthcharge_initramfs_conf(InitramfsCompress::Zstd),
            "# Generated by boot2deb.\nMODULES=list\nCOMPRESS=zstd\n"
        );
    }

    #[test]
    fn a_depthcharge_board_is_told_its_compressor_before_a_kernel_package_arrives() {
        // The whole reason this is pre-install config: `MODULES=list` and `COMPRESS=`
        // have to be readable when the kernel package's own hooks build the first
        // initramfs, or that one is built wrong and thrown away.
        let tmp = tempfile::tempdir().unwrap();
        let sink = |_e: crate::event::Event| {};
        let step = Step::start(&sink, "test");
        stage_preinstall_overlay(
            tmp.path(),
            &[],
            &c201(),
            Some(BootConfig::Depthcharge {
                board: "speedy-libreboot",
                cmdline: "console=tty1 ro",
                initramfs_compress: InitramfsCompress::Zstd,
            }),
            None,
            &step,
        )
        .unwrap();
        let conf = std::fs::read_to_string(
            tmp.path()
                .join("etc/initramfs-tools/conf.d/depthcharge.conf"),
        )
        .unwrap();
        assert!(conf.contains("COMPRESS=zstd"), "{conf}");
        assert!(conf.contains("MODULES=list"), "{conf}");

        // A raw-gap board has no signed payload and generates none of this.
        let rkbin = tempfile::tempdir().unwrap();
        stage_preinstall_overlay(rkbin.path(), &[], &rk1(), None, None, &step).unwrap();
        assert!(!rkbin
            .path()
            .join("etc/initramfs-tools/conf.d/depthcharge.conf")
            .exists());
    }

    #[test]
    fn apt_sources_has_suite_pockets_and_components() {
        // The emitted text is pinned rather than probed for substrings: this file is
        // what every `apt update` on the shipped board reads, and the component list
        // and archive-per-pocket split are both part of the contract.
        assert_eq!(
            config::apt_sources("forky", crate::bootstrap::COMPONENTS),
            "deb http://deb.debian.org/debian forky main contrib non-free non-free-firmware\n\
             deb http://deb.debian.org/debian-security forky-security main contrib non-free non-free-firmware\n\
             deb http://deb.debian.org/debian forky-updates main contrib non-free non-free-firmware\n"
        );
    }

    #[test]
    fn a_libre_image_offers_only_the_free_archive() {
        // The whole point of the libre axis reaching this file: an image whose kernel
        // cannot load a blob does not offer `non-free-firmware` to the person at its
        // console either. Every pocket narrows, not just the first.
        assert_eq!(
            config::apt_sources("forky", crate::bootstrap::FREE_COMPONENTS),
            "deb http://deb.debian.org/debian forky main\n\
             deb http://deb.debian.org/debian-security forky-security main\n\
             deb http://deb.debian.org/debian forky-updates main\n"
        );
    }

    #[test]
    fn apt_sources_omits_the_pockets_unstable_does_not_publish() {
        // Debian publishes neither `sid-security` nor `sid-updates` — both 404. The
        // generator used to emit them unconditionally, so a `sid` image booted and then
        // reported two dead sources on every `apt update`. `sid` is a documented,
        // deliberate suite value, so the fix belongs here and not in suite validation.
        assert_eq!(
            config::apt_sources("sid", crate::bootstrap::COMPONENTS),
            "deb http://deb.debian.org/debian sid main contrib non-free non-free-firmware\n"
        );
        assert_eq!(
            config::apt_sources("unstable", crate::bootstrap::COMPONENTS),
            "deb http://deb.debian.org/debian unstable main contrib non-free non-free-firmware\n"
        );
    }

    #[test]
    fn hosts_names_the_hostname() {
        assert!(config::hosts("turing-rk1").contains("127.0.1.1\tturing-rk1"));
    }

    /// Build a small rootfs-shaped tarball (`./`-prefixed, as the export writes) at
    /// `tarball` from the given `members` (`archive-path`, `contents`). Returns false
    /// if `tar` is unavailable so the caller can skip.
    #[cfg(test)]
    fn build_test_tar(tarball: &Path, root: &Path, members: &[(&str, &str)]) -> bool {
        for (path, contents) in members {
            let full = root.join(path.trim_start_matches("./"));
            std::fs::create_dir_all(full.parent().unwrap()).unwrap();
            std::fs::write(&full, contents).unwrap();
        }
        let mut cmd = Command::new("tar");
        cmd.arg("-cf").arg(tarball).arg("-C").arg(root);
        for (path, _) in members {
            cmd.arg(path);
        }
        cmd.status().map(|s| s.success()).unwrap_or(false)
    }

    #[test]
    fn validate_tar_rejects_a_tar_missing_a_required_member() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("r");
        let tarball = tmp.path().join("rootfs.tar");
        // Missing `./etc/shadow` — the completeness sentinel — stands in for a tar
        // truncated by an interrupted bootstrap.
        let members = [
            ("./etc/os-release", "ID=debian\n"),
            ("./etc/fstab", "LABEL=rootfs / ext4 defaults 0 1\n"),
        ];
        if !build_test_tar(&tarball, &root, &members) {
            eprintln!("skipping: tar unavailable");
            return;
        }
        let err = validate_tar(&tarball).unwrap_err();
        assert!(
            matches!(err, EngineError::ArtifactMissing { what, .. } if what.contains("etc/shadow")),
            "expected a missing-member error naming shadow"
        );
    }

    #[test]
    fn locale_gen_pairs_each_locale_with_its_codeset() {
        // locale-gen reads `<name> <codeset>` pairs, and the codeset is not separate
        // config — it is carried inside the name.
        let g = config::locale_gen(&[
            "C.UTF-8".to_string(),
            "en_US.UTF-8".to_string(),
            "sr_RS.UTF-8@latin".to_string(),
        ]);
        assert_eq!(
            g, "C.UTF-8 UTF-8\nen_US.UTF-8 UTF-8\nsr_RS.UTF-8@latin UTF-8\n",
            "a modifier rides after the codeset, not inside it"
        );
    }

    #[test]
    fn the_system_locale_is_written_to_locale_conf_not_default_locale() {
        // This is the whole point of the path choice. Debian makes /etc/default/locale
        // a symlink to /etc/locale.conf and systemd-tmpfiles re-asserts it with a
        // *forcing* rule (`L+ /etc/default/locale ... ../locale.conf`) — so a regular
        // file written at /etc/default/locale is deleted and replaced by the symlink on
        // the next boot, leaving the image with no locale at all. Write the target.
        assert_eq!(config::locale_conf("C.UTF-8"), "LANG=C.UTF-8\n");

        let tmp = tempfile::tempdir().unwrap();
        let sink = |_e: crate::event::Event| {};
        let step = Step::start(&sink, "test");
        stage_preinstall_overlay(tmp.path(), &[], &rk1(), None, None, &step).unwrap();

        assert!(tmp.path().join("etc/locale.conf").is_file());
        assert!(
            !tmp.path().join("etc/default/locale").exists(),
            "must not write /etc/default/locale — tmpfiles force-replaces it with a symlink"
        );
    }

    /// The identity document reaches the image, at the path a tool reading this disk
    /// from outside looks for it.
    ///
    /// The two assertions are the two halves of why the file exists. The board profile
    /// is the value that is **not** recoverable from the disk — `depthchargectl` gets it
    /// from the *running* board's HWID, so a tool re-signing this image's kernel from
    /// other media, or from a machine that is not this board, can only be told. And the
    /// document ships *inside* the image, so it must never carry the per-image first-boot
    /// password that its sibling — the provenance manifest, which stays with the build —
    /// exists to record.
    #[test]
    fn the_staged_overlay_carries_the_image_identity() {
        let build = c201();
        let identity = ident(&build);
        let tmp = tempfile::tempdir().unwrap();
        let sink = |_e: crate::event::Event| {};
        let step = Step::start(&sink, "test");
        stage_overlay(
            tmp.path(),
            &[],
            &build,
            uuid::Uuid::nil(),
            &identity,
            None,
            &step,
        )
        .unwrap();

        let path = tmp.path().join("etc/boot2deb/image.toml");
        let text = std::fs::read_to_string(&path).expect("identity staged into the rootfs");

        assert!(
            text.contains("board = \"speedy\""),
            "the depthcharge board profile is the one value an outside tool cannot \
             derive from the disk; without it the file has no reason to exist:\n{text}"
        );
        assert!(text.contains("device = \"asus-c201\""));
        assert!(
            text.contains("version = 1"),
            "a wire format read by other programs"
        );

        let data: String = text
            .lines()
            .filter(|l| !l.trim_start().starts_with('#'))
            .collect();
        assert!(
            !data.contains("password"),
            "the first-boot secret must never ship inside an image:\n{text}"
        );

        // A rockchip-rkbin board has no board profile, so it records none rather than an
        // empty string a reader would have to special-case.
        let rk = rk1();
        let tmp2 = tempfile::tempdir().unwrap();
        stage_overlay(
            tmp2.path(),
            &[],
            &rk,
            uuid::Uuid::nil(),
            &ident(&rk),
            None,
            &step,
        )
        .unwrap();
        let rk_text = std::fs::read_to_string(tmp2.path().join("etc/boot2deb/image.toml")).unwrap();
        assert!(rk_text.contains("boot_method = \"rockchip-rkbin\""));
        assert!(!rk_text.contains("board ="));
    }

    /// The two files the image needs because it is built on a machine that is not the
    /// board. Both failures are silent at build time and only surface on hardware: a
    /// `dhcpcd` that cannot start, and an initramfs that waits for the *builder's* swap
    /// and then skips the root filesystem check.
    #[test]
    fn the_staged_overlay_states_what_the_build_host_would_otherwise_answer() {
        let build = rk1();
        let tmp = tempfile::tempdir().unwrap();
        let sink = |_e: crate::event::Event| {};
        let step = Step::start(&sink, "test");
        stage_overlay(
            tmp.path(),
            &[],
            &build,
            uuid::Uuid::nil(),
            &ident(&build),
            None,
            &step,
        )
        .unwrap();

        // `dhcpcd.service` lists /etc/resolv.conf in its ReadWritePaths under
        // ProtectSystem=strict, and systemd refuses the namespace if the path is absent
        // — so the file existing is the whole requirement. No package ships one.
        let resolv = tmp.path().join("etc/resolv.conf");
        assert!(resolv.is_file(), "dhcpcd cannot start without this path");

        let conf =
            std::fs::read_to_string(tmp.path().join("etc/initramfs-tools/conf.d/boot2deb.conf"))
                .expect("the initramfs drop-in is staged");
        // Unset, the resume hook bakes the build host's swap device into every image.
        assert!(conf.contains("RESUME=none"), "{conf}");
        // Unset, the fsck hook probes a PARTUUID that no disk carries yet, finds nothing,
        // and ships an initramfs with no fsck — so root goes unchecked at every boot.
        // The type is the formatter's, not a literal, so the helper matches the image.
        assert!(
            conf.contains(&format!("FSTYPE={}", crate::image::ROOTFS_FS_KIND)),
            "{conf}"
        );
    }

    #[test]
    fn the_timezone_is_the_localtime_symlink_and_nothing_else() {
        // forky's tzdata *deletes* /etc/timezone on configure ("Removing now unused
        // /etc/timezone") and reads the zone back by readlink-ing /etc/localtime, so
        // the symlink is the entire interface. Writing the file would be worse than
        // redundant: it would be removed, and it would be the thing a reader trusted.
        assert_eq!(
            config::localtime_target("America/New_York"),
            "/usr/share/zoneinfo/America/New_York"
        );

        let tmp = tempfile::tempdir().unwrap();
        let sink = |_e: crate::event::Event| {};
        let step = Step::start(&sink, "test");
        stage_preinstall_overlay(tmp.path(), &[], &rk1(), None, None, &step).unwrap();

        let link = tmp.path().join("etc/localtime");
        assert_eq!(
            std::fs::read_link(&link).unwrap(),
            Path::new("/usr/share/zoneinfo/UTC"),
            "staged as a symlink, which `cp -dR` copies as a link"
        );
        assert!(!tmp.path().join("etc/timezone").exists());
    }

    #[test]
    fn configured_ntp_servers_set_the_primary_list_and_leave_the_fallback_pool_alone() {
        // Setting FallbackNTP too would strand an image the moment it booted on a
        // network its configured server is not on. Debian compiles its pool into that
        // fallback, and timesyncd consults it whenever the primary yields nothing — so
        // writing only NTP= makes a configured server a preference that degrades.
        let conf = config::timesyncd_conf(&["ntp.lan".to_string(), "192.168.1.1".to_string()]);
        assert!(
            conf.contains("NTP=ntp.lan 192.168.1.1\n"),
            "servers join with the space timesyncd splits on: {conf}"
        );
        // No *directive* sets it. Checked against the uncommented lines rather than the
        // whole file, since the drop-in explains in a comment why it leaves it alone.
        let directives: Vec<&str> = conf
            .lines()
            .map(str::trim)
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .collect();
        assert!(
            !directives.iter().any(|l| l.starts_with("FallbackNTP")),
            "the compiled-in pool must survive as the fallback: {directives:?}"
        );
        assert!(
            conf.contains("[Time]"),
            "timesyncd reads the [Time] section"
        );
    }

    #[test]
    fn an_image_with_no_configured_ntp_server_stages_no_drop_in() {
        let sink = |_e: crate::event::Event| {};

        // Empty is not "no time source" — it is Debian's compiled-in pool. Writing an
        // empty `NTP=` would say the opposite, so the file is absent instead.
        let bare = tempfile::tempdir().unwrap();
        let step = Step::start(&sink, "test");
        stage_preinstall_overlay(bare.path(), &[], &rk1(), None, None, &step).unwrap();
        assert!(
            !bare
                .path()
                .join("etc/systemd/timesyncd.conf.d/10-boot2deb.conf")
                .exists(),
            "an unconfigured image carries no timesyncd drop-in"
        );

        // Configured, the drop-in lands where timesyncd reads drop-ins — not as an
        // edit of timesyncd.conf, which is a systemd conffile a rewrite would make
        // every future upgrade prompt about.
        let configured = resolve_recipe(
            &repo_root(),
            "turing-rk1/media-accel-forky",
            &Overrides {
                ntp_servers: Some(vec!["ntp.lan".to_string()]),
                ..Overrides::default()
            },
        )
        .unwrap();
        let lan = tempfile::tempdir().unwrap();
        let step = Step::start(&sink, "test");
        stage_preinstall_overlay(lan.path(), &[], &configured, None, None, &step).unwrap();
        let conf = std::fs::read_to_string(
            lan.path()
                .join("etc/systemd/timesyncd.conf.d/10-boot2deb.conf"),
        )
        .expect("a configured image carries the drop-in");
        assert!(conf.contains("NTP=ntp.lan\n"), "{conf}");
    }

    #[test]
    fn only_a_board_with_a_keyboard_gets_a_keyboard_file() {
        let sink = |_e: crate::event::Event| {};

        // The C201 is a laptop: its layout is configured, and the file it lands in is
        // the one keyboard-configuration seeds its debconf answers from.
        let laptop = tempfile::tempdir().unwrap();
        let step = Step::start(&sink, "test");
        stage_preinstall_overlay(laptop.path(), &[], &c201(), None, None, &step).unwrap();
        let kb = std::fs::read_to_string(laptop.path().join("etc/default/keyboard")).unwrap();
        assert!(kb.contains("XKBLAYOUT=\"us\""));
        assert!(kb.contains("XKBMODEL=\"pc105\""));

        // The RK1 is headless. Writing a layout for a console nobody types at would be
        // a claim we cannot back; Debian's own default stands instead.
        let headless = tempfile::tempdir().unwrap();
        let step = Step::start(&sink, "test");
        stage_preinstall_overlay(headless.path(), &[], &rk1(), None, None, &step).unwrap();
        assert!(!headless.path().join("etc/default/keyboard").exists());
    }

    #[test]
    fn write_staged_forces_0644_regardless_of_umask() {
        use std::os::unix::fs::PermissionsExt;
        let tmp = tempfile::tempdir().unwrap();
        write_staged(tmp.path(), "etc/hostname", "host\n").unwrap();
        let mode = std::fs::metadata(tmp.path().join("etc/hostname"))
            .unwrap()
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o644);
    }
}
