//! Lockfile format — the *resolved exact pins* for a recipe. Populated from
//! upstream by `boot2deb update`; `build` reads only the lock and never resolves
//! "latest".

use crate::model::ExtraDeb;
use serde::{Deserialize, Serialize};

/// Deserialize a lock commit id, enforcing the full-40-hex-sha shape at the parse
/// boundary (SUB-3). `build` feeds these values straight into option-sensitive `git`
/// argv positions — the detached checkout and `fetch <commit>` — where a leading `-`
/// or other malformed value could be reinterpreted; pinning the shape at the lock
/// boundary means a hand-edited or corrupt lock cannot smuggle one that far. The
/// value is lowercased to git's canonical output form so a later `HEAD == commit`
/// byte comparison holds regardless of the case a hand-editor typed.
fn de_commit<'de, D>(d: D) -> Result<String, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let s = String::deserialize(d)?;
    if crate::sources::is_full_sha(&s) {
        Ok(s.to_ascii_lowercase())
    } else {
        Err(serde::de::Error::custom(format!(
            "commit '{s}' is not a full 40-character hex sha"
        )))
    }
}

/// Header prepended to a serialized lock, marking it generated.
const LOCK_BANNER: &str = "\
# Generated by `boot2deb update`; do not hand-edit.
# Exact resolved pins for the recipe. `boot2deb build` reads only this;
# re-run `boot2deb update` to re-resolve within the recipe's constraints.
";

/// The resolved exact pins for a recipe. `boot2deb build` reads only this;
/// `boot2deb update` is the sole writer, re-resolving upstream within the
/// recipe's constraints. Keeping old locks is what keeps old builds reproducible.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Lock {
    /// Exact kernel pin.
    pub kernel: KernelPin,
    /// Exact patch-series pin.
    pub patches: PatchesPin,
    /// Exact u-boot pin.
    pub uboot: UbootPin,
    /// Exact media-accel userspace source pins (MPP/RGA/Mali). Present iff the
    /// recipe builds the HW transcode stack (a `requires_media_accel` feature is
    /// selected); omitted from the committed lock for a base build, which resolves
    /// and builds no userspace/ffmpeg nodes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub userspace: Option<UserspacePins>,
    /// Exact ffmpeg source pins (V4L2 base + Rockchip rkmpp/rkrga). Present in
    /// lockstep with [`userspace`](Self::userspace) — the media-accel stack pins
    /// as a unit.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ffmpeg: Option<FfmpegPins>,
    /// Rootfs suite + content-pinned package manifest.
    pub rootfs: RootfsPin,
    /// Verified rkbin blob hashes.
    pub blobs: BlobsPin,
    /// Pre-built `.deb`s pulled from outside the Debian mirror,
    /// content-pinned by sha256 — the resolved [`ExtraDeb`] set recorded verbatim
    /// (the sha256 is already exact, so there is nothing to resolve). `update`
    /// fetches + verifies + stores each; `build` materializes from the store into
    /// the local apt repo. Empty (and omitted from the committed file) when no layer
    /// or feature adds one.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub extra_debs: Vec<ExtraDeb>,
    /// `snapshot.debian.org` availability backstop; captured but dormant.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub snapshot: Option<SnapshotPin>,
}

impl Lock {
    /// Serialize to the canonical committed form: the generated-file banner
    /// followed by the TOML body. This is the exact text `boot2deb update`
    /// writes to `recipes/<name>.lock`.
    pub fn to_toml_string(&self) -> Result<String, crate::ConfigError> {
        let body = toml::to_string(self).map_err(|source| crate::ConfigError::Serialize {
            what: "lock",
            source,
        })?;
        Ok(format!("{LOCK_BANNER}{body}"))
    }
}

/// Pinned kernel: which definition, at which ref, resolved to which commit.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct KernelPin {
    /// Kernel definition id.
    pub id: String,
    /// The tag/branch that was resolved (TOML key `ref`).
    #[serde(rename = "ref")]
    pub reference: String,
    /// The exact commit the ref pointed at. Deserialization enforces the full-hex-sha
    /// shape (SUB-3).
    #[serde(deserialize_with = "de_commit")]
    pub commit: String,
}

/// Pinned patch series: the profile and the exact `patches`-repo commit.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PatchesPin {
    /// Patch profile name.
    pub profile: String,
    /// `patches` repo commit. Deserialization enforces the full-hex-sha
    /// shape (SUB-3).
    #[serde(deserialize_with = "de_commit")]
    pub commit: String,
}

/// Pinned u-boot: ref and exact commit.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UbootPin {
    /// The tag that was resolved (TOML key `ref`).
    #[serde(rename = "ref")]
    pub reference: String,
    /// The exact commit the ref pointed at. Deserialization enforces the full-hex-sha
    /// shape (SUB-3).
    #[serde(deserialize_with = "de_commit")]
    pub commit: String,
}

/// A resolved git pin: the ref that was requested and the exact commit it
/// resolved to. Shared by the userspace and ffmpeg source pins.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GitPin {
    /// The branch/tag/commit that was requested (TOML key `ref`).
    #[serde(rename = "ref")]
    pub reference: String,
    /// The exact commit the ref pointed at. Deserialization enforces the full-hex-sha
    /// shape (SUB-3).
    #[serde(deserialize_with = "de_commit")]
    pub commit: String,
}

/// Pinned media-accel userspace sources — the MPP/RGA/Mali forks the userspace
/// build node compiles into `.deb`s.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UserspacePins {
    /// Rockchip MPP pin (`librockchip-mpp1`).
    pub mpp: GitPin,
    /// librga pin (`librga2`).
    pub librga: GitPin,
    /// libmali pin (built only when requested).
    pub libmali: GitPin,
}

/// Pinned ffmpeg sources — the V4L2 base plus the Rockchip provenance tree the
/// graft patch series was derived from. `build` fetches `base` and applies
/// the profile's ffmpeg `git am` series; the graft is not re-derived from
/// `rockchip`, which is recorded purely as provenance.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FfmpegPins {
    /// Base tree pin (V4L2-request decode).
    pub base: GitPin,
    /// Rockchip rkmpp/rkrga provenance-tree pin the graft series was derived from.
    pub rockchip: GitPin,
}

/// Pinned rootfs: the suite plus a pointer to the solved package manifest that
/// content-pins every package (name → version → sha256) — the reproducibility
/// guarantee.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RootfsPin {
    /// Debian suite.
    pub suite: String,
    /// Filename of the content-pinned solved package manifest, committed beside
    /// the lock (`recipes/<manifest>`).
    pub manifest: String,
    /// sha256 of that committed manifest file, pinning the manifest itself so a
    /// committed-manifest that drifts from the lock is caught. `None` until
    /// the manifest is committed beside the lock — the manifest-as-input wiring
    /// sets it; a bare `update` before any build leaves it unset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub manifest_sha256: Option<String>,
}

/// Pinned rkbin blobs, each `"<filename>@sha256:<hex>"`, verified before the
/// u-boot build consumes them.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BlobsPin {
    /// ATF/BL31 blob pin.
    pub atf: String,
    /// DDR TPL blob pin.
    pub tpl: String,
}

/// How a captured snapshot participates in a build.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SnapshotMode {
    /// Provenance only; builds use the live mirror.
    Off,
    /// Live mirror first, snapshot fills anything that 404s.
    Fallback,
    /// Build exclusively against the snapshot.
    Pin,
}

impl SnapshotMode {
    /// The mode's lowercase name — matches the serialized TOML form and the
    /// `--snapshot` CLI value, so error messages and the flag agree.
    pub fn as_str(self) -> &'static str {
        match self {
            SnapshotMode::Off => "off",
            SnapshotMode::Fallback => "fallback",
            SnapshotMode::Pin => "pin",
        }
    }
}

/// A captured `snapshot.debian.org` timestamp and its activation mode.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SnapshotPin {
    /// Snapshot timestamp (e.g. `20260628T083000Z`).
    pub timestamp: String,
    /// Whether/how the snapshot is used.
    pub mode: SnapshotMode,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lock_roundtrips_through_toml() {
        let lock = Lock {
            kernel: KernelPin {
                id: "rk3588-mainline-7.1".into(),
                reference: "v7.1.1".into(),
                commit: "c9acdc466e9aa96352f658b9276aa8a45b8e817d".into(),
            },
            patches: PatchesPin {
                profile: "rk3588-accel".into(),
                commit: "f78b240894a29a4c3976ad22935b1c2e16b3c6ad".into(),
            },
            uboot: UbootPin {
                reference: "v2026.04".into(),
                commit: "88dc2788777babfd6322fa655df549a019aa1e69".into(),
            },
            userspace: Some(UserspacePins {
                mpp: GitPin {
                    reference: "mainline-cma-fix".into(),
                    commit: "750e76ec2d9287babfaf08c8bf395ebc5e8778ea".into(),
                },
                librga: GitPin {
                    reference: "master".into(),
                    commit: "2cffdf6f332c3ddb93eb087841d78e8b487db2a3".into(),
                },
                libmali: GitPin {
                    reference: "master".into(),
                    commit: "bd33ee262f47fd936b831afccaa0759b3ecc2482".into(),
                },
            }),
            ffmpeg: Some(FfmpegPins {
                base: GitPin {
                    reference: "v4l2-request-n8.1".into(),
                    commit: "b57fbbe50c9b2656fad86a1a7eeabfd2b2a50935".into(),
                },
                rockchip: GitPin {
                    reference: "8.1".into(),
                    commit: "f66f2f804627e4464c2d1b10181772b5437bb991".into(),
                },
            }),
            rootfs: RootfsPin {
                suite: "forky".into(),
                manifest: "turing-rk1-forky.pkgs.lock".into(),
                manifest_sha256: Some("deadbeef".into()),
            },
            blobs: BlobsPin {
                atf: "rk3588_bl31_v1.51.elf@sha256:00".into(),
                tpl: "rk3588_ddr_lp4_2112MHz_lp5_2400MHz_v1.19.bin@sha256:11".into(),
            },
            extra_debs: vec![
                ExtraDeb {
                    url: Some("https://vendor.example/foo_1.2_arm64.deb".into()),
                    path: None,
                    sha256: "aa".into(),
                },
                ExtraDeb {
                    url: None,
                    path: Some("vendor/bar_3.4_arm64.deb".into()),
                    sha256: "bb".into(),
                },
            ],
            snapshot: Some(SnapshotPin {
                timestamp: "20260628T083000Z".into(),
                mode: SnapshotMode::Off,
            }),
        };
        let text = lock.to_toml_string().unwrap();
        assert!(text.starts_with("# Generated by `boot2deb update`"));
        let back: Lock = toml::from_str(&text).unwrap();
        assert_eq!(lock, back);
    }

    /// A minimal lock with no captured snapshot — the shape `update` writes today
    /// (`pins.rs` always emits `snapshot: None`). The committed form must omit the
    /// `[snapshot]` table entirely (`skip_serializing_if`), not write
    /// `snapshot = ` or an empty table, and must round-trip back to `None`.
    fn base_lock() -> Lock {
        Lock {
            kernel: KernelPin {
                id: "k".into(),
                reference: "v1".into(),
                commit: "a".repeat(40),
            },
            patches: PatchesPin {
                profile: "none".into(),
                commit: "b".repeat(40),
            },
            uboot: UbootPin {
                reference: "v2".into(),
                commit: "c".repeat(40),
            },
            userspace: Some(UserspacePins {
                mpp: GitPin { reference: "m".into(), commit: "1".repeat(40) },
                librga: GitPin { reference: "r".into(), commit: "2".repeat(40) },
                libmali: GitPin { reference: "l".into(), commit: "3".repeat(40) },
            }),
            ffmpeg: Some(FfmpegPins {
                base: GitPin { reference: "b".into(), commit: "4".repeat(40) },
                rockchip: GitPin { reference: "rk".into(), commit: "5".repeat(40) },
            }),
            rootfs: RootfsPin {
                suite: "forky".into(),
                manifest: "rec.pkgs.lock".into(),
                manifest_sha256: None,
            },
            blobs: BlobsPin {
                atf: "atf@sha256:0".into(),
                tpl: "tpl@sha256:1".into(),
            },
            extra_debs: vec![],
            snapshot: None,
        }
    }

    #[test]
    fn deserialize_rejects_a_non_sha_commit() {
        // A lock whose kernel commit is not a full 40-hex sha is refused at parse
        // time (SUB-3), so a malformed/hand-edited value never reaches the git argv.
        let text = base_lock().to_toml_string().unwrap();
        let tampered = text.replacen(
            &format!("commit = \"{}\"", "a".repeat(40)),
            "commit = \"-o=evil\"",
            1,
        );
        assert!(
            toml::from_str::<Lock>(&tampered).is_err(),
            "a non-sha commit must be rejected at deserialize"
        );
        // An uppercase sha is accepted but canonicalized to git's lowercase form.
        let upper = text.replacen(
            &format!("commit = \"{}\"", "a".repeat(40)),
            &format!("commit = \"{}\"", "A".repeat(40)),
            1,
        );
        let back: Lock = toml::from_str(&upper).unwrap();
        assert_eq!(back.kernel.commit, "a".repeat(40));
    }

    #[test]
    fn lock_without_snapshot_omits_the_table() {
        let lock = base_lock();
        let text = lock.to_toml_string().unwrap();
        // The reserved/optional fields collapse out of the committed form when
        // unset, so the shipped lock stays minimal until a mechanism populates them.
        assert!(
            !text.contains("[snapshot]") && !text.contains("snapshot ="),
            "committed lock must not emit a snapshot table when None:\n{text}"
        );
        assert!(
            !text.contains("extra_debs"),
            "empty extra_debs must be omitted:\n{text}"
        );
        assert!(
            !text.contains("manifest_sha256"),
            "unset manifest_sha256 must be omitted:\n{text}"
        );
        let back: Lock = toml::from_str(&text).unwrap();
        assert_eq!(back.snapshot, None);
        assert!(back.extra_debs.is_empty());
        assert_eq!(back.rootfs.manifest_sha256, None);
        assert_eq!(lock, back);
    }

    #[test]
    fn base_build_lock_omits_the_media_accel_tables() {
        // A recipe with no `requires_media_accel` feature builds no userspace/ffmpeg
        // nodes, so `update` writes no pins for them. The committed lock must omit
        // both tables entirely (not empty tables) and round-trip back to `None`.
        let mut lock = base_lock();
        lock.userspace = None;
        lock.ffmpeg = None;
        let text = lock.to_toml_string().unwrap();
        assert!(
            !text.contains("[userspace") && !text.contains("[ffmpeg"),
            "base-build lock must not emit media-accel tables:\n{text}"
        );
        let back: Lock = toml::from_str(&text).unwrap();
        assert_eq!(back.userspace, None);
        assert_eq!(back.ffmpeg, None);
        assert_eq!(lock, back);
    }
}
