//! Lockfile format — the *resolved exact pins* for a recipe. Populated from
//! upstream by `boot2deb update`; `build` reads only the lock and never resolves
//! "latest".

use crate::model::ExtraDeb;
use serde::{Deserialize, Serialize};

/// Deserialize a lock commit id, enforcing the full-40-hex-sha shape at the parse
/// boundary (SUB-3). `build` feeds these values straight into option-sensitive `git`
/// argv positions — the detached checkout and `fetch <commit>` — where a leading `-`
/// or other malformed value could be reinterpreted; pinning the shape at the lock
/// boundary means a hand-edited or corrupt lock cannot smuggle one that far. The
/// value is lowercased to git's canonical output form so a later `HEAD == commit`
/// byte comparison holds regardless of the case a hand-editor typed.
fn de_commit<'de, D>(d: D) -> Result<String, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let s = String::deserialize(d)?;
    if crate::sources::is_full_sha(&s) {
        Ok(s.to_ascii_lowercase())
    } else {
        Err(serde::de::Error::custom(format!(
            "commit '{s}' is not a full 40-character hex sha"
        )))
    }
}

/// Shape-check one `"<filename>@sha256:<hex64>"` blob pin (TRUST-7): a bare
/// filename (non-empty, no separators, not option-like) and a 64-char
/// lowercase-hex digest — the exact form `update`'s pin generator emits.
/// Returns the failure reason for a deserializer to wrap.
fn check_blob_pin(pin: &str) -> Result<(), String> {
    let Some((file, hex)) = pin.rsplit_once("@sha256:") else {
        return Err("has no '@sha256:' separator".into());
    };
    if file.is_empty() || file.contains('/') || file.contains('\\') || file.starts_with('-') {
        return Err("has an invalid filename component".into());
    }
    if !crate::sources::is_sha256_hex(hex) {
        return Err("digest is not 64 lowercase hex characters".into());
    }
    Ok(())
}

/// Deserialize a blob pin, enforcing the `"<filename>@sha256:<hex64>"` shape at
/// the parse boundary (TRUST-7, the [`de_commit`] discipline): the filename is
/// later joined into blob-dir paths and the digest compared as bytes, so a
/// hand-edited or corrupt lock must fail here, attributably, not downstream.
fn de_blob_pin<'de, D>(d: D) -> Result<String, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let s = String::deserialize(d)?;
    check_blob_pin(&s).map_err(|why| serde::de::Error::custom(format!("blob pin '{s}' {why}")))?;
    Ok(s)
}

/// [`de_blob_pin`] for the optional BL32 pin.
fn de_opt_blob_pin<'de, D>(d: D) -> Result<Option<String>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    match Option::<String>::deserialize(d)? {
        Some(s) => {
            check_blob_pin(&s)
                .map_err(|why| serde::de::Error::custom(format!("blob pin '{s}' {why}")))?;
            Ok(Some(s))
        }
        None => Ok(None),
    }
}

/// Deserialize the manifest filename as a *bare* name (TRUST-7): it is joined
/// into `recipes/<manifest>` paths, so separators or dot-dirs must fail at the
/// parse boundary rather than address a file outside `recipes/`.
fn de_bare_filename<'de, D>(d: D) -> Result<String, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let s = String::deserialize(d)?;
    let bad = s.is_empty()
        || s.contains('/')
        || s.contains('\\')
        || s == "."
        || s == ".."
        || s.starts_with('-');
    if bad {
        return Err(serde::de::Error::custom(format!(
            "manifest '{s}' is not a bare filename"
        )));
    }
    Ok(s)
}

/// Deserialize the optional manifest digest as 64 lowercase hex (TRUST-7).
fn de_opt_sha256<'de, D>(d: D) -> Result<Option<String>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    match Option::<String>::deserialize(d)? {
        Some(s) if crate::sources::is_sha256_hex(&s) => Ok(Some(s)),
        Some(s) => Err(serde::de::Error::custom(format!(
            "sha256 '{s}' is not 64 lowercase hex characters"
        ))),
        None => Ok(None),
    }
}

/// Header prepended to a serialized lock, marking it generated.
const LOCK_BANNER: &str = "\
# Generated by `boot2deb update`; do not hand-edit.
# Exact resolved pins for the recipe. `boot2deb build` reads only this;
# re-run `boot2deb update` to re-resolve within the recipe's constraints.
";

/// The resolved exact pins for a recipe. `boot2deb build` reads only this;
/// `boot2deb update` is the sole writer, re-resolving upstream within the
/// recipe's constraints. Keeping old locks is what keeps old builds reproducible.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Lock {
    /// Exact kernel pin. Present iff the build **compiles** a kernel. A
    /// distro-package kernel is installed from the mirror like any other package, so
    /// its exact version and hash live in the solved package manifest
    /// ([`RootfsPin::manifest`]) and there is no commit to pin here; the committed
    /// lock then omits the `[kernel]` table entirely, rather than recording a source
    /// dependency the build does not have.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kernel: Option<KernelPin>,
    /// Exact patch-series pin. Present iff the resolved kernel names a patch
    /// profile. A kernel that applies no series never reads the `patches` repo, so
    /// pinning a commit would record provenance for a dependency the build does not
    /// have; the committed lock then omits the `[patches]` table entirely.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub patches: Option<PatchesPin>,
    /// Exact u-boot pin. Present iff the build's boot method **compiles u-boot**
    /// (`rockchip-rkbin`). A depthcharge board's firmware is its own — coreboot in an
    /// SPI chip — so nothing bootloader-shaped is fetched or built, and the committed
    /// lock omits the `[uboot]` table.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uboot: Option<UbootPin>,
    /// Exact media-accel userspace source pins (MPP/RGA/Mali). Present iff the
    /// recipe builds the HW transcode stack (a `requires_media_accel` feature is
    /// selected); omitted from the committed lock for a base build, which resolves
    /// and builds no userspace/ffmpeg nodes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub userspace: Option<UserspacePins>,
    /// Exact ffmpeg source pins (V4L2 base + Rockchip rkmpp/rkrga). Present in
    /// lockstep with [`userspace`](Self::userspace) — the media-accel stack pins
    /// as a unit.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ffmpeg: Option<FfmpegPins>,
    /// Rootfs suite + content-pinned package manifest.
    pub rootfs: RootfsPin,
    /// Verified rkbin blob hashes. Present iff the build's boot method consumes rkbin
    /// blobs (`rockchip-rkbin`, whose u-boot build takes the ATF and DDR TPL as make
    /// inputs). Omitted from the committed lock otherwise.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub blobs: Option<BlobsPin>,
    /// Pre-built `.deb`s pulled from outside the Debian mirror,
    /// content-pinned by sha256 — the resolved [`ExtraDeb`] set recorded verbatim
    /// (the sha256 is already exact, so there is nothing to resolve). `update`
    /// fetches + verifies + stores each; `build` materializes from the store into
    /// the local apt repo. Empty (and omitted from the committed file) when no layer
    /// or feature adds one.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub extra_debs: Vec<ExtraDeb>,
    /// `snapshot.debian.org` availability backstop; captured but dormant.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub snapshot: Option<SnapshotPin>,
}

impl Lock {
    /// Serialize to the canonical committed form: the generated-file banner
    /// followed by the TOML body. This is the exact text `boot2deb update`
    /// writes to `recipes/<name>.lock`.
    pub fn to_toml_string(&self) -> Result<String, crate::ConfigError> {
        let body = toml::to_string(self).map_err(|source| crate::ConfigError::Serialize {
            what: "lock",
            source,
        })?;
        Ok(format!("{LOCK_BANNER}{body}"))
    }
}

/// Pinned kernel: which definition, from which repo, at which ref, resolved to
/// which commit.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct KernelPin {
    /// Kernel definition id.
    pub id: String,
    /// Clone URL the commit was pinned from (the definition's resolved source).
    /// A commit id is meaningful only within its repo, so every commit pin
    /// records its source; the drift gate compares it against a fresh resolve,
    /// catching a config edit that would reinterpret the pin in a different
    /// repo (COR-23).
    pub source: String,
    /// The tag/branch that was resolved (TOML key `ref`).
    #[serde(rename = "ref")]
    pub reference: String,
    /// The exact commit the ref pointed at. Deserialization enforces the full-hex-sha
    /// shape (SUB-3).
    #[serde(deserialize_with = "de_commit")]
    pub commit: String,
}

/// Pinned patch series: the profile and the exact `patches`-repo commit.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PatchesPin {
    /// Patch profile name.
    pub profile: String,
    /// `patches` repo commit. Deserialization enforces the full-hex-sha
    /// shape (SUB-3).
    #[serde(deserialize_with = "de_commit")]
    pub commit: String,
}

/// Pinned u-boot: source repo, ref, and exact commit.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UbootPin {
    /// Clone URL the commit was pinned from (the resolved boot method's
    /// `uboot_source`). The drift gate compares it against a fresh resolve, so
    /// a boot-method flip to a different repo cannot silently reinterpret the
    /// commit there (COR-23).
    pub source: String,
    /// The tag that was resolved (TOML key `ref`).
    #[serde(rename = "ref")]
    pub reference: String,
    /// The exact commit the ref pointed at. Deserialization enforces the full-hex-sha
    /// shape (SUB-3).
    #[serde(deserialize_with = "de_commit")]
    pub commit: String,
}

/// A resolved git pin: the source repo, the ref that was requested, and the
/// exact commit it resolved to. Shared by the userspace and ffmpeg source pins.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GitPin {
    /// Clone URL the commit was pinned from (the resolved SoC-layer source).
    /// Compared against a fresh resolve by the drift gate (COR-23).
    pub source: String,
    /// The branch/tag/commit that was requested (TOML key `ref`).
    #[serde(rename = "ref")]
    pub reference: String,
    /// The exact commit the ref pointed at. Deserialization enforces the full-hex-sha
    /// shape (SUB-3).
    #[serde(deserialize_with = "de_commit")]
    pub commit: String,
}

/// Pinned media-accel userspace sources — the MPP/RGA/Mali forks the userspace
/// build node compiles into `.deb`s.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UserspacePins {
    /// Rockchip MPP pin (`librockchip-mpp1`).
    pub mpp: GitPin,
    /// librga pin (`librga2`).
    pub librga: GitPin,
    /// libmali pin (built only when requested).
    pub libmali: GitPin,
}

/// Pinned ffmpeg sources — the V4L2 base plus the Rockchip provenance tree the
/// graft patch series was derived from. `build` fetches `base` and applies
/// the profile's ffmpeg `git am` series; the graft is not re-derived from
/// `rockchip`, which is recorded purely as provenance.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FfmpegPins {
    /// Base tree pin (V4L2-request decode).
    pub base: GitPin,
    /// Rockchip rkmpp/rkrga provenance-tree pin the graft series was derived from.
    pub rockchip: GitPin,
}

/// Pinned rootfs: the suite plus a pointer to the solved package manifest that
/// content-pins every package (name → version → sha256) — the reproducibility
/// guarantee.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RootfsPin {
    /// Debian suite.
    pub suite: String,
    /// Filename of the content-pinned solved package manifest, committed beside
    /// the lock (`recipes/<manifest>`). Deserialization enforces a bare filename
    /// (TRUST-7).
    #[serde(deserialize_with = "de_bare_filename")]
    pub manifest: String,
    /// sha256 of that committed manifest file, pinning the manifest itself so a
    /// committed-manifest that drifts from the lock is caught. `None` until
    /// the manifest is committed beside the lock — the manifest-as-input wiring
    /// sets it; a bare `update` before any build leaves it unset. Deserialization
    /// enforces the 64-lowercase-hex shape (TRUST-7).
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "de_opt_sha256"
    )]
    pub manifest_sha256: Option<String>,
}

/// Pinned rkbin blobs, each `"<filename>@sha256:<hex>"`, verified before the
/// u-boot build consumes them.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BlobsPin {
    /// ATF/BL31 blob pin. Deserialization enforces the
    /// `"<filename>@sha256:<hex64>"` shape (TRUST-7).
    #[serde(deserialize_with = "de_blob_pin")]
    pub atf: String,
    /// DDR TPL blob pin. Shape-enforced like [`atf`](Self::atf) (TRUST-7).
    #[serde(deserialize_with = "de_blob_pin")]
    pub tpl: String,
    /// OP-TEE BL32 blob pin, present only when the build has one. Absent on
    /// BL31-only boots (RK3588/RK1), so those locks serialize without the field.
    /// Shape-enforced like [`atf`](Self::atf) when present (TRUST-7).
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "de_opt_blob_pin"
    )]
    pub bl32: Option<String>,
}

/// How a captured snapshot participates in a build.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SnapshotMode {
    /// Provenance only; builds use the live mirror.
    Off,
    /// Live mirror first, snapshot fills anything that 404s.
    Fallback,
    /// Build exclusively against the snapshot.
    Pin,
}

impl SnapshotMode {
    /// The mode's lowercase name — matches the serialized TOML form and the
    /// `--snapshot` CLI value, so error messages and the flag agree.
    pub fn as_str(self) -> &'static str {
        match self {
            SnapshotMode::Off => "off",
            SnapshotMode::Fallback => "fallback",
            SnapshotMode::Pin => "pin",
        }
    }
}

/// A captured `snapshot.debian.org` timestamp and its activation mode.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SnapshotPin {
    /// Snapshot timestamp (e.g. `20260628T083000Z`).
    pub timestamp: String,
    /// Whether/how the snapshot is used.
    pub mode: SnapshotMode,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lock_roundtrips_through_toml() {
        let lock = Lock {
            kernel: Some(KernelPin {
                id: "rk3588-mainline-7.1".into(),
                source: "https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git".into(),
                reference: "v7.1.1".into(),
                commit: "c9acdc466e9aa96352f658b9276aa8a45b8e817d".into(),
            }),
            patches: Some(PatchesPin {
                profile: "rk3588-accel".into(),
                commit: "f78b240894a29a4c3976ad22935b1c2e16b3c6ad".into(),
            }),
            uboot: Some(UbootPin {
                source: "https://source.denx.de/u-boot/u-boot.git".into(),
                reference: "v2026.04".into(),
                commit: "88dc2788777babfd6322fa655df549a019aa1e69".into(),
            }),
            userspace: Some(UserspacePins {
                mpp: GitPin {
                    source: "https://github.com/example/mpp.git".into(),
                    reference: "mainline-cma-fix".into(),
                    commit: "750e76ec2d9287babfaf08c8bf395ebc5e8778ea".into(),
                },
                librga: GitPin {
                    source: "https://github.com/example/librga.git".into(),
                    reference: "master".into(),
                    commit: "2cffdf6f332c3ddb93eb087841d78e8b487db2a3".into(),
                },
                libmali: GitPin {
                    source: "https://github.com/example/libmali.git".into(),
                    reference: "master".into(),
                    commit: "bd33ee262f47fd936b831afccaa0759b3ecc2482".into(),
                },
            }),
            ffmpeg: Some(FfmpegPins {
                base: GitPin {
                    source: "https://github.com/example/ffmpeg.git".into(),
                    reference: "v4l2-request-n8.1".into(),
                    commit: "b57fbbe50c9b2656fad86a1a7eeabfd2b2a50935".into(),
                },
                rockchip: GitPin {
                    source: "https://github.com/example/ffmpeg-rockchip.git".into(),
                    reference: "8.1".into(),
                    commit: "f66f2f804627e4464c2d1b10181772b5437bb991".into(),
                },
            }),
            rootfs: RootfsPin {
                suite: "forky".into(),
                manifest: "turing-rk1-forky.pkgs.lock".into(),
                manifest_sha256: Some("dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd".into()),
            },
            blobs: Some(BlobsPin {
                atf: "rk3588_bl31_v1.51.elf@sha256:0000000000000000000000000000000000000000000000000000000000000000".into(),
                tpl: "rk3588_ddr_lp4_2112MHz_lp5_2400MHz_v1.19.bin@sha256:1111111111111111111111111111111111111111111111111111111111111111".into(),
                bl32: None,
            }),
            extra_debs: vec![
                ExtraDeb {
                    url: Some("https://vendor.example/foo_1.2_arm64.deb".into()),
                    path: None,
                    sha256: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".into(),
                },
                ExtraDeb {
                    url: None,
                    path: Some("vendor/bar_3.4_arm64.deb".into()),
                    sha256: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb".into(),
                },
            ],
            snapshot: Some(SnapshotPin {
                timestamp: "20260628T083000Z".into(),
                mode: SnapshotMode::Off,
            }),
        };
        let text = lock.to_toml_string().unwrap();
        assert!(text.starts_with("# Generated by `boot2deb update`"));
        let back: Lock = toml::from_str(&text).unwrap();
        assert_eq!(lock, back);
    }

    /// A minimal lock with no captured snapshot — the shape `update` writes today
    /// (`pins.rs` always emits `snapshot: None`). The committed form must omit the
    /// `[snapshot]` table entirely (`skip_serializing_if`), not write
    /// `snapshot = ` or an empty table, and must round-trip back to `None`.
    fn base_lock() -> Lock {
        Lock {
            kernel: Some(KernelPin {
                id: "k".into(),
                source: "https://k.example/k.git".into(),
                reference: "v1".into(),
                commit: "a".repeat(40),
            }),
            patches: Some(PatchesPin {
                profile: "rk3588-accel".into(),
                commit: "b".repeat(40),
            }),
            uboot: Some(UbootPin {
                source: "https://u.example/u.git".into(),
                reference: "v2".into(),
                commit: "c".repeat(40),
            }),
            userspace: Some(UserspacePins {
                mpp: GitPin { source: "m://s".into(), reference: "m".into(), commit: "1".repeat(40) },
                librga: GitPin { source: "r://s".into(), reference: "r".into(), commit: "2".repeat(40) },
                libmali: GitPin { source: "l://s".into(), reference: "l".into(), commit: "3".repeat(40) },
            }),
            ffmpeg: Some(FfmpegPins {
                base: GitPin { source: "b://s".into(), reference: "b".into(), commit: "4".repeat(40) },
                rockchip: GitPin { source: "rk://s".into(), reference: "rk".into(), commit: "5".repeat(40) },
            }),
            rootfs: RootfsPin {
                suite: "forky".into(),
                manifest: "rec.pkgs.lock".into(),
                manifest_sha256: None,
            },
            blobs: Some(BlobsPin {
                atf: "atf@sha256:0000000000000000000000000000000000000000000000000000000000000000".into(),
                tpl: "tpl@sha256:1111111111111111111111111111111111111111111111111111111111111111".into(),
                bl32: None,
            }),
            extra_debs: vec![],
            snapshot: None,
        }
    }

    #[test]
    fn a_distro_kernel_depthcharge_lock_pins_only_the_rootfs() {
        // The C201 shape: Debian's own kernel package, a boot method that compiles no
        // u-boot, and no rkbin blobs. Nothing is fetched from git and nothing is
        // compiled, so the only thing there *is* to pin is the package set — and the
        // committed lock says exactly that, rather than carrying three tables of
        // provenance for dependencies the build does not have.
        let lock = Lock {
            kernel: None,
            patches: None,
            uboot: None,
            userspace: None,
            ffmpeg: None,
            rootfs: RootfsPin {
                suite: "forky".into(),
                manifest: "asus-c201-forky.pkgs.lock".into(),
                manifest_sha256: None,
            },
            blobs: None,
            extra_debs: vec![],
            snapshot: None,
        };
        let text = lock.to_toml_string().unwrap();
        for absent in ["[kernel]", "[patches]", "[uboot]", "[blobs]", "[userspace", "[ffmpeg"] {
            assert!(
                !text.contains(absent),
                "a distro-kernel depthcharge lock must omit {absent}:\n{text}"
            );
        }
        assert!(text.contains("[rootfs]"));
        // And it round-trips: every omitted table reads back as an absence, not a
        // default-constructed pin.
        assert_eq!(toml::from_str::<Lock>(&text).unwrap(), lock);
    }

    #[test]
    fn a_no_patch_kernels_lock_omits_the_patches_table() {
        // A kernel that applies no series pins no `patches` commit: the committed
        // lock has no `[patches]` table at all, and round-trips back to `None` rather
        // than to a placeholder pin.
        let mut lock = base_lock();
        lock.patches = None;
        let text = lock.to_toml_string().unwrap();
        assert!(
            !text.contains("[patches]"),
            "no-patch lock must omit the table entirely:\n{text}"
        );
        assert_eq!(toml::from_str::<Lock>(&text).unwrap(), lock);
        // A lock that does pin a series still writes the table.
        let with = base_lock().to_toml_string().unwrap();
        assert!(with.contains("[patches]"));
        assert!(with.contains("profile = \"rk3588-accel\""));
    }

    #[test]
    fn deserialize_rejects_a_non_sha_commit() {
        // A lock whose kernel commit is not a full 40-hex sha is refused at parse
        // time (SUB-3), so a malformed/hand-edited value never reaches the git argv.
        let text = base_lock().to_toml_string().unwrap();
        let tampered = text.replacen(
            &format!("commit = \"{}\"", "a".repeat(40)),
            "commit = \"-o=evil\"",
            1,
        );
        assert!(
            toml::from_str::<Lock>(&tampered).is_err(),
            "a non-sha commit must be rejected at deserialize"
        );
        // An uppercase sha is accepted but canonicalized to git's lowercase form.
        let upper = text.replacen(
            &format!("commit = \"{}\"", "a".repeat(40)),
            &format!("commit = \"{}\"", "A".repeat(40)),
            1,
        );
        let back: Lock = toml::from_str(&upper).unwrap();
        assert_eq!(back.kernel.unwrap().commit, "a".repeat(40));
    }

    #[test]
    fn deserialize_rejects_malformed_blob_and_manifest_shapes() {
        // Every content-pin field is shape-checked at the parse boundary
        // (TRUST-7), so a hand-edited lock fails here, naming the field, rather
        // than misbehaving downstream where the value is joined into paths or
        // compared against hashes.
        let good = base_lock().to_toml_string().unwrap();
        let atf = format!("atf@sha256:{}", "0".repeat(64));
        assert!(good.contains(&atf), "fixture must carry the expected pin");
        for (from, to, why) in [
            // No separator at all.
            (atf.clone(), "atf-no-separator".to_string(), "separator"),
            // Digest too short / wrong case.
            (atf.clone(), format!("atf@sha256:{}", "0".repeat(63)), "64 lowercase hex"),
            (atf.clone(), format!("atf@sha256:{}", "A".repeat(64)), "64 lowercase hex"),
            // Filename with a path separator.
            (atf.clone(), format!("../atf@sha256:{}", "0".repeat(64)), "filename"),
            // Manifest must be a bare filename.
            (
                "manifest = \"rec.pkgs.lock\"".to_string(),
                "manifest = \"../rec.pkgs.lock\"".to_string(),
                "bare filename",
            ),
        ] {
            let bad = good.replacen(&from, &to, 1);
            assert_ne!(good, bad, "case failed to modify the fixture: {to}");
            let err = toml::from_str::<Lock>(&bad).unwrap_err().to_string();
            assert!(err.contains(why), "expected '{why}' in: {err}");
        }
        // manifest_sha256, when present, must be 64 lowercase hex too.
        let with_digest = good.replacen(
            "manifest = \"rec.pkgs.lock\"",
            "manifest = \"rec.pkgs.lock\"\nmanifest_sha256 = \"DEADBEEF\"",
            1,
        );
        let err = toml::from_str::<Lock>(&with_digest).unwrap_err().to_string();
        assert!(err.contains("64 lowercase hex"), "{err}");
    }

    #[test]
    fn lock_without_snapshot_omits_the_table() {
        let lock = base_lock();
        let text = lock.to_toml_string().unwrap();
        // The reserved/optional fields collapse out of the committed form when
        // unset, so the shipped lock stays minimal until a mechanism populates them.
        assert!(
            !text.contains("[snapshot]") && !text.contains("snapshot ="),
            "committed lock must not emit a snapshot table when None:\n{text}"
        );
        assert!(
            !text.contains("extra_debs"),
            "empty extra_debs must be omitted:\n{text}"
        );
        assert!(
            !text.contains("manifest_sha256"),
            "unset manifest_sha256 must be omitted:\n{text}"
        );
        let back: Lock = toml::from_str(&text).unwrap();
        assert_eq!(back.snapshot, None);
        assert!(back.extra_debs.is_empty());
        assert_eq!(back.rootfs.manifest_sha256, None);
        assert_eq!(lock, back);
    }

    #[test]
    fn base_build_lock_omits_the_media_accel_tables() {
        // A recipe with no `requires_media_accel` feature builds no userspace/ffmpeg
        // nodes, so `update` writes no pins for them. The committed lock must omit
        // both tables entirely (not empty tables) and round-trip back to `None`.
        let mut lock = base_lock();
        lock.userspace = None;
        lock.ffmpeg = None;
        let text = lock.to_toml_string().unwrap();
        assert!(
            !text.contains("[userspace") && !text.contains("[ffmpeg"),
            "base-build lock must not emit media-accel tables:\n{text}"
        );
        let back: Lock = toml::from_str(&text).unwrap();
        assert_eq!(back.userspace, None);
        assert_eq!(back.ffmpeg, None);
        assert_eq!(lock, back);
    }

    #[test]
    fn bl32_blob_pin_round_trips_and_is_omitted_when_absent() {
        // BL31-only build (RK3588/RK1): no bl32 key in the committed form, parses
        // back to None, and an older lock written without the key still loads.
        let lock = base_lock();
        assert_eq!(lock.blobs.as_ref().unwrap().bl32, None);
        let text = lock.to_toml_string().unwrap();
        assert!(!text.contains("bl32"), "absent bl32 must be omitted:\n{text}");
        assert_eq!(
            toml::from_str::<Lock>(&text).unwrap().blobs.unwrap().bl32,
            None
        );

        // OP-TEE build (RK3576): the pin is present and survives the round-trip.
        let mut with = base_lock();
        with.blobs.as_mut().unwrap().bl32 = Some("rk3576_bl32_v1.08.bin@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".into());
        let text = with.to_toml_string().unwrap();
        assert!(text.contains("bl32 = \"rk3576_bl32_v1.08.bin@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\""));
        assert_eq!(toml::from_str::<Lock>(&text).unwrap(), with);
    }
}
