//! The NuGet package pins of an app's restore: the sidecar file a `dotnet-deb` app's
//! lock entry names ([`NugetPin`](crate::lock::NugetPin)).
//!
//! A .NET build restores its packages from a feed. boot2deb's builds run with no
//! network, so the feed is a folder the engine fills before the build starts. This
//! manifest is what it fills it from: every package the restore needs, by id and
//! version, pinned by the sha512 of the `.nupkg` file.
//!
//! `update` produces it from one networked restore. `build` fetches each package,
//! verifies it against its pin, and restores offline.
//!
//! Pure: parsing, serialization and validation only.

use crate::error::ConfigError;
use serde::{Deserialize, Serialize};

/// Header prepended to a serialized manifest, marking it generated.
const BANNER: &str = "\
# Generated by `boot2deb update`; do not hand-edit.
# The NuGet packages an app's offline restore needs, each pinned by the sha512 of
# its .nupkg. `boot2deb build` fetches and verifies every one before the build.
";

/// Where nuget.org serves package files: its flat-container endpoint, which
/// addresses a package by lowercase id and normalized lowercase version.
pub const NUGET_FLAT_CONTAINER: &str = "https://api.nuget.org/v3-flatcontainer";

/// The suffix every NuGet sidecar's name ends with.
const SIDECAR_SUFFIX: &str = ".nuget.lock";

/// The file an app's NuGet pins live in: `<stem>.<app>.nuget.lock`.
///
/// One spelling for both places it lands. Beside the lock, `stem` is the recipe's
/// leaf, as the rootfs manifest's is. Beside a published image it is the image's
/// artifact stem, which is where an SBOM reads it from.
pub fn sidecar_name(stem: &str, app: &str) -> String {
    format!("{stem}.{app}{SIDECAR_SUFFIX}")
}

/// Whether a file name is a NuGet sidecar's. A sidecar shares the `.lock` extension
/// with the lock it sits beside and is not one. Anything reading a recipe directory's
/// locks by extension therefore sets these aside, as it does the rootfs manifest.
pub fn is_sidecar_name(name: &str) -> bool {
    name.ends_with(SIDECAR_SUFFIX)
}

/// Every NuGet package one app's restore needs, for one runtime.
///
/// Ordered by id, then version, and free of duplicates. The same set therefore always
/// serializes to the same bytes, and its digest in the lock is stable.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NugetManifest {
    /// The .NET runtime identifier the restore targeted, e.g. `linux-arm64`. A
    /// self-contained publish restores that runtime's packs, so the set is specific
    /// to it.
    pub runtime: String,
    /// The packages (TOML array `[[package]]`).
    #[serde(rename = "package", default)]
    pub packages: Vec<NugetPackage>,
}

/// One pinned NuGet package.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NugetPackage {
    /// The package id, lowercased the way NuGet's global packages folder and its
    /// flat-container endpoint spell it.
    pub id: String,
    /// The normalized version, lowercased likewise.
    pub version: String,
    /// sha512 of the `.nupkg` file, as 128 lowercase hex characters.
    pub sha512: String,
}

impl NugetPackage {
    /// The package's file name, `<id>.<version>.nupkg`: its name on nuget.org and in
    /// a folder feed.
    pub fn file_name(&self) -> String {
        format!("{}.{}.nupkg", self.id, self.version)
    }

    /// Where nuget.org serves this package's `.nupkg`.
    pub fn url(&self) -> String {
        format!(
            "{NUGET_FLAT_CONTAINER}/{id}/{version}/{file}",
            id = self.id,
            version = self.version,
            file = self.file_name()
        )
    }

    /// Why this entry cannot be a pin, or `None` when it can. The id and version
    /// become path components and URL segments, so they are held to the characters
    /// NuGet itself allows, lowercase.
    fn defect(&self) -> Option<String> {
        let id_ok = self
            .id
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
            && self.id.chars().all(|c| {
                c.is_ascii_lowercase() || c.is_ascii_digit() || matches!(c, '.' | '-' | '_')
            });
        if !id_ok {
            return Some(format!(
                "package id '{}' is not a lowercase NuGet id",
                self.id
            ));
        }
        let version_ok = self
            .version
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_digit())
            && self.version.chars().all(|c| {
                c.is_ascii_lowercase() || c.is_ascii_digit() || matches!(c, '.' | '-' | '+')
            });
        if !version_ok {
            return Some(format!(
                "package '{}' version '{}' is not a lowercase NuGet version",
                self.id, self.version
            ));
        }
        if !crate::sources::is_sha512_hex(&self.sha512) {
            return Some(format!(
                "package '{}' {} sha512 is not 128 lowercase hex characters",
                self.id, self.version
            ));
        }
        None
    }
}

impl NugetManifest {
    /// Build a manifest from packages in any order: sorted by id and version, an
    /// exact duplicate folded, and every entry validated.
    ///
    /// # Errors
    ///
    /// [`ConfigError::NugetManifestInvalid`], naming `origin`, when an entry is not a
    /// usable pin or one id and version carry two different hashes. The same error
    /// refuses a runtime .NET does not publish for.
    pub fn new(
        runtime: &str,
        mut packages: Vec<NugetPackage>,
        origin: &str,
    ) -> Result<Self, ConfigError> {
        packages.sort();
        packages.dedup();
        let manifest = NugetManifest {
            runtime: runtime.to_string(),
            packages,
        };
        manifest.validate(origin)?;
        Ok(manifest)
    }

    /// Serialize to the committed form: the generated-file banner and the TOML body.
    pub fn to_toml_string(&self) -> Result<String, ConfigError> {
        let body = toml::to_string(self).map_err(|source| ConfigError::Serialize {
            what: "NuGet manifest",
            source,
        })?;
        Ok(format!("{BANNER}{body}"))
    }

    /// Parse and validate a committed manifest. `path` names the file in errors and
    /// is not read from.
    ///
    /// # Errors
    ///
    /// [`ConfigError::Parse`] when the text is not a manifest, and
    /// [`ConfigError::NugetManifestInvalid`] when it parses but is not in the
    /// canonical form [`new`](Self::new) produces.
    pub fn from_toml_str(text: &str, path: &str) -> Result<Self, ConfigError> {
        let manifest: NugetManifest =
            toml::from_str(text).map_err(|source| ConfigError::Parse {
                path: path.to_string(),
                source,
            })?;
        manifest.validate(path)?;
        Ok(manifest)
    }

    /// Check the manifest is a usable, canonical pin set: a runtime .NET publishes
    /// for, every entry well-formed, and the entries strictly ordered, which also
    /// rules out duplicates. The order is what makes the file's digest a function of
    /// the set alone.
    fn validate(&self, origin: &str) -> Result<(), ConfigError> {
        let invalid = |why: String| ConfigError::NugetManifestInvalid {
            path: origin.to_string(),
            why,
        };
        if !matches!(
            self.runtime.as_str(),
            "linux-x64" | "linux-arm64" | "linux-arm"
        ) {
            return Err(invalid(format!(
                "runtime '{}' is not one .NET publishes for",
                self.runtime
            )));
        }
        for package in &self.packages {
            if let Some(why) = package.defect() {
                return Err(invalid(why));
            }
        }
        for pair in self.packages.windows(2) {
            let (a, b) = (&pair[0], &pair[1]);
            if (&a.id, &a.version) == (&b.id, &b.version) {
                return Err(invalid(format!(
                    "package '{}' {} is pinned twice",
                    a.id, a.version
                )));
            }
            if a > b {
                return Err(invalid(format!(
                    "packages are not sorted: '{}' {} comes before '{}' {}",
                    a.id, a.version, b.id, b.version
                )));
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn pkg(id: &str, version: &str, fill: char) -> NugetPackage {
        NugetPackage {
            id: id.to_string(),
            version: version.to_string(),
            sha512: fill.to_string().repeat(128),
        }
    }

    /// The same set in any order is the same manifest, and so the same bytes: the
    /// lock pins the file's digest, which must not depend on the order a restore
    /// happened to list its packages in.
    #[test]
    fn a_manifest_is_canonical_whatever_order_it_is_built_from() {
        let a = NugetManifest::new(
            "linux-arm64",
            vec![
                pkg("skiasharp", "3.119.0", 'b'),
                pkg("asynckeyedlock", "7.1.4", 'a'),
            ],
            "t",
        )
        .unwrap();
        let b = NugetManifest::new(
            "linux-arm64",
            vec![
                pkg("asynckeyedlock", "7.1.4", 'a'),
                pkg("skiasharp", "3.119.0", 'b'),
                pkg("asynckeyedlock", "7.1.4", 'a'),
            ],
            "t",
        )
        .unwrap();
        assert_eq!(a, b, "an exact duplicate folds");
        assert_eq!(a.to_toml_string().unwrap(), b.to_toml_string().unwrap());
        assert_eq!(a.packages[0].id, "asynckeyedlock");
    }

    #[test]
    fn a_manifest_round_trips_through_its_committed_form() {
        let m = NugetManifest::new(
            "linux-arm64",
            vec![pkg("a.b", "1.0.0-preview.1", 'c'), pkg("z", "2.0.0", 'd')],
            "t",
        )
        .unwrap();
        let text = m.to_toml_string().unwrap();
        assert!(text.starts_with("# Generated by `boot2deb update`"));
        assert!(text.contains("[[package]]"));
        assert_eq!(NugetManifest::from_toml_str(&text, "t").unwrap(), m);
    }

    /// One id and version pinned to two hashes is not a set the build could verify
    /// against, and a hand-reordered file would change the digest the lock pins.
    #[test]
    fn a_non_canonical_or_malformed_manifest_is_refused() {
        let twice = NugetManifest::new(
            "linux-arm64",
            vec![pkg("a", "1.0.0", 'a'), pkg("a", "1.0.0", 'b')],
            "t",
        );
        assert!(matches!(
            twice,
            Err(ConfigError::NugetManifestInvalid { .. })
        ));

        let unsorted = format!(
            "runtime = \"linux-arm64\"\n\
             [[package]]\nid = \"z\"\nversion = \"1.0.0\"\nsha512 = \"{h}\"\n\
             [[package]]\nid = \"a\"\nversion = \"1.0.0\"\nsha512 = \"{h}\"\n",
            h = "e".repeat(128)
        );
        assert!(matches!(
            NugetManifest::from_toml_str(&unsorted, "t"),
            Err(ConfigError::NugetManifestInvalid { .. })
        ));

        for bad in [
            pkg("../escape", "1.0.0", 'a'),
            pkg("UpperCase", "1.0.0", 'a'),
            pkg("a", "v1", 'a'),
            NugetPackage {
                sha512: "A".repeat(128),
                ..pkg("a", "1.0.0", 'a')
            },
        ] {
            assert!(
                NugetManifest::new("linux-arm64", vec![bad.clone()], "t").is_err(),
                "{bad:?} must be refused"
            );
        }
        assert!(NugetManifest::new("win-x64", vec![], "t").is_err());
    }

    #[test]
    fn a_sidecar_is_named_for_its_stem_and_app_and_recognized_by_its_suffix() {
        let name = sidecar_name("forky+jellyfin", "jellyfin");
        assert_eq!(name, "forky+jellyfin.jellyfin.nuget.lock");
        assert!(is_sidecar_name(&name));
        assert!(!is_sidecar_name("forky+jellyfin.lock"));
        assert!(!is_sidecar_name("forky.pkgs.lock"));
    }

    #[test]
    fn a_package_is_addressed_on_the_flat_container_by_lowercase_id_and_version() {
        let p = pkg("microsoft.netcore.app.runtime.linux-arm64", "10.0.12", 'a');
        assert_eq!(
            p.url(),
            "https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.linux-arm64/\
             10.0.12/microsoft.netcore.app.runtime.linux-arm64.10.0.12.nupkg"
        );
        assert_eq!(
            p.file_name(),
            "microsoft.netcore.app.runtime.linux-arm64.10.0.12.nupkg"
        );
    }
}
